### ISSUE TITLE
SerializationComponentRegistrar is not compatible with this version of compiler (1.2.31?)

### ISSUE THREAD

**Issue by KucherenkoIhor** [Kotlin/kotlinx.serialization#87] opened 2018-02-16 07:34 UTC
Error:Kotlin: [Internal Error] java.lang.IllegalStateException: The provided plugin org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationComponentRegistrar is not compatible with this version of compiler
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:178)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:114)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:409)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.createCoreEnvironment(K2JVMCompiler.kt:286)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.createEnvironmentWithScriptingSupport(K2JVMCompiler.kt:276)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:155)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:63)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:109)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:53)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:92)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$$inlined$ifAlive$lambda$1.invoke(CompileServiceImpl.kt:381)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$$inlined$ifAlive$lambda$1.invoke(CompileServiceImpl.kt:97)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:895)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:97)
	at org.jetbrains.kotlin.daemon.common.DummyProfiler.withMeasure(PerfUtils.kt:137)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.checkedCompile(CompileServiceImpl.kt:925)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.doCompile(CompileServiceImpl.kt:894)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:379)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:346)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AbstractMethodError: org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationComponentRegistrar.registerProjectComponents(Lcom/intellij/mock/MockProject;Lorg/jetbrains/kotlin/config/CompilerConfiguration;)V
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:176)
	... 34 more

**Comment by sandwwraith** [comment] 2018-02-16 10:31
Which version of Kotlin compiler do you use?

**Comment by KucherenkoIhor** [comment] 2018-02-16 11:06
@sandwwraith 1.2.21

**Comment by sandwwraith** [comment] 2018-02-16 17:10
Is this error occurs during Gradle build or IDEA build?

**Comment by KucherenkoIhor** [comment] 2018-02-18 12:42
I don’t know why and how. But it works now. Thank you

**Comment by appsonair** [comment] 2018-02-23 01:53
I do have the same issue. It only happens when I build using the IDEA build from the IDE

**Comment by gic888** [comment] 2018-03-03 22:58
I also see this issue using IDEA builds (but not when using Gradle command line builds). I've had this issue off and on over several versions. 

I briefly had things working under the 1.2.21 version of the Idea Kotlin plugin. The upgrade to the 1.2.30 IDEA plugin broke the build, and so far I am unable to repair it (I've tried removing the plugin, and installing 1.2.1 from disk. No luck there).  

It seems that every patch release breaks this build, which makes the serialization library practically unusable with IDEA projects. Since everything works nicely for CLI builds, it could be an issue specific to the IDEA plugin, not this library, but if this library depends on a specific patch version of the Kotlin compiler, that seems like a serious flaw.

**Comment by sandwwraith** [comment] 2018-03-07 14:02
This library does not depend on any particular patch version of compiler; however, because it uses internal and undocumented compiler API, which may vary from version to version, sometimes it got broken. 

However, this issue is most commonly caused by incorrect project import from gradle. Re-importing the project forces idea to correct resolving of plugin jars.

**Comment by tristancaron** [comment] 2018-03-23 15:04
Facing the same error when trying to compile from IDEA

**Comment by sandwwraith** [comment] 2018-03-30 10:33
@gladed Do you have stacktrace same as here or same as #97 ?

**Comment by gladed** [comment] 2018-03-30 13:54
It's the exception in this issue. I could only avoid it by using "Delegate IDE Build/Run Actions to Gradle".

**Comment by Anonymous20180110** [comment] 2018-04-07 09:14
Delegate IDE Build/Run Actions to Gradle didn't fix it for me. Still got this error:
```

Error:Kotlin: [Internal Error] java.lang.IllegalStateException: The provided plugin org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationComponentRegistrar is not compatible with this version of compiler
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:181)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:117)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:413)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.createCoreEnvironment(K2JVMCompiler.kt:276)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:154)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:63)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:108)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:92)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$$inlined$ifAlive$lambda$1.invoke(CompileServiceImpl.kt:389)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$$inlined$ifAlive$lambda$1.invoke(CompileServiceImpl.kt:97)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:909)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:97)
	at org.jetbrains.kotlin.daemon.common.DummyProfiler.withMeasure(PerfUtils.kt:137)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.checkedCompile(CompileServiceImpl.kt:939)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.doCompile(CompileServiceImpl.kt:908)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:387)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:361)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AbstractMethodError
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:179)
	... 33 more

```

**Comment by Anonymous20180110** [comment] 2018-04-07 09:15
It would be really good if the code on this github repo, worked out the box.

**Comment by davidmoshal** [comment] 2018-04-13 20:06
ran into this issue while evaluating kotlin as a groovy replacement - guess it's not ready for prime time.

**Comment by reisi007** [comment] 2018-04-14 18:48
I am having the same problem. Delegating build to gradle works here...

**Comment by davidm-public** [comment] 2018-04-15 22:59
thanks, I tried that, and was able to run the file, but ran into another execption:

Exception in thread "main" kotlinx.serialization.SerializationException: Can't locate default serializer for class class K2Kt$main$x$1 (Kotlin reflection is not available)

**Comment by sandwwraith** [comment] 2018-04-17 13:59
There's a recently published version of IDEA plugin compatible with 1.2.31 Kotlin IDEA plugin, please try it out and say if it works: [link](https://teamcity.jetbrains.com/viewLog.html?buildId=lastPinned&buildTypeId=KotlinTools_KotlinxSerialization_KotlinCompilerWithSerializationPlugin&tab=artifacts&guest=1&buildBranch=1.2.30). I've updated the README accordingly. However, delegating build to gradle is still preferred method to work, since JPS has no multiplatform support.

**Comment by sandwwraith** [comment] 2018-04-17 14:00
@davidmoshal No, kotlin version number in buildscript doesn't override version in IDE.

**Comment by sandwwraith** [comment] 2018-04-17 14:01
@davidm-public Have you read the docs? You need to mark your class as `@Serializable` to be able to work with its generated serializers, since this library does not use reflection

**Comment by davidm-public** [comment] 2018-04-17 14:36
@sandwwraith  which docs? 

I tried adding `@Serializable' to the anon object in my example above but that didn't work.

Don't get me wrong, I like the concept of Kotlin, and have followed it since the beginning, 2012 I think, just saying that it doesn't seem stable enough to replace Groovy
 - not that Groovy really needs replacing.

**Comment by sandwwraith** [comment] 2018-04-17 14:43
@davidm-public This works good for me:

```kotlin
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JSON

fun main(args: Array<String>) {
    val x = @Serializable object {
        val a = 12
    }
    println(JSON.stringify(x)) // prints {"a":12}
}
```

So it's likely you forgot to apply plugin or delegate build, etc.. If you still feel that there's something wrong – feel free to open separate issue where you can describe your setup and example code in details, since it's completely offtopic here.

**Comment by davidm-public** [comment] 2018-04-17 14:48
thanks, that's what I tried, will try again later.
it does work with other, non-anonymous, classes.

seems to compile faster than Groovy.

Dave

**Comment by DanielThomas** [comment] 2018-06-13 16:35
Installing the plugin has never been enough for me, there's something else at play here too. Strangely, if I have the plugin installed, and then IntelliJ updates, it starts working(!).

**Comment by thejakeofink** [comment] 2018-06-30 02:43
I am seeing this with 1.2.50

**Comment by nhajratw** [comment] 2018-07-25 17:29
same problem with 1.2.51

**Comment by sandwwraith** [comment] 2018-07-25 17:31
1. Check version of Kotlin plugin in IDEA and `build.gradle`, check version of serialization plugin in IDEA and `build.gradle`, then check compatibility table.
2. Re-import project from gradle.

**Comment by pecota** [comment] 2018-07-27 19:30
I have the same issue, but when I run the project on the command line it works perfectly.
It looks like an IDEA bug.

**Comment by sandwwraith** [comment] 2019-11-28 17:54
I think this is kinda old, and since Kotlin serialization IDE plugin is bundled into Kotlin IDE plugin since Kotlin 1.3, this is also obsolete.

**Closed by sandwwraith** 2019-11-28 17:54 UTC
