### ISSUE TITLE
Alias support And api to retrieve type info

### ISSUE THREAD

**Issue by shxhzhxx** [Kotlin/kotlinx.serialization#519] opened 2019-07-18 10:48 UTC
1.
I know that SerialName could overriding property name.
But what I need is Many-to-one mapping.
eg.
data class Example( @JsonAlias("tips", "errorMsg", "message") val msg: String )
"tips,errorMsg,message,msg" any of these appears in raw json data would be the value of msg property,
although the priority is arbitrary.

2.
To work around type erasure,  type info is necessary. If I can retrieve it from KSerializer<T>,  
could eliminate the need to add additional parameter.

**Comment by pdvrieze** [comment] 2019-07-18 13:37
Perhaps this feature should be supported in the general case, not only for Json. It is not too hard to implement as the structure containing the field has access to the child descriptors and can search for one with the given alias. The hardest would be for the plugin to check against duplicates.

**Comment by sandwwraith** [comment] 2020-07-23 18:15
1. Duplicate of #203 
2. Type info can be obtained from `typeOf` function. Serialization-related metadata is available in `KSerializer.descriptor`.

**Closed by sandwwraith** 2020-07-23 18:15 UTC
Labels: question
