### ISSUE TITLE
NoClassDefFoundError on JVM without kotlin-reflect calling Json.stringify

### ISSUE THREAD

**Issue by benjamin-bader** [Kotlin/kotlinx.serialization#570] opened 2019-10-04 19:43 UTC
**Describe the bug**

In a multiplatform library project, I've got a JVM unit test that attempts to stringify a simple data class to json.  It's a hard requirement for me not to use `kotlin-reflect`.  Unfortunately, this test fails with a `NoClassDefFoundError` _unless_ I include `kotlin-reflect`.

The exception happens when loading the class `kotlinx.serialization.json.Json`.  When running the class initializer, it [attempts to build a `Map<KClass<*>, KSerializer<*>>`](https://github.com/Kotlin/kotlinx.serialization/blob/master/runtime/commonMain/src/kotlinx/serialization/json/Json.kt#L215), which seems not possible without kotlin-reflect.

**To Reproduce**

In a multiplatform project's `jvmTest` sourceSet, without kotlin-reflect:

```kt
@Serializable
data class SampleData(val counter: Int)

class JsonTest {
  @Test fun sample() {
    assertEquals(
      Json.stringify(SampleData.serializer(), SampleData(5),
       """{"counter":5}"""
    )
  }
}
```

**Expected behavior**

I'd expect the test to pass.

**Actual behavior**

```
kotlin/reflect/KPackage
java.lang.NoClassDefFoundError: kotlin/reflect/KPackage
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at kotlin.jvm.internal.Reflection.<clinit>(Reflection.java:26)
	at kotlinx.serialization.json.JsonKt.<clinit>(Json.kt:216)
	at kotlinx.serialization.json.Json.<init>(Json.kt:63)
	at kotlinx.serialization.json.Json.<init>(Json.kt:62)
	at kotlinx.serialization.json.Json.<clinit>(Json.kt:160)
	at com.example.JsonTest.sample(JsonTest.kt:25)
        ...
```

**Environment**
 - Kotlin version: 1.3.50
 - Library version: 0.13.0
 - Kotlin platforms: JVM, Android, iOS
 - Gradle version: 5.6.1

**Comment by sandwwraith** [comment] 2019-10-11 15:24
kotlinx-serialization does not contain any dependencies on kotlin-reflect.jar. You can see it in `integration-test` project, such a test would fail:

```kotlin
@Test
    fun kotlinReflectNotInClasspath() {
        val klass = Json::class
        println(klass.qualifiedName)
    }
```

Usually, there is a message like `kotlin.jvm.KotlinReflectionNotSupportedError: Kotlin reflection implementation is not found at runtime. Make sure you have kotlin-reflect.jar in the classpath`. In your case (NCDFE), this error is probably caused by wrong stdlib version dependency or other kotlin versions mismatch. If it is possible, you could share a project with a reproducer.

**Comment by benjamin-bader** [comment] 2019-10-11 16:47
Interesting, I didn't know about the different exception types, and assumed NCDFE meant "no kotlin-reflect".  I'll see if I can get a minimal (and shareable) repro.

**Comment by qwwdfsad** [comment] 2020-07-07 14:23
Closing as outdates. Please reopen if you still encounter this issue and have a self-containing reproducer

**Closed by qwwdfsad** 2020-07-07 14:23 UTC
Labels: can't reproduce
