### ISSUE TITLE
overridden variables from extended class are not serialized

### ISSUE THREAD

**Issue by dri94** [Kotlin/kotlinx.serialization#381] opened 2019-02-18 14:17 UTC
I have an object that extends an abstract class that inherits an interface. When using kotlin serialization, it will not serialize the properties on the abstract class.
For example:

    @Serializable
    class User(private val uid: String = ""): BaseClass()

    abstract class BaseClass(): CacheClass {
        override val cacheDate: Long = 0L
    }

    interface CacheClass {
        val cacheDate: Long
    }

The variable `cacheDate` will never get serialized. How can I ensure that the variables defined on the abstract or open class will in fact be serialized?

**Comment by sandwwraith** [comment] 2019-02-25 11:37
Try to mark `BaseClass` as Serializable, too

**Comment by dri94** [comment] 2019-02-25 13:39
@sandwwraith That creates a polymorphic error

**Comment by sandwwraith** [comment] 2019-03-01 12:04
Which 'polymorphic error' exactly do you mean?

Anyway, this seems to be fixed in latest master.

**Comment by dri94** [comment] 2019-04-16 13:58
When using the structure
```
@Serializable
class User(private val uid: String = ""): BaseClass()

@Serializable
abstract class BaseClass(): CacheClass {
    override val cacheDate: Long = 0L
}

interface CacheClass {
    val cacheDate: Long
}
```
i get
`No direct method <init>(ILkotlinx/serialization/SerializationConstructorMarker;)V in class Lcom/expapp/atlas/model/AtlasModel; or its super classes (declaration of 'com.expapp.atlas.model.AtlasModel' appears in /data/app/com.expapp.atlas.stage-o3dPPIykrDABzXlyPydyOg==/split_lib_slice_8_apk.apk)`

When using the structure
```
@Serializable
class User(private val uid: String = ""): BaseClass()

abstract class BaseClass(): CacheClass {
    override val cacheDate: Long = 0L
}

interface CacheClass {
    val cacheDate: Long
}
```
I am not getting the `cacheDate` variable back still.

I am using kotlin 1.3.30 with serialization library 0.11

**Comment by sandwwraith** [comment] 2019-04-19 14:52
I'm unable to reproduce your problem on 1.3.30, make sure you use this version. Also, maybe clean build can help? What is the exact definition of `com.expapp.atlas.model.AtlasModel`?

**Comment by dri94** [comment] 2019-04-23 17:54
I am using 1.3.30. Doing a clean build was done. Here is my definition
AtlasModel
```
abstract class AtlasModel : Cacheable {
    @Transient
    protected val LOG_TAG = javaClass.simpleName
    override var cachedAt: Long = - 1
    override var cacheVersion: Int = - 1
    @Transient
    override val isValid: Boolean
        get() = ! isStale

    @Transient
    override val isStale: Boolean
        get() = false

    fun prefix(): String {
        return javaClass.simpleName.toLowerCase() + "-"
    }

    fun prefix(key: String, name: String = javaClass.simpleName.toLowerCase()): String {
        return "$name-$key"
    }

    override fun isCacheVersionSupported(minimumVersion: Int): Boolean {
        return this.cacheVersion != - 1 && this.cacheVersion >= minimumVersion
    }

    companion object {

        @UnstableDefault
        @UseExperimental(ImplicitReflectionSerializer::class)
        inline fun <reified T : Cacheable> fromJson(json: String): T {
            return Json.nonstrict.parse(json)
        }

        @UnstableDefault
        @UseExperimental(ImplicitReflectionSerializer::class)
        inline fun <reified T: Cacheable> fromJsonList(json: String): List<T> {
            return Json.nonstrict.parseList(json)
        }

        @UnstableDefault
        @UseExperimental(ImplicitReflectionSerializer::class)
        inline fun <reified T: Cacheable> toJson(value: List<T>): String {
            return Json.nonstrict.stringify(value)
        }

        @UnstableDefault
        @UseExperimental(ImplicitReflectionSerializer::class)
        inline fun <reified T: Any> toJson(value: T): String {
            return Json.nonstrict.stringify(value)

        }
    }

}
```

Cacheable
```
interface Cacheable {
    var cachedAt: Long
    val isValid: Boolean
    val isStale: Boolean
    var cacheVersion: Int
    fun isCacheVersionSupported(minimumVersion: Int): Boolean
}
```

**Comment by whoyawn** [comment] 2019-12-04 23:58
You may want to check the property names in your `default.json.bak` file, that did the trick for me.

**Comment by sandwwraith** [comment] 2020-07-23 17:39
Seems to be an old problem with class hierarchies scattered across different modules, which is solved now: https://github.com/Kotlin/kotlinx.serialization/issues/378#issuecomment-663134060

**Closed by sandwwraith** 2020-07-23 17:39 UTC
Labels: In next release, question
