### ISSUE TITLE
Annotating property type with @Serializable does not override default serializer in typealias

### ISSUE THREAD

**Issue by iseki0** [Kotlin/kotlinx.serialization#2358] opened 2023-07-05 17:43 UTC
**Describe the bug**
Annotating property type with `@Serializable` does not override default serializer in typealias. (Just like Kotlin/kotlinx.serialization#1895)
**To Reproduce**
Attach a code snippet or test data if possible.
```kotlin
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.serializer


object FooSerializer : KSerializer<A> {
    override val descriptor: SerialDescriptor
        get() = TODO()
    override fun deserialize(decoder: Decoder): A {
        TODO()
    }

    override fun serialize(encoder: Encoder, value: A) {
        TODO("Not yet implemented")
    }
}

@Serializable
data class A(val a: Int)
data class B(val a: Int)
typealias Foo = @Serializable(FooSerializer::class) A
typealias Foooo = @Serializable(FooSerializer::class) B

fun main() {
    println(serializer<Foo>()) // A$$serializer@3b95a09c
    println(serializer<Foooo>()) // FooSerializer@2b05039f
}
```

**Expected behavior**
All of them should print `FooSerializer@*`
**Environment**
 - Kotlin version: 1.8.22
 - Library version: 1.5.1
 - Kotlin platforms: JVM
 - Gradle version: 8.2
 - IDE version: IntelliJ IDEA 2023.1.2 (Ultimate Edition) Build #IU-231.9011.34, built on May 16, 2023
 - Other relevant context: OpenJDK 17

**Comment by sandwwraith** [comment] 2023-07-07 16:38
Duplicate of #2264. In reality, Kotlin compiler expands typealiases before call, so serialization plugin is unable to do anything.

**Closed by sandwwraith** 2023-07-07 16:38 UTC
