### ISSUE TITLE
@Serializable on interface causes ClassFormatError

### ISSUE THREAD

**Issue by NorbertSandor** [Kotlin/kotlinx.serialization#374] opened 2019-02-13 17:08 UTC
JDK: 12.ea.26-open

```
// Runtime error: java.lang.ClassFormatError: Interface cannot have a method named <init>
@Serializable
interface Test
```

**Comment by sandwwraith** [comment] 2019-02-14 10:03
Duplicate of #138, I think – serializable interfaces are not supported officially

**Closed by sandwwraith** 2019-02-14 10:03 UTC
