### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by StokeMasterJack** [Kotlin/kotlinx.serialization#1817] opened 2022-01-06 22:21 UTC
When there is an error parsing the JSON, the error messages are often cryptic. And for a large object, it can take hours to find the issue. For example:

Unsupported type: [{"taxable":true,"vendorItemId":1,"description":"This is the description. 123","vendorPartId":"123","leadTime":20,"expectedDate":"2022-01-26","type":7,"inv":false,"jobId":192383,"rate":2,"qty":22,"seq":1,"shipTerms":"Ramko"},{"taxable":true,"vendorItemId":2,"description":"This is the description. 333","vendorPartId":"333","leadTime":20,"expectedDate":"2022-01-26","type":1,"inv":false,"jobId":null,"rate":333,"qty":5,"seq":2,"shipTerms":"Ramko"}]

It would be helpful, if it could give an exact line and column. Or say which field it crapped out on. Or say _which_ type is unsupported.

**Comment by sandwwraith** [comment] 2022-01-17 15:14
Duplicate of #1137 ?

**Closed** 2022-05-12 10:52 UTC
Labels: feature, duplicate
