### ISSUE TITLE
Cycles in object graph

### ISSUE THREAD

**Issue by wafisher** [Kotlin/kotlinx.serialization#456] opened 2019-05-16 19:23 UTC
**Describe the bug**
I get a StackOverflowError when serializing objects that have a reference cycle.

```
...
at org.lirr.backend.model.domain.Train.write$Self(Train.kt:41)
	at org.lirr.backend.model.domain.Train$$serializer.serialize(Train.kt)
	at org.lirr.backend.model.domain.Train$$serializer.serialize(Train.kt:34)
	at kotlinx.serialization.json.internal.StreamingJsonOutput.encodeSerializableValue(StreamingJsonOutput.kt:225)
	at kotlinx.serialization.ElementValueEncoder.encodeSerializableElement(ElementWise.kt:83)
	at org.lirr.backend.model.domain.Event.write$Self(Event.kt:22)
	at org.lirr.backend.model.domain.Event$$serializer.serialize(Event.kt)
	at org.lirr.backend.model.domain.Event$$serializer.serialize(Event.kt:19)
	at kotlinx.serialization.json.internal.StreamingJsonOutput.encodeSerializableValue(StreamingJsonOutput.kt:225)
	at kotlinx.serialization.ElementValueEncoder.encodeSerializableElement(ElementWise.kt:83)
	at kotlinx.serialization.internal.ListLikeSerializer.serialize(CollectionSerializers.kt:93)
	at kotlinx.serialization.json.internal.StreamingJsonOutput.encodeSerializableValue(StreamingJsonOutput.kt:225)
	at kotlinx.serialization.ElementValueEncoder.encodeSerializableElement(ElementWise.kt:83)
	at org.lirr.backend.model.domain.Train.write$Self(Train.kt:91)
	at org.lirr.backend.model.domain.Train$$serializer.serialize(Train.kt)
	at org.lirr.backend.model.domain.Train$$serializer.serialize(Train.kt:34)
	at kotlinx.serialization.json.internal.StreamingJsonOutput.encodeSerializableValue(StreamingJsonOutput.kt:225)
	at kotlinx.serialization.ElementValueEncoder.encodeSerializableElement(ElementWise.kt:83)
	at org.lirr.backend.model.domain.Event.write$Self(Event.kt:22)
	at org.lirr.backend.model.domain.Event$$serializer.serialize(Event.kt)
	at org.lirr.backend.model.domain.Event$$serializer.serialize(Event.kt:19)
...
```

**To Reproduce**
```
@Serializable
class Event {
    lateinit var record: Train
    [...other fields...]
}

@Serializable
class Train {
    lateinit var events: List<Event>
    [...other fields...]
}

val myTrain = Train()
val myEvent = Event().apply {
    record = myTrain
}
myTrain.events = listOf(myEvent)
val json = Json.stringify(Train.serializer(), myTrain)
```

**Expected behavior**
No `StackOverflowError` and the ability to recover the links when parsing.

**Environment**
 - Kotlin version: 1.3.31
 - Library version: 0.11.0
 - Kotlin platforms: JVM
 - Gradle version: 5.4

**Comment by sandwwraith** [comment] 2019-05-16 20:35
Unfortunately, recursive structures are currently not supported by JSON (and any other standard format). There is a plenty requests for it, e.g. #15

**Comment by wafisher** [comment] 2019-05-17 03:45
Does that mean there's no way to do cycles with any of the output formats? Or just a problem with JSON?

**Comment by sandwwraith** [comment] 2019-05-17 14:14
It means that currently provided formats (including `Json` class) do not support such references. Theoretically, it is possible to implement a custom format (i.e. Encoder/Decoder and so on) which could support such references and produce JSON output.

**Comment by qwwdfsad** [comment] 2020-07-07 14:01
Closing as duplicate of #15

**Closed by qwwdfsad** 2020-07-07 14:01 UTC
Labels: duplicate, feature
