### ISSUE TITLE
Custom Nullable Int serializer is not used to deserialize nullable Int

### ISSUE THREAD

**Issue by LDuncAndroid** [Kotlin/kotlinx.serialization#978] opened 2020-08-16 22:48 UTC
**Describe the bug**
I cannot deserialize null values to values I want when using a custom serializer. The custom serializer is used when the correct type (`Int`) is supplied as a constructor parameter, but when `null` is used the serializer is not used at all (based upon breakpoints added).

I've attached a couple of tests using the Kotest Lib. But this is reproducible in prod too.

**To Reproduce**
```
@Serializable
data class ClassWithNullableInt(@Serializable(with = NullableIntSerializer::class) val value: Int?)

class NullableIntSerializer : KSerializer<Int?> {

    private val delegate = Int.serializer().nullable
    override val descriptor: SerialDescriptor = delegate.descriptor

    override fun serialize(encoder: Encoder, value: Int?) {
        if (value == null) {
            delegate.serialize(encoder, 0)
        } else {
            delegate.serialize(encoder, value)
        }
    }

    override fun deserialize(decoder: Decoder): Int? {
        return delegate.deserialize(decoder) ?: 0
    }
}

@UnstableDefault
@ImplicitReflectionSerializer
class NullableIntSerializerTests : FunSpec({
    val json = Json(JsonConfiguration.Default)

    test("null value should deserialize as equal to 0") {
        val nullInt = ClassWithNullableInt(null)
        val zeroInt = ClassWithNullableInt(0)

        val jsonStringNullInt = json.stringify(ClassWithNullableInt.serializer(), nullInt)

        jsonStringNullInt shouldBe """{"value":0}"""

        val zeroInt2 = json.parse(ClassWithNullableInt.serializer(), jsonStringNullInt)

        zeroInt2 shouldBe zeroInt
    }

    test("0 value should deserialize as equal to 0") {
        val zeroInt = ClassWithNullableInt(0)
        val jsonStringZeroInt = json.stringify(ClassWithNullableInt.serializer(), zeroInt)

        jsonStringZeroInt shouldBe """{"value":0}"""

        val zeroInt2 = json.parse(ClassWithNullableInt.serializer(), jsonStringZeroInt)

        zeroInt2 shouldBe zeroInt
    }

})

```

**Expected behavior**
I'd expect an instance of `ClassWithNullableInt` instantiated as follows `ClassWithNullableInt(null)` to produce a Json string like `"""{"value":0}"""` when supplied as the value parameter of the function `stringify` `json.stringify(ClassWithNullableInt.serializer(), nullInt)`

**Environment**
 - Kotlin version: 1.3.72
 - Library version: 0.20.0
 - Kotlin platforms: JVM
 - Gradle version: 6.3
 - Other relevant context [e.g. OS version, JRE version, ... ]: 
Ubuntu: `4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
Java: ```openjdk 13.0.2 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.2+8)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.2+8, mixed mode, sharing)```

**Comment by qwwdfsad** [comment] 2020-08-17 08:11
Thanks for the self-contained report!
This is already fixed in 1.0.0-RC (ETA of release -- today).
Closing as duplicate of #824

**Closed by qwwdfsad** 2020-08-17 08:11 UTC

**Comment by balvinderg** [comment] 2023-06-30 08:30
hey @qwwdfsad i am still facing this issue on 1.5.2. Is it possible that in future versions , this started happening again?

**Comment by sandwwraith** [comment] 2023-06-30 10:57
@balvinderg If you're seeing this on 1.5.1, please file a new issue with reproducer
