### ISSUE TITLE
NullPointerException when trying to add @Serializable to class with by delegate

### ISSUE THREAD

**Issue by Dakkakk** [Kotlin/kotlinx.serialization#2178] opened 2023-01-29 07:25 UTC
**Describe the bug**
Gradle Build fail when I trying to apply a `@Serializable` annotation to a class with deleagtes
**To Reproduce**
Attach a code snippet or test data if possible.
```kotlin
@Serializable
class A(
    val a:Int,val b:String
)
@Serializable
class B:MutableList<A> by mutableListOf()
```

**Environment**
kotlinVersion = "1.8.0"
kotlinXSerializationVersion = "1.5.0-RC"
platform="jvm"
gradle verion=8.0-rc-1
IntelliJ IDEA 2022.3.2 (Community Edition)

**The Crash Report**
```kotlin
Problem with `@Serializable
class B : MutableList<A> {
  constructor() /* primary */ {
    super/*Any*/()
    /* <init>() */

  }

  private /* final field */ val $$delegate_0: MutableList<A> = mutableListOf<A>()
  override val size: Int
    override get(): Int {
      return <this>.#$$delegate_0.<get-size>()
    }

  override fun add(index: Int, element: A) {
    <this>.#$$delegate_0.add(index = index, element = element)
  }

  override fun add(element: A): Boolean {
    return <this>.#$$delegate_0.add(element = element)
  }

  override fun addAll(index: Int, elements: Collection<A>): Boolean {
    return <this>.#$$delegate_0.addAll(index = index, elements = elements)
  }

  override fun addAll(elements: Collection<A>): Boolean {
    return <this>.#$$delegate_0.addAll(elements = elements)
  }

  override fun clear() {
    <this>.#$$delegate_0.clear()
  }

  override operator fun contains(element: A): Boolean {
    return <this>.#$$delegate_0.contains(element = element)
  }

  override fun containsAll(elements: Collection<A>): Boolean {
    return <this>.#$$delegate_0.containsAll(elements = elements)
  }

  override operator fun get(index: Int): A {
    return <this>.#$$delegate_0.get(index = index)
  }

  override fun indexOf(element: A): Int {
    return <this>.#$$delegate_0.indexOf(element = element)
  }

  override fun isEmpty(): Boolean {
    return <this>.#$$delegate_0.isEmpty()
  }

  override operator fun iterator(): MutableIterator<A> {
    return <this>.#$$delegate_0.iterator()
  }

  override fun lastIndexOf(element: A): Int {
    return <this>.#$$delegate_0.lastIndexOf(element = element)
  }

  override fun listIterator(): MutableListIterator<A> {
    return <this>.#$$delegate_0.listIterator()
  }

  override fun listIterator(index: Int): MutableListIterator<A> {
    return <this>.#$$delegate_0.listIterator(index = index)
  }

  override fun remove(element: A): Boolean {
    return <this>.#$$delegate_0.remove(element = element)
  }

  override fun removeAll(elements: Collection<A>): Boolean {
    return <this>.#$$delegate_0.removeAll(elements = elements)
  }

  override fun removeAt(index: Int): A {
    return <this>.#$$delegate_0.removeAt(index = index)
  }

  override fun retainAll(elements: Collection<A>): Boolean {
    return <this>.#$$delegate_0.retainAll(elements = elements)
  }

  override operator fun set(index: Int, element: A): A {
    return <this>.#$$delegate_0.set(index = index, element = element)
  }

  override fun subList(fromIndex: Int, toIndex: Int): MutableList<A> {
    return <this>.#$$delegate_0.subList(fromIndex = fromIndex, toIndex = toIndex)
  }

  companion object Companion {
    private constructor() /* primary */ {
      super/*Any*/()
      /* <init>() */

    }

    /* fake */ override operator fun equals(other: Any?): Boolean
    /* fake */ override fun hashCode(): Int
    /* fake */ override fun toString(): String
    fun serializer(): KSerializer<B>
  }

  @Deprecated(message = "This synthesized declaration should not be used directly", replaceWith = ReplaceWith(expression = "", imports = []), level = DeprecationLevel.HIDDEN)
  object $serializer : GeneratedSerializer<B> {
    private constructor() /* primary */ {
      super/*Any*/()
      /* <init>() */

    }

    /* fake */ override operator fun equals(other: Any?): Boolean
    /* fake */ override fun hashCode(): Int
    /* fake */ override fun toString(): String
    /* fake */ override fun typeParametersSerializers(): Array<KSerializer<*>>
    override val descriptor: SerialDescriptor
      override get(): SerialDescriptor
    override fun childSerializers(): Array<KSerializer<*>>
    override fun deserialize(decoder: Decoder): B
    override fun serialize(encoder: Encoder, value: B)
  }

  /* fake */ override operator fun equals(other: Any?): Boolean
  /* fake */ override fun forEach(p0: @FlexibleNullability Consumer<in @FlexibleNullability A?>?)
  /* fake */ override fun hashCode(): Int
  /* fake */ override fun parallelStream(): @EnhancedNullability Stream<@EnhancedNullability A>
  /* fake */ override fun removeIf(p0: @EnhancedNullability Predicate<in @EnhancedNullability A>): Boolean
  /* fake */ override fun replaceAll(p0: @EnhancedNullability UnaryOperator<@EnhancedNullability A>)
  /* fake */ override fun sort(p0: @FlexibleNullability Comparator<in @FlexibleNullability A?>?)
  /* fake */ override fun spliterator(): @EnhancedNullability Spliterator<@FlexibleNullability A?>
  /* fake */ override fun stream(): @EnhancedNullability Stream<@EnhancedNullability A>
  @Deprecated(message = "This member is not fully supported by Kotlin compiler, so it may be absent or have different signature in next major version", replaceWith = ReplaceWith(expression = "", imports = []), level = DeprecationLevel.WARNING)
  /* fake */ override fun <T : @FlexibleNullability Any?> toArray(p0: @FlexibleNullability IntFunction<@FlexibleNullability Array<out @FlexibleNullability T?>?>?): @FlexibleNullability Array<out @FlexibleNullability T?>?
  /* fake */ override fun toString(): String
  @JvmStatic
  fun write$Self(self: B, output: CompositeEncoder, serialDesc: SerialDescriptor)
  @Deprecated(message = "This synthesized declaration should not be used directly", replaceWith = ReplaceWith(expression = "", imports = []), level = DeprecationLevel.HIDDEN)
  constructor(seen1: Int, serializationConstructorMarker: SerializationConstructorMarker?) 
}

`
Details: kotlinx.serialization compiler plugin internal error: unable to transform declaration, see cause
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializerClassLowering.lower(SerializationLoweringExtension.kt:184)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitClass(SerializationLoweringExtension.kt:46)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitClass(IrElementVisitorVoid.kt:111)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitClass(SerializationLoweringExtension.kt:40)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitClass(SerializationLoweringExtension.kt:40)
	at org.jetbrains.kotlin.ir.declarations.IrClass.accept(IrClass.kt:64)
	at org.jetbrains.kotlin.ir.declarations.IrFile.acceptChildren(IrFile.kt:36)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitElement(SerializationLoweringExtension.kt:42)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitPackageFragment(IrElementVisitorVoid.kt:190)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitPackageFragment(SerializationLoweringExtension.kt:40)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:200)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitFile(SerializationLoweringExtension.kt:40)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:198)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitFile(SerializationLoweringExtension.kt:40)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitFile(SerializationLoweringExtension.kt:40)
	at org.jetbrains.kotlin.ir.declarations.IrFile.accept(IrFile.kt:30)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptVoid(IrVisitors.kt:11)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt.runOnFileInOrder(SerializationLoweringExtension.kt:40)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtension.generate(SerializationLoweringExtension.kt:149)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr$lambda$1(JvmIrCodegenFactory.kt:186)
	at org.jetbrains.kotlin.psi2ir.Psi2IrTranslator.generateModuleFragment(Psi2IrTranslator.kt:104)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr(JvmIrCodegenFactory.kt:218)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr(JvmIrCodegenFactory.kt:55)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.convertToIr(KotlinToJVMBytecodeCompiler.kt:225)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:102)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:47)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:167)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:53)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:101)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:47)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:485)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:131)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.doCompile(IncrementalCompilerRunner.kt:424)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:360)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.tryCompileIncrementally(IncrementalCompilerRunner.kt:194)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:89)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:625)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1746)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializableIrGenerator$generateInternalConstructor$1.invoke(SerializableIrGenerator.kt:137)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializableIrGenerator$generateInternalConstructor$1.invoke(SerializableIrGenerator.kt:60)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.IrBuilderWithPluginContext.addFunctionBody(IrBuilderWithPluginContext.kt:49)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializableIrGenerator.generateInternalConstructor(SerializableIrGenerator.kt:60)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializableIrGenerator.generateSyntheticInternalConstructor(SerializableIrGenerator.kt:364)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializableIrGenerator.generate(SerializableIrGenerator.kt:356)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializableIrGenerator$Companion.generate(SerializableIrGenerator.kt:383)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializerClassLowering.lower(SerializationLoweringExtension.kt:102)
	... 57 more
```

**Comment by sandwwraith** [comment] 2023-01-30 11:02
Duplicate of #2157

**Closed by sandwwraith** 2023-01-30 11:02 UTC
