### ISSUE TITLE
Support sealed interface

### ISSUE THREAD

**Issue by MEJIOMAH17** [Kotlin/kotlinx.serialization#1861] opened 2022-02-09 19:17 UTC
**What is your use-case and why do you need this feature?**
Usage of sealed interface 
sealed interface IdHolder{
  val id:Long
}

class Entity:IdHolder{
   override val id:Long
}

class Request(val entity:IdHolder)

**Describe the solution you'd like**

Same with sealed class

**Comment by pdvrieze** [comment] 2022-02-18 14:16
This is a duplicate of #1576

**Comment by MEJIOMAH17** [comment] 2022-02-19 20:14
@pdvrieze, yes you are right. https://github.com/Kotlin/kotlinx.serialization/issues/1576 is closed now. If you reopen it, I will close this issue.

**Comment by sandwwraith** [comment] 2022-02-21 13:12
#1576 is closed because corresponding commit is added to Kotlin master and sealed interfaces would be supported from 1.6.20-M1 and further

**Closed by sandwwraith** 2022-02-21 13:12 UTC
Labels: feature

**Comment by MEJIOMAH17** [comment] 2022-02-21 16:35
@sandwwraith great!
