### ISSUE TITLE
Error deserialization value class in sealed class\interface

### ISSUE THREAD

**Issue by SchweinchenFuntik** [Kotlin/kotlinx.serialization#2479] opened 2023-10-16 08:19 UTC
I use value class inside sealed class (interface) , there can be several levels of sealed class (interface).

Serialization runs fine, but deserialization already generates a runtime error

**Main:**
```kotlin
import kotlinx.serialization.decodeFromString
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import net.mamoe.yamlkt.Yaml
import net.mamoe.yamlkt.YamlBuilder


private val json =  Json {
    prettyPrint = true
    encodeDefaults = false

}
private val yaml = Yaml {
    encodeDefaultValues = false
}


fun main() {
    test1()
    test2()
}

private fun test1() {
    val list: MutableList<Task> = ArrayList()

    list += Task.ProjectAction("foo")
    list += Task.Simple(action = Action.ComponentsLoad(listOf("feature1", "feature2")))

    val s1 = json.encodeToString(list)
    val s2 = yaml.encodeToString(list)
    println(s1)
    println("\n----------------------------------------\n")
    println(s2)

    // error
    json.decodeFromString<List<Task>>(s1)
//    yaml.decodeFromString<List<Task>>(s1)
}

@OptIn(Developing::class)
private fun test2() {
    val task1: Task = Task.ProjectAction("foo")
    val task2: Task = Task.Simple(action = Action.ComponentsLoad(listOf("feature1", "feature2")))

    val s1 = json.encodeToString(task1)
    val s2 = json.encodeToString(task2)

    println(s1)
    println("\n----------------------------------------\n")
    println(s2)

    // error
    json.decodeFromString<List<Task>>(s1)
    json.decodeFromString<List<Task>>(s2)
}
```

**Structure**:
```kotlin
@Serializable
sealed class Action {
    val pipeline: MutableList<PipelineOperation> = mutableListOf()

    @Serializable
    @SerialName("componentsLoad")
    data class ComponentsLoad(val features: List<String> = emptyList()) : Action()

    @Serializable
    @SerialName("import") 
    data class Import(
        val targetDataSource: String,
        val isReimport: Boolean = false,
        val fromFeatures: List<String> = emptyList() 
    ) : Action()
}

@Serializable
sealed interface Task {
    @JvmInline
    @Serializable
    value class Simple(val action: Action) : Task // wrapper

    @JvmInline
    @Serializable
    value class ProjectAction(val name: String) : Task // get action from Map by name
}
```

**Environment**
 - Kotlin version: 1.8.21
 - Library version: 1.5.1
 - Kotlin platforms: JVM
 - Gradle version:7.4.2

**Comment by sandwwraith** [comment] 2023-10-16 09:28
Duplicate of #2374

**Closed by sandwwraith** 2023-10-16 09:28 UTC
