### ISSUE TITLE
Primitives.kt RuntimeError: dereferencing a null pointer

### ISSUE THREAD

**Issue by VladislavSumin** [Kotlin/kotlinx.serialization#2583] opened 2024-02-29 20:23 UTC
The kotlin-serialization library crashes with a null pointer exception when initializing the Serializer in the code of a third-party library compiled with an older version of kotlin. When using such Serializers directly in the code, there is no crash.
<details>
  <summary>wasm stack trace</summary>

```
Primitives.kt:79 Uncaught (in promise) RuntimeError: dereferencing a null pointer
    at <vs-control.client:wasm>.kotlinx.serialization.internal.checkName (Primitives.kt:79:36)
    at <vs-control.client:wasm>.kotlinx.serialization.internal.PrimitiveDescriptorSafe (Primitives.kt:72:5)
    at <vs-control.client:wasm>.kotlinx.serialization.descriptors.PrimitiveSerialDescriptor (SerialDescriptors.kt:91:12)
    at <vs-control.client:wasm>.com.arkivanov.essenty.statekeeper.Serializer.<init> (SerializableContainer.kt:66:53)
    at <vs-control.client:wasm>.com.arkivanov.essenty.statekeeper.Serializer_getInstance (vs-control-client-wasm-wasm-js.wasm:0x2f6155)
    at <vs-control.client:wasm>.com.arkivanov.decompose.router.children.Companion.<init> (vs-control-client-wasm-wasm-js.wasm:0x2fccd2)
    at <vs-control.client:wasm>.com.arkivanov.decompose.router.children.Companion_getInstance (vs-control-client-wasm-wasm-js.wasm:0x2fcd08)
    at <vs-control.client:wasm>.com.arkivanov.decompose.router.children.childrenNavigator (vs-control-client-wasm-wasm-js.wasm:0x2fcab5)
    at <vs-control.client:wasm>.com.arkivanov.decompose.router.children.children (ChildrenFactory.kt:127:25)
    at <vs-control.client:wasm>.com.arkivanov.decompose.router.children.children$default (vs-control-client-wasm-wasm-js.wasm:0x2fc3ec)
```

</details>

**Environment**
 - Kotlin version: 2.0.0-Beta4
 - Library version: 1.6.2
 - Kotlin platforms: WASM
 - Gradle version: 8.6
 - Other relevant context: Decompose 3.0.0-alpha07

**Comment by sandwwraith** [comment] 2024-03-01 11:51
Do you have a project with a reproducer, by any chance? It's hard to tell what happened from the stacktrace alone.

**Comment by VladislavSumin** [comment] 2024-03-01 18:10
Yes, I have a project with 100 percent reproduction. You need to rollback to the specified commit and call `gradle :client:wasm:wasmJsBrowserDevelopmentRun`. It crashes immediately at the start, you don’t need to do anything additional. If you roll back one more commit earlier, kotlin-beta01 will be there and everything works.
Repo: https://github.com/VladislavSumin/vs-control
Revision: c2257bc76d9a8ad68f1460e361dadb511593b1fa

**Comment by ismai117** [comment] 2024-03-11 17:44
I'm receiving the same error

```
dereferencing a null pointer
RuntimeError: dereferencing a null pointer
    at <DroidJobsKMP:webApp-wasm>.kotlinx.serialization.internal.checkName (http://localhost:8080/webApp-wasm.wasm:wasm-function[57078]:0x89fe45)
    at <DroidJobsKMP:webApp-wasm>.kotlinx.serialization.internal.PrimitiveDescriptorSafe (http://localhost:8080/webApp-wasm.wasm:wasm-function[57077]:0x89fd91)
    at <DroidJobsKMP:webApp-wasm>.kotlinx.serialization.descriptors.PrimitiveSerialDescriptor (http://localhost:8080/webApp-wasm.wasm:wasm-function[56198]:0x894bb1)
    at <DroidJobsKMP:webApp-wasm>.kotlinx.datetime.serializers.LocalTimeIso8601Serializer.<init> (http://localhost:8080/webApp-wasm.wasm:wasm-function[59289]:0x8c77b7)
    at <DroidJobsKMP:webApp-wasm>.kotlinx.datetime.serializers.LocalTimeIso8601Serializer_getInstance (http://localhost:8080/webApp-wasm.wasm:wasm-function[59295]:0x8c786c)
    at <DroidJobsKMP:webApp-wasm>.kotlin.wasm.internal.initAssociatedObjects (http://localhost:8080/webApp-wasm.wasm:wasm-function[17120]:0x5056e5)
    at <DroidJobsKMP:webApp-wasm>.kotlin.wasm.internal.findAssociatedObject (http://localhost:8080/webApp-wasm.wasm:wasm-function[17119]:0x505632)
    at <DroidJobsKMP:webApp-wasm>.kotlinx.serialization.internal.constructSerializerForGivenTypeArgs (http://localhost:8080/webApp-wasm.wasm:wasm-function[57342]:0x8a471d)
    at <DroidJobsKMP:webApp-wasm>.kotlinx.serialization.internal.compiledSerializerImpl (http://localhost:8080/webApp-wasm.wasm:wasm-function[57339]:0x8a4697)
    at <DroidJobsKMP:webApp-wasm>.kotlinx.serialization.serializerOrNull (http://localhost:8080/webApp-wasm.wasm:wasm-function[56043]:0x89220c)
```

**Comment by Shanezor12** [comment] 2024-03-21 06:59
I'm also receiving a similar error with serialization and WASM when using Beta4

**Comment by sandwwraith** [comment] 2024-03-26 12:14
I was able to reproduce the error, but it seems it is connected to Kotlin/WASM itself. Has anyone reported it to the YouTrack?

**Comment by ismai117** [comment] 2024-03-27 06:37
It seems to be fixed with Kotlin version 2.0.0-Beta5, and I no longer receive the error. If you want to use 2.0.0-Beta5, compose compiler 1.5.11-kt-2.0.0-Beta5 works.

**Comment by VladislavSumin** [comment] 2024-03-31 18:37
@sandwwraith Yes I get the same error with the kotlin version Beta5

**Comment by sandwwraith** [comment] 2024-11-27 18:19
This should not happen in 2.0.20, because both `Duration` and `Uuid` present there. Please re-open if you still experience the issue.

**Closed by sandwwraith** 2024-11-27 18:19 UTC
Labels: bug
