### ISSUE TITLE
Kapt problems with generated code and models with generics

### ISSUE THREAD

**Issue by nico-gonzalez** [Kotlin/kotlinx.serialization#76] opened 2018-02-01 08:50 UTC
@sandwwraith As discussed in issue #72 I am having issues with the kotlinx serialization plugin that generates the serializers for models that make use of generics. This is the sample project I am working on that reproduces the problem: https://github.com/nico-gonzalez/K-Places/tree/kotlinx-serialization. The url points to `kotlinx-serialization` branch which is the one I am using to test this. My idea was to replace the usage of **Gson** with this by setting the kotlinx serialization dependency only on the data module as it was the case for **Gson** dependency

To reproduce this you just need to hit build and you will get the following sort of errors when `:data:kaptDebugKotlin`. Note that it seems that the plugin is set up and running and it is indeed generating the $serializer classes for the different models with **@Serializable** annotation. Let me know in case you need anything else from my side.

```
e: /Users/nico/Dev/git/edreams/workshops/K-Places/data/build/tmp/kapt3/stubs/debug/com/edreams/android/workshops/kotlin/data/venues/remote/response/Response.java:75: error: non-static type variable T cannot be referenced from a static context
    public static final class $serializer implements kotlinx.serialization.KSerializer<com.edreams.android.workshops.kotlin.data.venues.remote.response.Response<? extends T>> {
                                                                                                                                                                           ^
e: /Users/nico/Dev/git/edreams/workshops/K-Places/data/build/tmp/kapt3/stubs/debug/com/edreams/android/workshops/kotlin/data/venues/remote/response/Response.java:85: error: non-static type variable T cannot be referenced from a static context
        com.edreams.android.workshops.kotlin.data.venues.remote.response.Response<? extends T> old) {
                                                                                            ^
e: /Users/nico/Dev/git/edreams/workshops/K-Places/data/build/tmp/kapt3/stubs/debug/com/edreams/android/workshops/kotlin/data/venues/remote/response/Response.java:83: error: non-static type variable T cannot be referenced from a static context
        public com.edreams.android.workshops.kotlin.data.venues.remote.response.Response<T> update(@org.jetbrains.annotations.NotNull()
                                                                                         ^
e: /Users/nico/Dev/git/edreams/workshops/K-Places/data/build/tmp/kapt3/stubs/debug/com/edreams/android/workshops/kotlin/data/venues/remote/response/Response.java:98: error: non-static type variable T cannot be referenced from a static context
        com.edreams.android.workshops.kotlin.data.venues.remote.response.Response<? extends T> obj) {
                                                                                            ^
e: /Users/nico/Dev/git/edreams/workshops/K-Places/data/build/tmp/kapt3/stubs/debug/com/edreams/android/workshops/kotlin/data/venues/remote/response/Response.java:103: error: non-static type variable T cannot be referenced from a static context
        public com.edreams.android.workshops.kotlin.data.venues.remote.response.Response<T> load(@org.jetbrains.annotations.NotNull()
                                                                                         ^
e: /Users/nico/Dev/git/edreams/workshops/K-Places/data/build/tmp/kapt3/stubs/debug/com/edreams/android/workshops/kotlin/data/venues/remote/response/Response.java:109: error: cannot find symbol
        kotlinx.serialization.KSerializer<T0> typeSerial0) {
                                          ^
  symbol:   class T0
  location: class $serializer
e: /Users/nico/Dev/git/edreams/workshops/K-Places/data/build/tmp/kapt3/stubs/debug/com/edreams/android/workshops/kotlin/data/venues/remote/response/FourSquareResponse.java:75: error: non-static type variable T cannot be referenced from a static context
    public static final class $serializer implements kotlinx.serialization.KSerializer<com.edreams.android.workshops.kotlin.data.venues.remote.response.FourSquareResponse<? extends T>> {
                                                                                                                                                                                     ^
e: /Users/nico/Dev/git/edreams/workshops/K-Places/data/build/tmp/kapt3/stubs/debug/com/edreams/android/workshops/kotlin/data/venues/remote/response/FourSquareResponse.java:85: error: non-static type variable T cannot be referenced from a static context
        com.edreams.android.workshops.kotlin.data.venues.remote.response.FourSquareResponse<? extends T> old) {
                                                                                                      ^
e: /Users/nico/Dev/git/edreams/workshops/K-Places/data/build/tmp/kapt3/stubs/debug/com/edreams/android/workshops/kotlin/data/venues/remote/response/FourSquareResponse.java:83: error: non-static type variable T cannot be referenced from a static context
        public com.edreams.android.workshops.kotlin.data.venues.remote.response.FourSquareResponse<T> update(@org.jetbrains.annotations.NotNull()
                                                                                                   ^
e: /Users/nico/Dev/git/edreams/workshops/K-Places/data/build/tmp/kapt3/stubs/debug/com/edreams/android/workshops/kotlin/data/venues/remote/response/FourSquareResponse.java:98: error: non-static type variable T cannot be referenced from a static context
        com.edreams.android.workshops.kotlin.data.venues.remote.response.FourSquareResponse<? extends T> obj) {
                                                                                                      ^
e: /Users/nico/Dev/git/edreams/workshops/K-Places/data/build/tmp/kapt3/stubs/debug/com/edreams/android/workshops/kotlin/data/venues/remote/response/FourSquareResponse.java:103: error: non-static type variable T cannot be referenced from a static context
        public com.edreams.android.workshops.kotlin.data.venues.remote.response.FourSquareResponse<T> load(@org.jetbrains.annotations.NotNull()
                                                                                                   ^
e: /Users/nico/Dev/git/edreams/workshops/K-Places/data/build/tmp/kapt3/stubs/debug/com/edreams/android/workshops/kotlin/data/venues/remote/response/FourSquareResponse.java:109: error: cannot find symbol
        kotlinx.serialization.KSerializer<T0> typeSerial0) {
                                          ^
  symbol:   class T0
  location: class $serializer
e: /Users/nico/Dev/git/edreams/workshops/K-Places/data/build/tmp/kapt3/stubs/debug/com/edreams/android/workshops/kotlin/data/venues/remote/response/GroupsResponse.java:75: error: non-static type variable T cannot be referenced from a static context
    public static final class $serializer implements kotlinx.serialization.KSerializer<com.edreams.android.workshops.kotlin.data.venues.remote.response.GroupsResponse<? extends T>> {
                                                                                                                                                                                 ^
e: /Users/nico/Dev/git/edreams/workshops/K-Places/data/build/tmp/kapt3/stubs/debug/com/edreams/android/workshops/kotlin/data/venues/remote/response/GroupsResponse.java:85: error: non-static type variable T cannot be referenced from a static context
        com.edreams.android.workshops.kotlin.data.venues.remote.response.GroupsResponse<? extends T> old) {
                                                                                                  ^
e: /Users/nico/Dev/git/edreams/workshops/K-Places/data/build/tmp/kapt3/stubs/debug/com/edreams/android/workshops/kotlin/data/venues/remote/response/GroupsResponse.java:83: error: non-static type variable T cannot be referenced from a static context
        public com.edreams.android.workshops.kotlin.data.venues.remote.response.GroupsResponse<T> update(@org.jetbrains.annotations.NotNull()
                                                                                               ^
e: /Users/nico/Dev/git/edreams/workshops/K-Places/data/build/tmp/kapt3/stubs/debug/com/edreams/android/workshops/kotlin/data/venues/remote/response/GroupsResponse.java:98: error: non-static type variable T cannot be referenced from a static context
        com.edreams.android.workshops.kotlin.data.venues.remote.response.GroupsResponse<? extends T> obj) {
                                                                                                  ^
e: /Users/nico/Dev/git/edreams/workshops/K-Places/data/build/tmp/kapt3/stubs/debug/com/edreams/android/workshops/kotlin/data/venues/remote/response/GroupsResponse.java:103: error: non-static type variable T cannot be referenced from a static context
        public com.edreams.android.workshops.kotlin.data.venues.remote.response.GroupsResponse<T> load(@org.jetbrains.annotations.NotNull()
                                                                                               ^
e: /Users/nico/Dev/git/edreams/workshops/K-Places/data/build/tmp/kapt3/stubs/debug/com/edreams/android/workshops/kotlin/data/venues/remote/response/GroupsResponse.java:109: error: cannot find symbol
        kotlinx.serialization.KSerializer<T0> typeSerial0) {
                                          ^
  symbol:   class T0
  location: class $serializer

:data:kaptDebugKotlin FAILED
```

**Comment by sandwwraith** [comment] 2018-02-02 12:26
Okay, now I see. It's either serialization plugin produced not so correct descriptors or kapt can't transform such code

**Comment by nico-gonzalez** [comment] 2018-02-13 20:50
@sandwwraith any update on this? were you able to investigate this issue further?

**Comment by sandwwraith** [comment] 2018-02-14 11:28
@nico-gonzalez Yes. Unfortunately, there are some problems with internal plugin api, which doesn't allow to correctly specify type parameters in synthetic classes (such as serializers). This means this issue can't be resolved without changes in upstream compiler and next Kotlin update

**Comment by igordmn** [comment] 2018-03-26 21:32
I have the same problem.

Doesn't work when the new kapt plugin is used:
    kotlin("jvm") version "1.2.31"
    kotlin("kapt") version "1.2.31"

Works with internal kapt plugin and downgraded kotlin:
    kotlin("jvm") version "1.2.20"

**Comment by sandwwraith** [comment] 2018-06-19 11:20
Starting from 1.2.50, this should not be a problem

**Closed** 2018-06-19 11:20 UTC
Labels: bug

**Comment by nico-gonzalez** [comment] 2018-06-19 15:31
@sandwwraith seems to be working now. I will test this further. Many thanks!!

**Comment by alishir** [comment] 2018-07-12 07:51
@sandwwraith I'm using kotlin `1.2.51` and kapt, but unfortunately I couldn't build the project due to following error.

```
/home/test/android/app/build/tmp/kapt3/stubs/debug/io/github/alishir/test/profile/TestManager.java:7: error: type DeviceManager.DeviceManagerCallback does not take parameters
    private final pkg.test.DeviceManager.DeviceManagerCallback<pkg.test.DeviceManagerCallbacks> mCallback = null;
                                                                             ^
```

**Comment by sandwwraith** [comment] 2018-07-12 09:13
@alishir I don't see how that's related to kotlinx.serialization... is your `DeviceManagerCallback` serializable?

**Comment by alishir** [comment] 2018-07-12 09:23
@sandwwraith oh sorry I didn't check the exact error, you are right it is unrelated. Do you know where should I post issues about kapt?

**Comment by alishir** [comment] 2018-07-12 09:51
@sandwwraith thanks a lot.

**Comment by SpaceBison** [comment] 2019-04-26 06:37
It seems that this problem still persists.

Sample code to reproduce:
```kotlin
@Serializable
data class GenericDataClass<T>(val genericProperty: T)
```

When used with kapt and any annotation process, it causes kapt to fail with the following errors:
```
> Task :kaptKotlin FAILED
e: /foo/kotlinx-serialization-test/build/tmp/kapt3/stubs/main/GenericDataClass.java:51: error: non-static type variable T cannot be referenced from a static context
    GenericDataClass<T> self, @org.jetbrains.annotations.NotNull()
                     ^
e: /foo/kotlinx-serialization-test/build/tmp/kapt3/stubs/main/GenericDataClass.java:54: error: non-static type variable T cannot be referenced from a static context
    kotlinx.serialization.KSerializer<T> typeSerial1) {
                                      ^
```
Here's the generated code in question:
```java
public static final void write$Self(@org.jetbrains.annotations.NotNull()
GenericDataClass<T> self, @org.jetbrains.annotations.NotNull()
kotlinx.serialization.CompositeEncoder output, @org.jetbrains.annotations.NotNull()
kotlinx.serialization.SerialDescriptor serialDesc, @org.jetbrains.annotations.NotNull()
kotlinx.serialization.KSerializer<T> typeSerial1) {
}
```

**Comment by sandwwraith** [comment] 2019-04-26 09:57
@SpaceBison It's #429 .
