### ISSUE TITLE
KSerializer instances that don't have a constructor with no arguments crash the build on Apple

### ISSUE THREAD

**Issue by dkhalanskyjb** [Kotlin/kotlinx.serialization#1242] opened 2020-12-08 16:16 UTC
**Describe the bug**

A user of datetime experienced a build crash: https://github.com/Kotlin/kotlinx-datetime/issues/63 It turned out that the cause was an incorrectly-written serializer.

**To Reproduce**

Clone https://github.com/dkhalanskyjb/serializer-constructor-parameter (a small reproducing project), do `./gradlew build`. Observe something like
```
e: org.jetbrains.kotlin.konan.KonanExternalToolFailure: The /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ command returned non-zero exit code: 1.
output:
error: Invalid record (Producer: 'LLVM8.0.0svn' Reader: 'LLVM APPLE_1_1103.0.32.62_0')
1 error generated.
        at org.jetbrains.kotlin.konan.exec.Command.handleExitCode(ExecuteCommand.kt:112)
        at org.jetbrains.kotlin.konan.exec.Command.execute(ExecuteCommand.kt:73)
        at org.jetbrains.kotlin.backend.konan.BitcodeCompiler.runTool(BitcodeCompiler.kt:31)
        at org.jetbrains.kotlin.backend.konan.BitcodeCompiler.targetTool(BitcodeCompiler.kt:42)
        at org.jetbrains.kotlin.backend.konan.BitcodeCompiler.clang(BitcodeCompiler.kt:83)
...
```

**Expected behavior**

I expect the compiler not to crash and instead output something actionable.

**Environment**
 - Kotlin version: 1.4.20
 - Library version: 1.0.1
 - Kotlin platforms: Native, at least MacOS. JVM and JS seem to work fine.

**Comment by sandwwraith** [comment] 2023-06-20 14:50
@dkhalanskyjb Am I right that this is not a bug, but a result of missing compiler diagnostic?
There's https://youtrack.jetbrains.com/issue/KT-58036/Provide-diagnostic-in-compiler-plugin-when-provided-serializer-cant-be-instantiated ticket for that, so I'll close this one.

**Closed by sandwwraith** 2023-06-20 14:50 UTC
Labels: bug, native
