### ISSUE TITLE
Exclude property from serialization/deserialization specifically  

### ISSUE THREAD

**Issue by AChep** [Kotlin/kotlinx.serialization#1796] opened 2021-12-15 18:51 UTC
**What is your use-case and why do you need this feature?**
```kotlin
data class Foo(
  @Deprecated
  private val a: Int? = null,
  private val b: Int = a ?: 0,
)
```
I want to read the `a` property, but I don't want to write it back to the json file. _It would also be nice to forcefully serialize `b` as well, even if it matches the default value, but that's a different question._   

**Describe the solution you'd like**
```kotlin
data class Foo(
  @Deprecated
  @Transient(deserialize = true)
  private val a: Int? = null,
  private val b: Int = a ?: 0,
)
```

**Comment by sandwwraith** [comment] 2021-12-27 15:24
Duplicate of #692

>  It would also be nice to forcefully serialize b as well, even if it matches the default value, but that's a different question.

Use `@EncodeDefault` annotation

**Closed by sandwwraith** 2021-12-27 15:24 UTC
Labels: feature

**Comment by AChep** [comment] 2021-12-27 15:53
@sandwwraith hey, that was a side question, please reopen the issue. :stuck_out_tongue:

**Comment by sandwwraith** [comment] 2021-12-27 16:05
@AChep Yeah, but your main question is a duplicate — see the linked issue
