### ISSUE TITLE
Support I/O stream

### ISSUE THREAD

**Issue by chenfei0928** [Kotlin/kotlinx.serialization#204] opened 2018-08-30 05:02 UTC
If I deserialize  a json from file system, deserialize method require me full read the file to a string.
Can it support read and write json content from I/O stream, like Gson done?

**Comment by sandwwraith** [comment] 2018-08-30 10:06
We are planning migration to kotlin multiplatform IO library – https://github.com/Kotlin/kotlinx-io . JSON parser would support both strings and kotlinx.io inputs.

**Comment by gajicm93** [comment] 2020-04-09 19:21
This is quite a bummer because I know for a fact that Android can crash when a very large JSON payload is converted to a String at once.

When can we expect a streaming parse? Thanks.

**Comment by jcraane** [comment] 2020-07-09 06:16
We indeed face this issue when per persist large json (the apps data) which sometimes triggers OutOfMemory.

**Comment by sdeleuze** [comment] 2020-10-06 14:08
We are interested by that one for Spring Framework support, beware that for Spring MVC we typically deal with `InputStream` / `OutputStream` while on Spring WebFlux side we typically deal with `java.nio.ByteBuffer`, potentially in combination with the upcoming JSON streaming support (#1073).

**Comment by epicstar** [comment] 2020-10-30 06:45
> This is quite a bummer because I know for a fact that Android can crash when a very large JSON payload is converted to a String at once.

Yes, this should be considered a stopper for all Android applications.

**Comment by mobiletoly** [comment] 2020-11-13 05:22
Any news or roadmap?

**Comment by sandwwraith** [comment] 2020-11-20 19:49
It's planned for 1.1 or 1.2

**Comment by ln-12** [comment] 2021-02-09 15:33
Seems like the feature didn't make into 1.1.0-RC. Currently, it's the only reason why I would not feel confident shipping it in a production app.

**Comment by cherryleafroad** [comment] 2021-04-05 20:06
Really sad, I was looking forward to this being supported

**Comment by sdeleuze** [comment] 2021-04-09 08:51
Could you please add support for that in 1.2 in order to allow Spring to use it in Spring Boot 2.5 ?

**Comment by slavonnet** [comment] 2021-05-12 13:27
+100500 votes! How read big

**Comment by chris-hatton** [comment] 2021-06-26 09:29
I'm developing an application with `kotlinx.serialization` and came to a point where I really want to implement a `Flow<T>` of objects from Server to Client.  It seems unfeasible to do this at the moment due to lack of stream processing support with `kotlinx.serialization`.  This is the biggest weakness I can see with this otherwise great library...

**Comment by chris-hatton** [comment] 2021-06-26 11:10
If `kotlinx.io` has been put on hold; could maintaining developers of `kotlinx.serialization` consider a separate effort to expose a streaming API?  I have seen suggestions that parsing is modelled around a stream internally, but for some reason this isn't exposed.

**Comment by sandwwraith** [comment] 2021-06-28 11:41
> I have seen suggestions that parsing is modelled around a stream internally 

that (wasn't) true

We currently have progress on working implementation over Java's InputStream/OutputStream (#1569 ) You can take a look and tell if that fits your needs.

**Comment by qwwdfsad** [comment] 2021-09-10 10:56
Fixed in 1.3.0-RC

**Closed by qwwdfsad** 2021-09-10 10:56 UTC
Labels: question, design

**Comment by slavonnet** [comment] 2021-09-10 17:05
random EOF exceptions  on heavy loads.

**Comment by sandwwraith** [comment] 2021-09-10 17:11
@slavonnet Can you please create a separate issue with a reproducer or at least a description of conditions under which exception occurs?

**Comment by martinbonnin** [comment] 2021-10-01 17:42
Is there a separate issue for multiplatform streaming ?

**Comment by sandwwraith** [comment] 2021-10-04 09:29
@martinbonnin I've cerated one for you: https://github.com/Kotlin/kotlinx.serialization/issues/1714
