### ISSUE TITLE
Duplicate classes build error after updating to version 1.0-M1-1.4.0-rc

### ISSUE THREAD

**Issue by caiodev** [Kotlin/kotlinx.serialization#1022] opened 2020-08-29 08:03 UTC
**Describe the bug**
After updating the kotlin.serialization version to 1.0-M1-1.4.0-rc i started to get build errors about duplicate classes on jetified-kotlinx-serialization-core-jvm-1.0.0-RC.jar and jetified-kotlinx-serialization-runtime-jvm-1.0-M1-1.4.0-rc.jar

**To Reproduce**
I just updated the version to the aforementioned one. This is the output when i try to build my project(It's too long so i created a Gist): https://gist.github.com/caiodev/92375d8b4572380ead323e99071b0d5f

**Expected behavior**
It should just be updated and keep working. I know this is a RC version but i really can't build my project right now so any help will be really appreciated. Thank you folks.

**Environment**
 - Kotlin version: [1.4]
 - Library version: [1.0-M1-1.4.0-rc]
 - Kotlin platforms: [JVM/Android]
 - Gradle version: [Wrapper: 6.6 / Plugin: 4.0.1]
 - IDE version: [Android Studio 4.0]
 - Other relevant context [OS version: Ubuntu MATE 20.04, Kernel Version: 5.8.5, JRE version: 1.8 ]

**Comment by sandwwraith** [comment] 2020-08-31 13:30
Duplicate of #996 ? (pls reopen if I'm wrong)

**Closed by sandwwraith** 2020-08-31 13:30 UTC

**Comment by caiodev** [comment] 2020-08-31 13:41
It is a duplicate. Thanks for pointing it
