### ISSUE TITLE
Serialization of circular structures

### ISSUE THREAD

**Issue by fab1an** [Kotlin/kotlinx.serialization#15] opened 2017-10-02 07:50 UTC
I need deserialization of circular references (a parent object holding children, which in turn have a reference to the parent). I wrote an annotation-processor for json-serialization and described how I did that here: 

https://medium.com/@spitzwegerich/generated-json-serialisation-for-kotlin-4470dabe40b8

**Comment by sandwwraith** [comment] 2017-10-04 09:32
Thank for the notice, tree-like structures are important part of DTOs, and we plan to add support for them in future.

Can you provide the link to your implementation? Can't find it in medium post.

**Comment by fab1an** [comment] 2017-10-04 10:58
Here's an example:
```kotlin
@GsonSerializer
class Root(var leaf: Leaf? = null)

@GsonSerializer
data class Leaf(@ParentRef val root: Root, val number: Int)
```

**Generated Serializers**
* The `JsonContext` is simply an enum that is passed around to be able to customize serialization for some types.

```kotlin

/** write root */
fun JsonWriter.value(obj: Root?, context: JsonContext? = null) {
    if (obj == null) {
        nullValue()
        return
    }
    beginObject()
    name("leaf").value(obj.leaf, context)
    endObject()
}


/** write leaf **/
fun JsonWriter.value(obj: Leaf?, context: JsonContext? = null) {
    if (obj == null) {
        nullValue()
        return
    }
    beginObject()
    name("number").value(obj.number)
    endObject()
}
```

**Generated Deserializer for `Root`**
* `unknownFieldFn` is a callback I need in very special cases to decide whether to throw or work around a problem
* circular refs work only if the field in the parent is nullable or a collection, so it can be set after instantiation.

```kotlin

fun JsonReader.nextRoot(unknownFieldFn: JsonReader.(String) -> Unit): Root {

    /* leaf is a function here, since it has a @ParentRef in it's constructor */
    var leaf: ((Root) -> Leaf)? = null
    var leafFound = false

    beginObject()
    while (hasNext()) {
        nextName().toLowerCase().let {
            when (it) {
                "leaf" ->  {
                    leafFound = true
                    leaf = nextOrNull(JsonReader::nextLeaf)
                }
                else -> unknownFieldFn(it)
            }
        }
    }
    endObject()
 
    check(leafFound) {"error parsing Root, nullable field not found: leaf: Leaf"}

    /* create root */
    val obj = Root(
        leaf = null
    )

    /* set leaf */ 
    obj.leaf = leaf?.invoke(obj)
    return obj
}
```

**Generated Deserializer for `Leaf`**
* like stated above, `nextLeaf` returns a function, because it needs a `@ParentRef`
```kotlin
fun JsonReader.nextLeaf(unknownFieldFn: JsonReader.(String) -> Unit): (root: Root) -> Leaf {
    var number: Int? = null

    beginObject()
    while (hasNext()) {
        nextName().toLowerCase().let {
            when (it) {
                "number" -> number = nextInt()
                else -> unknownFieldFn(it)
            }
        }
    }
    endObject()

    return { root->
        Leaf(
            root = root,
            number = checkNotNull(number) {"error parsing Leaf, field not found: number: Int"}
        )
    }
}
```

**Comment by qwwdfsad** [comment] 2020-07-10 09:29
`kotlinx.serialization` is aimed to provide (de)serialization of _the plain data_ out of the box.
Ability to serialize an arbitrary object graph (in the right order, etc.) is not the goal, so it's unlikely to be implemented on our side. In the end, the vast majority of use cases is a serialization of plain data. Adding support for cyclic graphs requires a tremendous effort (for the sake of 0.01% of use-cases) and we already have Java Serialization which genuinely regrets the decision of supporting it.

Closing as won't fix

**Closed by qwwdfsad** 2020-07-10 09:29 UTC
Labels: feature

**Comment by ylemoigne** [comment] 2020-07-25 12:01
It seems that the title of the issue is misleading. The request isn't about any arbitrary graph, but about tree-like structure.
Yes, it involve cycle in object graph, but in a very narrow use case : Parent-Childs relationship. It's more about something like Jackson's @JsonManagedReference, @JsonBackReference.

I perfectly understand that `arbitrary object graph` is a non goal. But I hope to see the support for bidirectional relationship one day.

As it seems it was a reasonnable goal a few years ago : https://github.com/Kotlin/kotlinx.serialization/issues/15#issuecomment-334101208 ; I wonder if now I can open an issue requesting support for this specific case or kotlinx.serialization's team consider now this is also as a non goal ?

**Comment by fab1an** [comment] 2020-07-25 13:27
I have actually implemented serialization of parent-leaf trees in a closed-source library.
It can't do generic graphs, just parent-leaf trees.

The assumptions are:
* The child has a constructor which takes an instance of the parent, which is annotated with `@ParentRef`.
* The parent has the child either in a nullable field or in a collection.
* During deserialization the parent is constructed first.
* Then the child is constructed and passed a reference to the parent
* At last the child is set at the nullable field in the parent or added to the collection.




https://medium.com/@fabianzeindl/generated-json-serialisation-for-kotlin-4470dabe40b8

**Comment by pdvrieze** [comment] 2020-07-25 17:20
@fab1an There is one category of "Circular" structures that is more or less supportable. That is the category like parent/child where there is a clear "master" and the other property is ignored. The most straightforward option to do this is to have a model that is used for serialization/deserialization that is then able to be used to construct the actual value types (this is the easiest way although it introduces extra classes). Alternatively it is possible to use custom deserializers that ensure that the properties get the right value (in some cases, like with parent/child, this is not needed if the parent constructor causes the parent on all assigned children to be set automatically).

Note that you can always use an `@SerializeWith` annotation to generate some sort of reference instead of actually writing the child. Btw. your assumption that the parent is created first is incompatible with the way the serialization framework works. It creates/deserializes children first. More significantly, the deserialization of children has no access to the parent that is being constructed (otherwise you could invert this in a custom serializer).

To support references in a general way is quite complex already. It involves keeping track of all written objects, giving them id attributes (in case of XML, something else for other formats), and then writing a reference to that id when you see the same object again.

The really hard part comes with recursive data structures. In that case you need to make sure to do this recording ahead of actually looking at the children.

**Comment by fab1an** [comment] 2020-07-25 17:23
No, my assumptions are about my own library: I don't use kotlinx.serialization, I have written my own compile-time annotation-processor which generates de/ser code.
It was many advantages over kotlinx.serialization, in my opinion, you can read the article.

**Comment by sandwwraith** [comment] 2020-07-28 12:36
@ylemoigne my comment in #15 was about the current JSON tree structure (`JsonElement`, etc). It did not imply parent referencing in a tree in any way. Sorry for misleading.

**Comment by ylemoigne** [comment] 2020-07-29 05:58
@sandwwraith Ok. Thanks for the precision.

I think that with it, you answered my question, not the answer I was hoping for but I understand the position, bidirectionnal relationship won't be supported.
