### ISSUE TITLE
getting java.lang.String cannot be cast to java.lang.Void error

### ISSUE THREAD

**Issue by ire4ever1190** [Kotlin/kotlinx.serialization#610] opened 2019-11-23 12:16 UTC
I am getting this error when trying to parse my json
```
java.lang.String cannot be cast to java.lang.Void
```
The stacktrace says that the error is coming from the "Movie " class

The classes that I am using are as follows
```
@Model
@Serializable
data class MovieList(val watchers: Int, val movie: Movie)

@Serializable
data class Movie(val title: String, val year: Int, val ids: MovieIds)

@Serializable
data class MovieIds(val trakt: Int, val slug: String, val imdb: String, val tmdb: Int)
```

and the json data looks like this
```
[
  {
    "watchers": 21,
    "movie": {
      "title": "TRON: Legacy",
      "year": 2010,
      "ids": {
        "trakt": 1,
        "slug": "tron-legacy-2010",
        "imdb": "tt1104001",
        "tmdb": 20526
      }
    }
  },
  {
    "watchers": 17,
    "movie": {
      "title": "The Dark Knight",
      "year": 2008,
      "ids": {
        "trakt": 4,
        "slug": "the-dark-knight-2008",
        "imdb": "tt0468569",
        "tmdb": 155
      }
    }
  }
]
```

 - Kotlin version: 1.3.60-eap-25
 - Library version: 0.14.0
 - Kotlin platforms: android
 - Gradle version: 5.6.1
 - IDE version Android Studio 4.0
 - Other relevant context: using openjdk 8 on linux

**Comment by ire4ever1190** [comment] 2019-11-24 08:22
It passes in my unit tests which makes me believe it is an android problem

**Comment by sandwwraith** [comment] 2019-11-25 13:03
Can you post the stacktrace? 

Btw, Kotlin `1.3.60` is released already, so no need to use eap.

**Comment by ire4ever1190** [comment] 2019-11-26 08:11
```
2019-11-26 19:10:07.718 1209-1209/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: me.jakeleahy.watchcorn, PID: 1209
    java.lang.ClassCastException: kotlinx.serialization.json.JsonLiteral cannot be cast to java.lang.Void
        at me.jakeleahy.watchcorn.MovieList$$serializer.deserialize(TraktDataClassses.kt:8)
        at me.jakeleahy.watchcorn.MovieList$$serializer.deserialize(TraktDataClassses.kt)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:34)
        at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:33)
        at kotlinx.serialization.ElementValueDecoder.decodeSerializableElement(ElementWise.kt:131)
        at kotlinx.serialization.internal.ListLikeSerializer.readElement(CollectionSerializers.kt:89)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:58)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.patch(CollectionSerializers.kt:39)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:49)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:34)
        at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:33)
        at kotlinx.serialization.CoreKt.decode(Core.kt:80)
        at kotlinx.serialization.json.Json.parse(Json.kt:126)
        at me.jakeleahy.watchcorn.MainActivityKt$ListMovies$1$1$1$1$1$2$1.invoke(MainActivity.kt:52)
        at me.jakeleahy.watchcorn.MainActivityKt$ListMovies$1$1$1$1$1$2$1.invoke(MainActivity.kt)
        at com.github.kittinunf.fuel.core.DeserializableKt$response$1.invoke(Deserializable.kt:105)
        at com.github.kittinunf.fuel.core.DeserializableKt$response$1.invoke(Deserializable.kt)
        at com.github.kittinunf.fuel.core.DeserializableKt$response$asyncRequest$1$1.invoke(Deserializable.kt:192)
        at com.github.kittinunf.fuel.core.DeserializableKt$response$asyncRequest$1$1.invoke(Deserializable.kt)
        at com.github.kittinunf.fuel.core.RequestExecutionOptionsKt$sam$java_lang_Runnable$0.run(RequestExecutionOptions.kt)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by pdvrieze** [comment] 2019-11-26 22:22
@ire4ever1190 It seems that the class definitions you posed are incomplete/incorrect. Somehow the polymorphic serializer is used for `MovieList` but this type has no polymorphic members (it is not even a list/collection - it appears to map to a single `MovieListElement`).

**Comment by ire4ever1190** [comment] 2019-11-27 01:09
Sorry about that. I changed my classes during testing and forgot to revert back.
This should be the correct stacktrace
```
2019-11-27 12:07:38.278 993-1009/? I/System.out: [{"watchers":68,"movie":{"title":"Once Upon a Time... in Hollywood","year":2019,"ids":{"trakt":313464,"slug":"once-upon-a-time-in-hollywood-2019","imdb":"tt7131622","tmdb":466272}}},{"watchers":51,"movie":{"title":"Hustlers","year":2019,"ids":{"trakt":392042,"slug":"hustlers-2019","imdb":"tt5503686","tmdb":540901}}},{"watchers":43,"movie":{"title":"Gemini Man","year":2019,"ids":{"trakt":299929,"slug":"gemini-man-2019","imdb":"tt1025100","tmdb":453405}}},{"watchers":39,"movie":{"title":"It Chapter Two","year":2019,"ids":{"trakt":322000,"slug":"it-chapter-two-2019","imdb":"tt7349950","tmdb":474350}}},{"watchers":38,"movie":{"title":"Rambo: Last Blood","year":2019,"ids":{"trakt":371013,"slug":"rambo-last-blood-2019","imdb":"tt1206885","tmdb":522938}}},{"watchers":36,"movie":{"title":"Joker","year":2019,"ids":{"trakt":322988,"slug":"joker-2019","imdb":"tt7286456","tmdb":475557}}},{"watchers":32,"movie":{"title":"Angel Has Fallen","year":2019,"ids":{"trakt":268664,"slug":"angel-has-fallen-2019","imdb":"tt6189022","tmdb":423204}}},{"watchers":23,"movie":{"title":"Ready or Not","year":2019,"ids":{"trakt":417095,"slug":"ready-or-not-2019","imdb":"tt7798634","tmdb":567609}}},{"watchers":19,"movie":{"title":"Downton Abbey","year":2019,"ids":{"trakt":387482,"slug":"downton-abbey-2019","imdb":"tt6398184","tmdb":535544}}},{"watchers":18,"movie":{"title":"Avengers: Endgame","year":2019,"ids":{"trakt":191798,"slug":"avengers-endgame-2019","imdb":"tt4154796","tmdb":299534}}}]
2019-11-27 12:07:38.284 993-1009/? I/System.out: java.lang.String cannot be cast to java.lang.Void
2019-11-27 12:07:38.284 993-1009/? I/System.out: 	com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:86)
2019-11-27 12:07:38.284 993-1009/? I/System.out: 	com.github.kittinunf.fuel.core.FuelError$Companion.wrap$default(FuelError.kt:83)
2019-11-27 12:07:38.284 993-1009/? I/System.out: 	com.github.kittinunf.fuel.core.requests.RequestTaskCallbacks.call(RequestTaskCallbacks.kt:30)
2019-11-27 12:07:38.284 993-1009/? I/System.out: Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Void
2019-11-27 12:07:38.284 993-1009/? I/System.out: 	me.jakeleahy.watchcorn.Movie$$serializer.deserialize(TraktDataClassses.kt:9)
2019-11-27 12:07:38.284 993-1009/? I/System.out: 	me.jakeleahy.watchcorn.Movie$$serializer.deserialize(TraktDataClassses.kt)
2019-11-27 12:07:38.284 993-1009/? I/System.out: 	kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:34)
2019-11-27 12:07:38.284 993-1009/? I/System.out: 	kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:33)
2019-11-27 12:07:38.284 993-1009/? I/System.out: 	kotlinx.serialization.ElementValueDecoder.decodeSerializableElement(ElementWise.kt:131)
2019-11-27 12:07:38.284 993-1009/? I/System.out: 	me.jakeleahy.watchcorn.MovieList$$serializer.deserialize(TraktDataClassses.kt:5)
2019-11-27 12:07:38.284 993-1009/? I/System.out: 	me.jakeleahy.watchcorn.MovieList$$serializer.deserialize(TraktDataClassses.kt)
2019-11-27 12:07:38.284 993-1009/? I/System.out: 	kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:34)
2019-11-27 12:07:38.284 993-1009/? I/System.out: 	kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:33)
2019-11-27 12:07:38.285 993-1009/? I/System.out: 	kotlinx.serialization.ElementValueDecoder.decodeSerializableElement(ElementWise.kt:131)
2019-11-27 12:07:38.285 993-1009/? I/System.out: 	kotlinx.serialization.internal.ListLikeSerializer.readElement(CollectionSerializers.kt:89)
2019-11-27 12:07:38.285 993-1009/? I/System.out: 	kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:58)
2019-11-27 12:07:38.285 993-1009/? I/System.out: 	kotlinx.serialization.internal.AbstractCollectionSerializer.patch(CollectionSerializers.kt:39)
2019-11-27 12:07:38.285 993-1009/? I/System.out: 	kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:49)
2019-11-27 12:07:38.285 993-1009/? I/System.out: 	kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:34)
2019-11-27 12:07:38.285 993-1009/? I/System.out: 	kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:33)
2019-11-27 12:07:38.285 993-1009/? I/System.out: 	kotlinx.serialization.CoreKt.decode(Core.kt:80)
2019-11-27 12:07:38.285 993-1009/? I/System.out: 	kotlinx.serialization.json.Json.parse(Json.kt:126)
2019-11-27 12:07:38.285 993-1009/? I/System.out: 	me.jakeleahy.watchcorn.MainActivity$onCreate$1$1$3.invoke(MainActivity.kt:34)
2019-11-27 12:07:38.285 993-1009/? I/System.out: 	me.jakeleahy.watchcorn.MainActivity$onCreate$1$1$3.invoke(MainActivity.kt)
2019-11-27 12:07:38.285 993-1009/? I/System.out: 	com.github.kittinunf.fuel.core.DeserializableKt$response$1.invoke(Deserializable.kt:105)
2019-11-27 12:07:38.285 993-1009/? I/System.out: 	com.github.kittinunf.fuel.core.DeserializableKt$response$1.invoke(Deserializable.kt)
2019-11-27 12:07:38.285 993-1009/? I/System.out: 	com.github.kittinunf.fuel.core.DeserializableKt$response$asyncRequest$1$1.invoke(Deserializable.kt:192)
2019-11-27 12:07:38.285 993-1009/? I/System.out: 	com.github.kittinunf.fuel.core.DeserializableKt$response$asyncRequest$1$1.invoke(Deserializable.kt)
2019-11-27 12:07:38.285 993-1009/? I/System.out: 	com.github.kittinunf.fuel.core.RequestExecutionOptionsKt$sam$java_lang_Runnable$0.run(RequestExecutionOptions.kt)
2019-11-27 12:07:38.285 993-1009/? I/System.out: 	com.github.kittinunf.fuel.core.DefaultEnvironment$callbackExecutor$1.execute(Environment.kt:16)
2019-11-27 12:07:38.285 993-1009/? I/System.out: 	com.github.kittinunf.fuel.core.RequestExecutionOptions.callback(RequestExecutionOptions.kt:43)
2019-11-27 12:07:38.285 993-1009/? I/System.out: 	com.github.kittinunf.fuel.core.DeserializableKt$response$asyncRequest$1.invoke(Deserializable.kt:190)
2019-11-27 12:07:38.285 993-1009/? I/System.out: 	com.github.kittinunf.fuel.core.DeserializableKt$response$asyncRequest$1.invoke(Deserializable.kt)
2019-11-27 12:07:38.285 993-1009/? I/System.out: 	com.github.kittinunf.fuel.core.requests.RequestTaskCallbacks.call(RequestTaskCallbacks.kt:29)
2019-11-27 12:07:38.285 993-1009/? I/System.out: 	com.github.kittinunf.fuel.core.requests.RequestTaskCallbacks.call(RequestTaskCallbacks.kt:20)
2019-11-27 12:07:38.285 993-1009/? I/System.out: 	java.util.concurrent.FutureTask.run(FutureTask.java:237)
2019-11-27 12:07:38.285 993-1009/? I/System.out: 	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
2019-11-27 12:07:38.285 993-1009/? I/System.out: 	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
2019-11-27 12:07:38.285 993-1009/? I/System.out: 	java.lang.Thread.run(Thread.java:761)
```

**Comment by LambergaR** [comment] 2020-03-15 19:54
Any luck with this? I agree with @ire4ever1190, this is probably an Android issue, but can't find a workaround ...

**Comment by LambergaR** [comment] 2020-03-15 19:56
also tried this

```
package com.sonc.playground.jetpacktest.data.api.dto

import kotlinx.serialization.*

@Serializable
data class PhotoDto(
    var albumId: Int,
    var id: Int,
    @Serializable(with = CustomStringDeserializer::class)
    var title: AString?,
    @Serializable(with = CustomStringDeserializer::class)
    var url: AString?,
    @Serializable(with = CustomStringDeserializer::class)
    var thumbnailUrl: AString?
)

class AString(val value: String)

@Serializer(forClass = AString::class)
object CustomStringDeserializer : KSerializer<AString> {
    override val descriptor: SerialDescriptor = object : SerialDescriptor {
        override val kind: SerialKind = StructureKind.CLASS
        override val name: String = "AString"

        override fun getElementIndex(name: String): Int {
            return 0
        }

        override fun getElementName(index: Int): String {
            return ""
        }

        override fun isElementOptional(index: Int): Boolean {
            return true
        }
    }

    override fun deserialize(input: Decoder): AString {
        return AString("")
    }

    override fun serialize(output: Encoder, obj: AString) {
    }

}
```

But it throws the same type of exception

```
2020-03-15 20:51:12.267 13514-13514/com.sonc.playground.jetpacktest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sonc.playground.jetpacktest, PID: 13514
    java.lang.ClassCastException: com.sonc.playground.jetpacktest.data.api.dto.AString cannot be cast to java.lang.Void
        at com.sonc.playground.jetpacktest.data.api.dto.PhotoDto$$serializer.deserialize(PhotoDto.kt:7)
        at com.sonc.playground.jetpacktest.data.api.dto.PhotoDto$$serializer.deserialize(Unknown Source:0)
        at kotlinx.serialization.CoreKt.decode(Core.kt:84)
        at kotlinx.serialization.json.JSON.parse(JSON.kt:43)
        at kotlinx.serialization.json.JSON$Companion.parse(JSON.kt:60)
        at com.sonc.playground.jetpacktest.data.api.provider.impl.PhotoProvider$get$1.invokeSuspend(PhotoProvider.kt:31)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
2020-03-15 20:51:12.293 13514-13514/? I/Process: Sending signal. PID: 13514 SIG: 9
```

**Comment by klemmjerome** [comment] 2020-06-03 19:38
Is it possible that you are using jetpack compose. I got the same issue when using jetpack compose. Without compose enabled everything works fine.

It occurs when you have a string property in your serialized object.
With Integer values like they are given in the examples for kotlinx serialization it works.

So this might be a bug with jetpack compose. And that is why this issue is marked as "can't reproduce". Because the code works without using jetpack compose.

I reported the bug to the jetpack compose team.

**Comment by robertoestivill** [comment] 2020-06-11 07:24
@klemmjerome do you have a link to the reported issue? I'm facing the same problem and would love to keep track.

**Comment by klemmjerome** [comment] 2020-06-11 10:46
Yes :
https://issuetracker.google.com/issues/157901343

For me its not a big problem, i just used gson instead of kotlinx
serialization and when the bug its fixed i will exchange it ^_^

Roberto Estivill <notifications@github.com> schrieb am Do., 11. Juni 2020,
09:24:

**Closed** 2020-07-23 18:50 UTC
Labels: compose

**Comment by klemmjerome** [comment] 2020-07-23 18:56
Why this issue is closed ? Is it resolved ?
My comment did not solve the problem. It was just a hint to get it fixed.

Leonid Startsev <notifications@github.com> schrieb am Do., 23. Juli 2020,
20:50:

**Comment by sandwwraith** [comment] 2020-07-24 15:59
@klemmjerome see https://github.com/Kotlin/kotlinx.serialization/issues/770#issuecomment-661743674
