### ISSUE TITLE
JsonElement should expose the original value

### ISSUE THREAD

**Issue by bluenote10** [Kotlin/kotlinx.serialization#1799] opened 2021-12-20 10:48 UTC
**What is your use-case and why do you need this feature?**

I'm working with raw schema-less JSON data, i.e., I need to use the plain `JsonElement` class. The use case involves accessing the underlying value wrapped by `JsonElement`.

Currently this is awkward and inefficient, because the `JsonElement` only exposes the underlying value in the form of a `String`. This requires repeated re-parsing of the string (plus incorporating the `isString` information) to get e.g. actual boolean/number values etc.

**Describe the solution you'd like**

I'm completely new to Kotlin, so I lack the skills to draft an ideal solution.

What I would have expected from a user perspective is that the `JsonElement` is modeled like JSON data is modeled in other languages, i.e., with explicit (sealed) subclasses for `JsonString`, `JsonNumber`, `JsonBoolean`, `JsonNull`, `JsonArray`, `JsonObject`, where all e.g. `x.value` of the appropriate type.

**Comment by bluenote10** [comment] 2021-12-20 10:54
It should be noted that the extension functions defined on `JsonPrimitive` don't fully solve that issue, because they lose type information. For instance `JsonPrimitive("true")` allows to extract a boolean although it wasn't constructed from a boolean. My use case also involves maintaining accurate type information.

**Comment by sandwwraith** [comment] 2021-12-20 11:29
> What I would have expected from a user perspective is that the JsonElement is modeled like JSON data is modeled in other languages, i.e., with explicit (sealed) subclasses for JsonString, JsonNumber, JsonBoolean, JsonNull, JsonArray, JsonObject

Well, there are `JsonObject`, `JsonArray`, `JsonPrimitive` and `JsonNull`, so you can do

```kotlin
when(element) {
  is JsonObject -> ...
  is JsonArray -> ...
  is JsonNull -> ....
  else -> ...
}
```

Does it solve your problem?

Regarding type information in `JsonPrimitive`: see https://github.com/Kotlin/kotlinx.serialization/issues/1298#issuecomment-764746213

**Comment by bluenote10** [comment] 2021-12-20 11:38
No, because `JsonPrimitive` mixes strings, numbers, booleans, and nulls into a field `content: String`. The original value is lost, and if you look into how e.g. `JsonPrimitive.boolean` is implemented you can see the inefficient re-parsing I was referring to.

**Comment by sandwwraith** [comment] 2021-12-20 13:10
Then it's a duplicate of #1298, I answered you there

**Closed by sandwwraith** 2021-12-20 13:10 UTC
Labels: question
