### ISSUE TITLE
Accessing Json companion outside of main thread fails on native

### ISSUE THREAD

**Issue by kpgalligan** [Kotlin/kotlinx.serialization#441] opened 2019-04-20 18:39 UTC
We have code to parse json that gets run on a background thread using `Json.nonstrict`. On first app run, this gets called before every other use of that companion object. When first run from a background thread, it'll attempt to reference `defaultJsonModule`:

runtime/common/src/main/kotlin/kotlinx/serialization/json/Json.kt:222

```kotlin
private val defaultJsonModule = serializersModuleOf(
    mapOf<KClass<*>, KSerializer<*>>(
        JsonElement::class to JsonElementSerializer,
    //Etc...
```

You cannot reference top level vals in native from a thread other than main. This should be refactored of marked `@SharedImmutable`

As a workaround, Referencing `Json.nonstrict` from somewhere else, in the main thread, causes the companion to initialize and everything works.

This seems to have worked on versions before 0.11.0 and Kotlin 1.3.30, but I'd need to do more verification and research to confirm.

**Comment by sandwwraith** [comment] 2019-04-22 11:53
I think better workaround will be creating your own json instance using `Json(JsonConfiguration(...))` constructor.

**Comment by sandwwraith** [comment] 2019-04-22 11:56
How do you exactly run a background thread? For some reason, I'm unable to reproduce this issue using workers (e.g. 

```kotlin
 val worker = Worker.start()
        val future = worker.execute(TransferMode.SAFE, { Unit }) {
            // data returned by the second function argument comes to the
            // worker routine as 'input' parameter.
                _ ->
            // Here we create an instance to be returned when someone consumes result future.
            val str2 = Json.nonstrict.stringify(SimpleData.serializer(), SimpleData("foo", 32))
            assertEquals("""{"foo":"foo","bar":32}""", str2)
            Json.nonstrict.parse(SimpleData.serializer(), str2)
        }
```

does not throw exception)

**Comment by kpgalligan** [comment] 2019-04-23 15:00
Hmm. Will follow up on repro

**Comment by kpgalligan** [comment] 2019-04-23 17:33
```kotlin
 val worker = Worker.start()
 val future = worker.execute(TransferMode.SAFE, { Unit }) {
        val str2 = Json.nonstrict.stringify(SimpleData.serializer(), SimpleData("foo", 32))
        assertEquals("""{"foo":"foo","bar":32}""", str2)
       Json.nonstrict.parse(SimpleData.serializer(), str2)
}.result
```
The `.result` at the end will consume the future (test will pass prematurely otherwise). Then, you need to make sure the test is run first.

```
./runtime/native/build/test-exe/test/debug/test.kexe --ktest_regex_filter=.*[your test name/class].*
```

Doing that I can repro locally.

[Screen recording on youtube](https://www.youtube.com/watch?v=nCJTRoSl2V0&feature=youtu.be) (unlisted)

**Comment by benasher44** [comment] 2019-04-24 21:36
it still fails if you create your own `Json` instance because initializing a `Json` accesses `defaultJsonModule`, which is not marked as `@SharedImmutable`.

**Comment by benasher44** [comment] 2019-04-24 22:31
You can workaround this by declaring a global Json that's immutable, which (I think) will get setup and frozen during K/N runtime init. Seems to be working locally
```
@SharedImmutable
private val DEFAULT_JSON = Json(your_config)
```

**Comment by benasher44** [comment] 2019-04-24 22:56
Oh this is technically a different bug. Will file a new ticket.

**Comment by benasher44** [comment] 2019-04-24 23:03
Filed #446

**Closed** 2019-06-20 09:46 UTC
Labels: native, runtime
