### ISSUE TITLE
Exception during serializing of subclass of abstract class in Kotlin/MPP

### ISSUE THREAD

**Issue by and-marsh** [Kotlin/kotlinx.serialization#995] opened 2020-08-20 10:02 UTC
**Describe the bug**
Hi, i have a Kotlin/MPP project with `iOS`, `Android` and `macOS` targets. When I tried to implement example from [here](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/polymorphism.md#registered-subclasses), I got an exception for macOs and iOS:
```
kotlinx.serialization.SerializationException: Serializer for class 'Project' is not found.
Mark the class as @Serializable or provide the serializer explicitly.
```
For Android it works fine:
```
{"type":"owned","name":"kotlinx.coroutines","owner":"kotlin"}
``` 

**To Reproduce**
My `build.gradle` and code is [attached](https://github.com/Kotlin/kotlinx.serialization/files/5102147/Archive.zip)
`SerializableTest.kts` is from commonMain dir, `CommonTest.kts` - from commonTest dir. Tests were started via gradle tasks `iosX64Test` and `macosX64Test`

**Expected behavior**
Succesful serialization on macOS and iOS like this:
```
{"type":"owned","name":"kotlinx.coroutines","owner":"kotlin"}
```

**Environment**
 - Kotlin version: `1.4.0`
 - Library version: `1.0.0-RC`
 - Kotlin platforms: `iOS`, `Android` and `macOS`
 - Gradle version: `6.5`
 - Other relevant context: `macOS Catalina 10.15.5`

**Comment by qwwdfsad** [comment] 2020-08-24 11:34
Thanks for the self-contained reproducer!
See the response and potential workarounds here: https://github.com/Kotlin/kotlinx.serialization/issues/1000#issuecomment-678983701

Closing as duplicate of #1000

**Closed by qwwdfsad** 2020-08-24 11:34 UTC

**Comment by and-marsh** [comment] 2020-08-29 17:59
Thanks a lot!
