### ISSUE TITLE
Unexpected type error on JS

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.serialization#1004] opened 2020-08-24 07:41 UTC
Unexpected type error:
```
@Serializable
class A(val prop: String) {
    val prop2: String = when(prop) {
        "aaa" -> "222"
        else -> {
            println("AAA") // Side effect
            "333"
        }
    }
    val prop3 = prop.length // unexpected TypeError
}
@Test
fun test() {
    val a = A("aaa")
    println(Json.encodeToString(a))
}
```

**Comment by InsanusMokrassar** [comment] 2020-08-25 13:44
Hello, is there any progress or some approximate date/release number when this issue will be fixed?

**Comment by qwwdfsad** [comment] 2020-08-26 08:21
Hi, unfortunately not yet

**Comment by sandwwraith** [comment] 2020-09-02 16:46
Workaround: use `val prop3 get() = prop.length`

**Comment by sandwwraith** [comment] 2020-09-02 16:47
Duplicate of #716, I assume

**Closed by sandwwraith** 2020-09-02 16:47 UTC
Labels: bug, compiler-plugin
