### ISSUE TITLE
Json.decodeFromStream throws IllegalArgumentException on Android 6.0 after migrating to kotlinx-serialization:1.5.0

### ISSUE THREAD

**Issue by NutsHell912** [Kotlin/kotlinx.serialization#2231] opened 2023-03-14 23:12 UTC
**Json.decodeFromStream throws IllegalArgumentException after migrating to kotlinx-serialization:1.5.0 on Android 6.0(API Level 23)**

`Json.decodeFromStream` call on Android 6.0(API Level 23)  throws  `IllegalArgumentException: Bad position` if stream has size more than 16384 (2^15) bytes.

Stacktrace:
![image](https://user-images.githubusercontent.com/23400995/224897545-6f6e5804-65f3-4b46-a454-08ea20e3edf3.png)

But there is no such problem on API 24+ or with previous serialization version(1.4.1)

I assume that it is because of recently added `kotlinx.serialization.json.internal.CharsetReader` in 1.5.0

**To Reproduce**
Code example:
```
    @OptIn(ExperimentalSerializationApi::class)
    private fun handleJson() {
        val someJson = "{\"id\":\"1\"},"
        val resultString = "[" + someJson.repeat(1490).removeSuffix(",") + "]"
        // 16391 bytes, more than 16384 (2^15),
        val byteArray = resultString.toByteArray(java.nio.charset.StandardCharsets.UTF_8)
        val stream = ByteArrayInputStream(byteArray)
        // throws java.lang.IllegalArgumentException: Bad position on Api level 23  if stream more than 16384 bytes
        // but works on 24+ with any stream sizes
        val parsedResponse = Json.decodeFromStream<List<SomeDto>>(stream)
        val textView: TextView = findViewById(R.id.text_view)
        textView.text = parsedResponse.firstOrNull()?.id
    }
```

Or simple repository with this problem: [https://github.com/NutsHell912/kotlinx_serialization_IllegalArgumentException](https://github.com/NutsHell912/kotlinx_serialization_IllegalArgumentException)

**Environment**
 - Kotlin version: 1.8.10
 - Library version: 1.5.0
 - Kotlin platforms: Android 6.0(API Level 23)

**Comment by badmannersteam** [comment] 2023-06-30 10:40
Hey!
Any news about this?
Because of this 1.5.x branch is literally broken now on Android 5-6 😢

**Comment by h6ah4i** [comment] 2023-07-18 14:32
I am also facing a crashing issue on my project, but the stack trace is different like this. However, the root cause of this Android 6.0 incompatibility is the same, I suppose...

```
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 8264: Expected quotation mark '"', but had 's' instead at path: $.stacks['32'].description
  JSON input: .....      ],
  "specialFeatures": [],
   "name": "Basic a.....
at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:584)
at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:582)
at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json(AbstractJsonLexer.kt:223)
at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(AbstractJsonLexer.kt:206)
at kotlinx.serialization.json.internal.AbstractJsonLexer.consumeNextToken(AbstractJsonLexer.kt:195)
at kotlinx.serialization.json.internal.ReaderJsonLexer.consumeKeyString(JsonLexer.kt:143)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeStringKey(StreamingJsonDecoder.kt:337)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeObjectIndex(StreamingJsonDecoder.kt:224)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeElementIndex(StreamingJsonDecoder.kt:175)
...
```

I've also found a workaround. Using the  `decodeFromBufferedSource()` method (which is included in `kotlinx-serialization-json-okio`) resolve the issue for my project and the sample code NutsHell912 created.

Here's a forked version of the sample code: (https://github.com/h6ah4i/kotlinx_serialization_IllegalArgumentException/commit/a6955ae72099fd33ee5bb6af7774172cf47ece6c)

**Comment by shanshin** [comment] 2023-11-02 20:48
Closed as a duplicate of #2457 

Workaround in old Android versions is to use `decodeFromString`, see https://github.com/Kotlin/kotlinx.serialization/issues/2457#issuecomment-1786923342

**Closed by shanshin** 2023-11-02 20:48 UTC
Labels: json

**Comment by grote** [comment] 2023-11-07 17:48
But what if the string is too big to fit into memory and we are reading from a stream intentionally? Are you sure this is an old isolated Android bug or related to the fact that older Android versions are still using Java 6 and are unable to desuger the CharsetDecoderICU?

**Comment by pdvrieze** [comment] 2023-11-08 09:45
@grote The problem is that it is a bug in Android that has since been fixed. Either using strings as a workaround could work, otherwise you may need to use okio for it. The problem is that the `SerialReader` is internal (although technically public with an annotation) and there is no separate support for readers (only streams).
