### ISSUE TITLE
Broken deserialization with JsonTransformingSerializer

### ISSUE THREAD

**Issue by rlconst** [Kotlin/kotlinx.serialization#2597] opened 2024-03-08 09:46 UTC
**Describe the bug**
I want to deserialize `[[1, "foo"],[2, "bar"]]` into data classes but Transformer is failing with

```
Parameter specified as non-null is null: method kotlinx.serialization.json.JsonTransformingSerializer.<init>, parameter tSerializer
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlinx.serialization.json.JsonTransformingSerializer.<init>, parameter tSerializer
```

Example with working and failed case. Value class could be a workaround

```
@JvmInline
@Serializable
value class FooList(
  val results: List<@Serializable(with = FooSerializer::class) Foo>,
)

@Serializable
data class Foo(
  val a: Int,
  val b: String,
)

object FooSerializer : JsonTransformingSerializer<Foo>(Foo.serializer()) {
  override fun transformDeserialize(element: JsonElement): JsonElement =
    if (element is JsonArray) {
      JsonObject(
        mapOf(
          "a" to element[0],
          "b" to element[1],
        )
      )
    } else {
      throw IllegalStateException("Can't parse $element")
    }
}

class Test : StringSpec({
  "Success" {
    val json: String = """[
      [1, "foo"],
      [2, "bar"]
    ]""".trimIndent()

    val list: FooList = Json.decodeFromString(json)

    list shouldBe FooList(listOf(
      Foo(1, "foo"),
      Foo(2, "bar")
    ))
  }

  "Fail" {
    val json: String = """[
      [1, "foo"],
      [2, "bar"]
    ]""".trimIndent()

    val list: List<@Serializable(FooSerializer::class) Foo> = Json.decodeFromString(json)

    list shouldBe listOf(
      Foo(1, "foo"),
      Foo(2, "bar")
    )
  }
})
```

If I add with to Serializable on `Foo`
```
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 8: Expected start of the object '{', but had '[' instead at path: $[0]
```

**Environment**
 - Kotlin version: 1.9.22
 - Library version: 1.9.22
 - Kotlin platforms: JVM
 - Gradle version: 7.6.4

**Comment by pdvrieze** [comment] 2024-03-08 14:41
The problem is that you pass `Foo.serializer()` as parameter to the serializer. `Foo.serializer()` at will resolve to `FooSerializer` but you are calling it in its own constructor. As such you have an initialisation loop. Note that it is probably also incorrect to have a self-referential serializer.

**Comment by sandwwraith** [comment] 2024-03-08 15:06
> Foo.serializer() at will resolve to FooSerializer but you are calling it in its own constructor.

this shouldn't happen, because Foo class declaration is marked as `@Serializable`, not `@Serializable(FooSerializer::class)`

**Comment by sandwwraith** [comment] 2024-03-08 15:07
However, ` val list: List<@Serializable(FooSerializer::class) Foo> = Json.decodeFromString(json)` is incorrect, because annotations do not affect anything outside a serializable class. 

To fix this, write `Json.decodeFromString(ListSerializer(FooSerializer), json)`

**Comment by rlconst** [comment] 2024-03-10 14:17
@sandwwraith why library doesn't pick up default Foo serializer?

**Comment by rlconst** [comment] 2024-03-10 14:20
I think [documentation](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md) is missing a very important section on how these annotations work with decode/encode under the hood. Currently it's too much magic inside.Sorry, but I have no idea what @pdvrieze or @sandwwraith is talking about, especially where initialization loop is coming from.

**Closed** 2024-03-10 14:29 UTC
Labels: question
