### ISSUE TITLE
Context-aware reference resolution during deserialization

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.serialization#1363] opened 2021-03-09 11:59 UTC
The use-case concerns serialization of a deeply-linked data structure. As a concrete example, consider the following simplified data structure that represents a polyhedron. A polyhedron has a list of indexed vertices and a list of faces, each face listing vertices that are adjacent to it:

```kotlin
@Serializable
class Polyhedron(
    val vertices: List<Vertex>,
    val faces: List<Face>
)

@Serializable
class Vertex(
    @Transient
    val id: Int = -1,
    val x: Double,
    val y: Double,
    val z: Double
)

@Serializable(with = FaceSerializer::class)
class Face(
    val vertices: List<Vertex>
)
```

Notice how `Vertex.id` field is marked as `@Transient` because we don't need to serialize it. There is an invariant that `Vertex.id` matches its index in `Polyhedron.vertices` list. For the same reason of avoiding duplication, we implement a custom serializer for a `Face` class, representing it only as a list of vertex ids, without serializing each `Vertex` all over again. Our end goal is that a cube, for example, should be represented with the following JSON:

```
{
    "vertices": [
        {"x":1.0,"y":1.0,"z":-1.0},{"x":-1.0,"y":1.0,"z":-1.0},{"x":-1.0,"y":-1.0,"z":-1.0},{"x":1.0,"y":-1.0,"z":-1.0},
        {"x":1.0,"y":1.0,"z":1.0},{"x":-1.0,"y":1.0,"z":1.0},{"x":-1.0,"y":-1.0,"z":1.0},{"x":1.0,"y":-1.0,"z":1.0}
    ],
    "faces": [[0,1,2,3],[0,4,5,1],[1,5,6,2],[2,6,7,3],[3,7,4,0],[4,7,6,5]]
}
```

This JSON output can be achieved by writing the following custom `FaceSerializer`:

```
object FaceSerializer : KSerializer<Face> {
    private val serializer = serializer<List<Int>>()
    override val descriptor = serializer.descriptor

    override fun serialize(encoder: Encoder, value: Face) {
        encoder.encodeSerializableValue(serializer, value.vertices.map { it.id })
    }

    override fun deserialize(decoder: Decoder): Face {
        TODO("Not yet implemented")
    }
}
```

However, there does not seem to be an easy way to implement deserialization for a valid `Polyhedron` instance can be reconstructed from this JSON. The only workaround is to go fully-custom, that is write a custom deserializer for a whole `Polyhedron` class, which might be impractical in larger real-life examples. The following pieces are missing:

* We cannot deserialize a `@Transient id` field of `Vertex` so that it contains an actual index of the face in the `vertices` list.
* We cannot deserialize a `Face` class instance, so that has references to the `Vertex` instances of the corresponding polyhedron.

There needs to be some architecture that allows such data structures to be deserialized. With an appropriate design, it will cover a wide range of internal references in serialized data.

P.S The full use-case demo code is here: https://gist.github.com/elizarov/e85fd3527abbe6ebc88b4ec80911fd7b

**Comment by sandwwraith** [comment] 2021-03-19 14:00
Looks like the same context mentioned in #1147

**Comment by altavir** [comment] 2021-08-21 08:01
I've encountered a similar case with the CERN ROOT json format. Any node in it could be replaced with `{"$red": 22}` node which references any other object in the graph (I am not yet really sure how the reference number is generated). The solution is here: https://github.com/mipt-npm/visionforge/blob/1b2d61008f4d8602d0ca4735fdfed89591702376/cern-root-loader/src/commonMain/kotlin/ru/mipt/npm/root/rootJson.kt

I store the node cache in the serializer module and use the serializer module as a context and re-create it on each deserialization.

**Comment by sandwwraith** [comment] 2024-12-23 15:38
Duplicate of #1147

**Closed by sandwwraith** 2024-12-23 15:38 UTC
Labels: feature
