### ISSUE TITLE
Cannot deserialize polymorphic interface with concrete implementation being a value type

### ISSUE THREAD

**Issue by zjuhasz** [Kotlin/kotlinx.serialization#1495] opened 2021-05-17 18:38 UTC
I have only tested with JSON on JVM.

Example -
```
private val module = SerializersModule {
    polymorphic(Foo::class) {
        subclass(FooImpl::class)
    }
}

private val json = Json {
    this.serializersModule = module
}

public fun main() {
    val serialized = json.encodeToString(PolymorphicSerializer(Foo::class), FooImpl(1))
    val deserialized = json.decodeFromString(PolymorphicSerializer(Foo::class), serialized)
}

public interface Foo

@Serializable
@JvmInline
public value class FooImpl(public val a: Int) : Foo
```

Error -
```
Exception in thread "main" kotlinx.serialization.json.internal.JsonDecodingException: Expected class kotlinx.serialization.json.JsonObject (Kotlin reflection is not available) as the serialized body of kotlinx.serialization.Polymorphic<Foo>, but had class kotlinx.serialization.json.JsonLiteral (Kotlin reflection is not available)
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:84)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:32)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:95)
	at TestKt.main(Test.kt:26)
	at TestKt.main(Test.kt)
```

If you remove `value` modifier from `FooImpl`, everything works fine.

**Comment by raamcosta** [comment] 2023-04-18 14:38
I also found this issue. Sealed interface with two value classes, all annotated with @Serializable, and it fails with this same error:

Expected class kotlinx.serialization.json.JsonObject (Kotlin reflection is not available) as the serialized body of <MY_VALUE_CLASS>, but had class kotlinx.serialization.json.JsonLiteral (Kotlin reflection is not available)

**Comment by sandwwraith** [comment] 2023-04-19 14:48
Duplicate of #2049
Note that it is not fixed for _decoding_ deliberately, as it is requires special serializer, see the comment: https://github.com/Kotlin/kotlinx.serialization/issues/2049#issuecomment-1476647228

**Closed by sandwwraith** 2023-04-19 14:48 UTC
