### ISSUE TITLE
Serialization of word null to string throws error

### ISSUE THREAD

**Issue by CharlieTap** [Kotlin/kotlinx.serialization#1660] opened 2021-09-05 22:26 UTC
I have an application which has a dictionary of german words, one of which is the word null. Attempting to serialize this to a data class produces: Unexpected JSON token at offset 516116: Unexpected 'null' value instead of string literal

**To Reproduce**

   For example if you have a data class

`@Serializable
data class DictionaryLookup(
    val word: String
)`

and the json

`{"word":"null"}`

You will receive the error

**Expected behavior**

No error, its serialized to a string containing the word null

**Environment**
 - Kotlin version: [1.5.21]
 - Library version: [1.2.2]
 - Kotlin platforms: [JVM]
 - Gradle version: [7.1.1]
 - IDE version [Android Studio 2020.3.1]

**Comment by qwwdfsad** [comment] 2021-09-06 11:09
Dupe of #1600

**Closed by qwwdfsad** 2021-09-06 11:09 UTC
Labels: json, runtime
