### ISSUE TITLE
Feature request: @Embedded annotation for properties

### ISSUE THREAD

**Issue by kroegerama** [Kotlin/kotlinx.serialization#1734] opened 2021-10-18 19:11 UTC
**What is your use-case and why do you need this feature?**

I'm writing a code generator for OpenApi specs. To model `allOf` schemas, it would be really handy, if kotlinx.serialization would support embedding of properties.
As an example, the Room library has a similar feature: https://developer.android.com/reference/androidx/room/Embedded

**Describe the solution you'd like**

Example schema:

```yaml
Pet:
  type: object
  properties:
    name:
      type: string
Fur:
  type: object
  properties:
    color:
      type: string
Dog:
  - $ref: '#/components/schemas/Pet'
  - $ref: '#/components/schemas/Fur'
```

I would then represent this schema using the following classes:

```kotlin

@Serializable
data class Pet(
  val name: String
)

@Serializable
data class Fur(
  val color: String
)

@Serializable
data class Dog(
  @Embedded
  val  pet: Pet,
  @Embedded
  val fur: Fur
)
```

Serializing `Dog(pet = Pet("Barko"), fur = Fur("brown"))` to JSON would print:

```json
{
  "name":  "Barko",
  "color": "brown"
}
```

There is no easy way to define `Dog`, because: 1. `Fur` and `Pet` are `data` classes and 2. it's impossible to extend two classes.

---

The `@Embedded` annotation could also support a `prefix`, so that

```kotlin
@Serializable
data class Dog(
  @Embedded(prefix = "pet_")
  val  pet: Pet,
  @Embedded(prefix = "fur_")
  val fur: Fur
)
```

would generate:

```json
{
  "pet_name":  "Barko",
  "fur_color": "brown"
}
```

**Comment by sandwwraith** [comment] 2024-11-28 11:12
Duplicate of #292

**Closed by sandwwraith** 2024-11-28 11:12 UTC
Labels: feature
