### ISSUE TITLE
@Serializable meta-annotation

### ISSUE THREAD

**Issue by rnett** [Kotlin/kotlinx.serialization#1284] opened 2021-01-09 06:27 UTC
**What is your use-case and why do you need this feature?**

I have a few situations where I would like to have an annotation that also applies `@Serializable`, so that I can serialize the class, and then do something with it.  For example, a config library that uses the HOCON serialization but also auto-generates `reference.conf`, or a type safe argument parser library.  Most of these with compiler plugins, so it's conceivable I could add `@Serializable` myself during the right phase, but it's easier to do it via meta annotation and supports non-compiler plugin uses.

Something like this is generally possible by using `@Serializable` and a custom annotation with `@SerialInfo`, but that is more verbose than necessary and there's no way to guarantee everything annotated with the custom annotation is indeed serializable.

**Describe the solution you'd like**

A `@MetaSerializable` annotation that causes any annotations annotated with it to be treated as `@Serializable` by the compiler plugin.  Also a `@MetaSerializable.WithParameter` or similar to designate a `KClass` parameter in my annotation as the equivalent of `@Serializable`s `with` parameter.

**Comment by rnett** [comment] 2021-03-02 01:44
Note that this has been brought up by the Ktor team in [KTOR-1165](https://youtrack.jetbrains.com/issue/KTOR-1165#focus=Comments-27-4699392.0-0).

**Comment by efenderbosch** [comment] 2021-07-30 16:51
looks like a dupe of #1127?

**Comment by rnett** [comment] 2021-07-30 19:10
Maybe?  That issue is for a meta annotation for specifying the serializer to use, this one is for specifying `@Serializable` (which can do that, but will also generate serializers when on classes, which is mostly what I'm after).  You could make this one just generation.

**Comment by sandwwraith** [comment] 2023-02-06 13:53
Closing as duplicate of #1127 (we already have `@MetaSerializable` btw)

**Closed by sandwwraith** 2023-02-06 13:53 UTC
Labels: feature
