### ISSUE TITLE
Deserialization doesn't initialize delegate interfaces when the delegate is initialized by a function

### ISSUE THREAD

**Issue by tianyu** [Kotlin/kotlinx.serialization#1039] opened 2020-09-03 20:06 UTC
**Describe the bug**

The following test fails:
```kotlin
@Serializable
class MyMap(val foo: Int): Map<String, Int> by mapOf("foo" to foo)

class TestDeserializeDelegate {
  @Test
  fun test() {
    Json.decodeFromString(MyMap.serializer(), "{\"foo\":1}")
      .keys
  }
}
```

With a `NullPointerException` at `MyMap.getKeys`.

**Expected behavior**

```kotlin
Json.decodeFromString(MyMap.serializer(), "{\"foo\":1}")
      .keys // Should return 1
```

**Environment**
 - Kotlin version: 1.4.0
 - Library version: 1.0.0-RC
 - Kotlin platforms: JVM and JS
 - Gradle version: 6.2.2

**Comment by sandwwraith** [comment] 2020-09-04 11:11
Duplicate of #241, probably

**Comment by tianyu** [comment] 2020-09-06 13:52
Closed as duplicate

**Closed** 2020-09-06 13:52 UTC
