### ISSUE TITLE
Problems with methods in Kotlin/JS

### ISSUE THREAD

**Issue by MarcinMoskala** [Kotlin/kotlinx.serialization#104] opened 2018-03-26 17:59 UTC
```
@Serializable
data class Article(
        val id: Int,
        val data: ArticleData,
        override val dateTime: DateTime = data.occurrence
) : News {
    val title get() = data.title
    val subtitle get() = data.subtitle
    val imageUrl get() = data.imageUrl
    val url get() = data.url
    val occurrence get() = data.occurrence
}

@Serializable
data class ArticleData(
        val title: String,
        val subtitle: String,
        val imageUrl: String,
        val url: String?,
        val occurrence: DateTime
)
```

I have the error on deserialization in Kotlin/JS:
```
"MissingFieldException: Field title is required, but it was missing
    at Article_init (webpack-internal:///95:374:13)
    at Article$$serializer.load_ljkqvg$ (webpack-internal:///95:345:12)
    at JSON$JsonInput.KInput.readSerializableValue_rf0fz3$ (webpack-internal:///94:703:19)
    at JSON$JsonInput.ElementValueInput.readSerializableElementValue_nqb5fm$ (webpack-internal:///94:1061:17)
    at ArrayListSerializer.ListLikeSerializer.readItem_ieea3b$ (webpack-internal:///94:3115:51)
    at ArrayListSerializer.ListLikeSerializer.update_qkk2oh$ (webpack-internal:///94:3098:22)
    at ArrayListSerializer.ListLikeSerializer.load_ljkqvg$ (webpack-internal:///94:3107:17)
    at JSON$JsonInput.KInput.readSerializableValue_rf0fz3$ (webpack-internal:///94:703:19)
    at JSON$JsonInput.ElementValueInput.readSerializableElementValue_nqb5fm$ (webpack-internal:///94:1061:17)
    at NewsData$$serializer.load_ljkqvg$ (webpack-internal:///95:1463:49)"
```

When I use:

```
@Serializable
data class Article(
        val id: Int,
        val data: ArticleData,
        override val dateTime: DateTime = data.occurrence
): News

val Article.title get() = data.title
val Article.subtitle get() = data.subtitle
val Article.imageUrl get() = data.imageUrl
val Article.url get() = data.url
val Article.occurrence get() = data.occurrence
```

Everything is ok.

Whole project:
https://github.com/MarcinMoskala/KotlinAcademyApp

**Comment by MarcinMoskala** [comment] 2018-03-30 06:56
```
e: org.jetbrains.kotlin.js.facade.exceptions.TranslationRuntimeException: Unexpected error occurred compiling the following fragment: 'package org.kotlinacademy.data

import kotlinx.serialization.Serializable
import kotlinx.serialization.Transient
import org.kotlinacademy.DateTime

@Serializable
data class Article(
        val id: Int,
        val data: ArticleData,
        override val dateTime: DateTime = data.occurrence
): News {
    @Transient val title get() = data.title
    @Transient val subtitle get() = data.subtitle
    @Transient val imageUrl get() = data.imageUrl
    @Transient val url get() = data.url
    @Transient val occurrence get() = data.occurrence
}' at (1,1) in /home/marcin/IdeaProjects/KotlinAcademyApp/common/src/main/kotlin/org/kotlinacademy/data/Article.kt
        at org.jetbrains.kotlin.js.translate.general.Translation.translateFile(Translation.java:390)
        at org.jetbrains.kotlin.js.translate.general.Translation.doGenerateAst(Translation.java:299)
        at org.jetbrains.kotlin.js.translate.general.Translation.generateAst(Translation.java:261)
        at org.jetbrains.kotlin.js.facade.K2JSTranslator.translateUnits(K2JSTranslator.java:134)
        at org.jetbrains.kotlin.js.facade.K2JSTranslator.translate(K2JSTranslator.java:96)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.translate(K2JSCompiler.java:150)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:278)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:82)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:108)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:92)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$1$2.invoke(CompileServiceImpl.kt:395)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$1$2.invoke(CompileServiceImpl.kt:97)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:909)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:97)
        at org.jetbrains.kotlin.daemon.common.DummyProfiler.withMeasure(PerfUtils.kt:137)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.checkedCompile(CompileServiceImpl.kt:939)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.doCompile(CompileServiceImpl.kt:908)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:394)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
        at sun.rmi.transport.Transport$1.run(Transport.java:200)
        at sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: transient without an initializer
        at org.jetbrains.kotlinx.serialization.compiler.backend.js.SerializableJsTranslator$generateInternalConstructor$f$1.invoke(SerializableJsTranslator.kt:79)
        at org.jetbrains.kotlinx.serialization.compiler.backend.js.SerializableJsTranslator$generateInternalConstructor$f$1.invoke(SerializableJsTranslator.kt:38)
        at org.jetbrains.kotlinx.serialization.compiler.backend.js.JsCodegenUtilKt.buildFunction(JsCodegenUtil.kt:84)
        at org.jetbrains.kotlinx.serialization.compiler.backend.js.SerializableJsTranslator.generateInternalConstructor(SerializableJsTranslator.kt:52)
        at org.jetbrains.kotlinx.serialization.compiler.backend.common.SerializableCodegen.generateSyntheticInternalConstructor(SerializableCodegen.kt:39)
        at org.jetbrains.kotlinx.serialization.compiler.backend.common.SerializableCodegen.generate(SerializableCodegen.kt:33)
        at org.jetbrains.kotlinx.serialization.compiler.backend.js.SerializableJsTranslator$Companion.translate(SerializableJsTranslator.kt:101)
        at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationJsExtension.generateClassSyntheticParts(SerializationJsExtension.kt:31)
        at org.jetbrains.kotlin.js.translate.declaration.ClassTranslator.generateClassSyntheticParts(ClassTranslator.kt:153)
        at org.jetbrains.kotlin.js.translate.declaration.ClassTranslator.translate(ClassTranslator.kt:111)
        at org.jetbrains.kotlin.js.translate.declaration.ClassTranslator.access$translate(ClassTranslator.kt:63)
        at org.jetbrains.kotlin.js.translate.declaration.ClassTranslator$Companion.translate(ClassTranslator.kt:568)
        at org.jetbrains.kotlin.js.translate.declaration.AbstractDeclarationVisitor.visitClassOrObject(AbstractDeclarationVisitor.kt:44)
        at org.jetbrains.kotlin.js.translate.declaration.AbstractDeclarationVisitor.visitClassOrObject(AbstractDeclarationVisitor.kt:37)
        at org.jetbrains.kotlin.psi.KtVisitor.visitClass(KtVisitor.java:33)
        at org.jetbrains.kotlin.psi.KtClass.accept(KtClass.kt:34)
        at org.jetbrains.kotlin.js.translate.general.Translation.translateFile(Translation.java:382)
        ... 35 more
```

**Comment by MarcinMoskala** [comment] 2018-03-30 06:59
Steps to reproduce:
1. Get this code: https://github.com/MarcinMoskala/KotlinAcademyApp/tree/Make_data_model_properties_transistent_instead_of_extensions
2. Run using `./gradlew :web:run`

**Comment by sandwwraith** [comment] 2018-03-30 13:03
I think it has the same origin as #2 but for JS side. Current workaround is indeed specify properties without backing fields as extension ones.

**Comment by sandwwraith** [comment] 2018-03-30 13:10
Regarding first version of the issue, it might be unexpected if properties w/o backing fields will be transient by default. (maybe you want them to be included in serialization and you don't care about deserialization). Since this library is still under design, we prefer to stick to explicitness and therefore I can say that `@Transient` annotation is required for such properties to work.

**Comment by sandwwraith** [comment] 2018-03-30 13:10
So now it is a duplicate of #107, as I can see

**Closed by sandwwraith** 2018-03-30 13:10 UTC
Labels: bug, compiler-plugin
