### ISSUE TITLE
Allow to set serializer for a class in Json intialization

### ISSUE THREAD

**Issue by kormik** [Kotlin/kotlinx.serialization#1952] opened 2022-05-27 14:55 UTC
I would be great if we had an option to set serializer for a class during Json initialization or in serializers module. Something like this:

```
Json {
    useSerializer(SomeClass::class, CustomSerializer)
}
```
or
```
SerializersModule {
    useSerializer(SomeClass::class, CustomSerializer)
}
```
It would allow us to set/ovveride serializer for a class from a library which is out of our control.

For example in my app I would like to serialize `kotlinx.datetime.Instant` as a number of miliseconds but the class is annotated `@Serializable(with = InstantIso8601Serializer::class)` and I can't change it.

**Comment by sandwwraith** [comment] 2022-05-30 12:02
Check out https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#specifying-serializers-for-a-file and also https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#contextual-serialization. These serializers always have higher priority than a `@Serializable(with=...)` on a class and can be configured per file. Does this solve your problem?

**Comment by kormik** [comment] 2022-05-31 06:43
> Check out https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#specifying-serializers-for-a-file and also https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#contextual-serialization. These serializers always have higher priority than a `@Serializable(with=...)` on a class and can be configured per file. Does this solve your problem?

Thank you for reply. I've seen this but I don't think it's a good option. I would like to set it for the whole project to be sure the same serializer is used everywhere. Annotating every single case (or file) is a bit painful and may lead to errors when someone forgot it.

**Comment by sandwwraith** [comment] 2024-11-25 18:42
I guess it is a duplicate of #507

**Closed by sandwwraith** 2024-11-25 18:42 UTC
Labels: question
