### ISSUE TITLE
Class with non properties can not be automatically serializable

### ISSUE THREAD

**Issue by majkrzak** [Kotlin/kotlinx.serialization#501] opened 2019-06-25 21:12 UTC
**Describe the bug**
When class constructors contains non property parameter it can not be made serializable with @Serializable annotaion
 
**To Reproduce**

    @Serializable
    class Foo(bar: String){
        val lol: String = bar.toLowerCase()
    }

**Expected behavior**

    Json.stringify(Foo.serializer(), Foo("LoL"))
    
    {
        "lol": "lol"
    }

**Environment**
 - Kotlin version: 1.3.40
 - Library version: 0.11.1
 - Kotlin platforms: JVM
 - Gradle version: Gradle 5.4.1-20190522110022+0000

**Comment by sandwwraith** [comment] 2019-06-27 13:48
This is a conceptual limitation. See, on deserialization, when the `lol` field is missing, you need to recreate it as `bar.toLowerCase()` (properties with default values are considered optional). But you can't because you don't have `bar`. It's not even a field, so it has no chance to be serialized. Therefore such classes can't be serializable.

**Comment by majkrzak** [comment] 2019-06-27 14:01
You are messing serialization and deserialization. Also class can be
deserialized if delegate provides the setvalue

**Comment by sandwwraith** [comment] 2019-06-27 14:13
Yes, I'm talking about deserialization. While 'serializable-only' concept is legit and has its use cases, this library focuses on making both processes available without corner cases, so making a class serializable and non-deserialziable is a non-goal.

> Also class can be
deserialized if delegate provides the setvalue

That's what I've mentioned in the issue about delegates.

**Comment by majkrzak** [comment] 2019-06-27 14:27
Sorry, I've messed the tickets.

**Comment by sandwwraith** [comment] 2024-11-28 17:47
Duplicate of #599

**Closed by sandwwraith** 2024-11-28 17:47 UTC
Labels: question, design

**Comment by majkrzak** [comment] 2024-11-28 18:05
I used to believe that 501 goes before 599

**Comment by sandwwraith** [comment] 2024-11-28 18:06
Yes, but discussion here has more votes and different comments, so it is better to keep that one open
