### ISSUE TITLE
Multiplatform/iOS Generated headers for JsonElement has invalid declarations

### ISSUE THREAD

**Issue by jblorenzo** [Kotlin/kotlinx.serialization#414] opened 2019-03-22 16:43 UTC
kotlinx_serialization_version = 0.10.0
kotlin-multiplatform = 1.3.12

Actually not sure if this is a kotlin multiplatform issue or a kotlin serialization one. I compiled my kotlin multiplatform to iOS frameworks and it gave me this:

```
@interface Posting_apiKotlinx_serialization_runtime_nativeJsonPrimitive : Posting_apiKotlinx_serialization_runtime_nativeJsonElement
@property (readonly) BOOL boolean;
@property (readonly) Posting_apiBoolean * _Nullable booleanOrNull;
@property (readonly) NSString *content;
@property (readonly) NSString * _Nullable contentOrNull;
@property (readonly) double double;
@property (readonly) Posting_apiDouble * _Nullable doubleOrNull;
@property (readonly) float float;
@property (readonly) Posting_apiFloat * _Nullable floatOrNull;
@property (readonly) int32_t int;
@property (readonly) Posting_apiInt * _Nullable intOrNull;
@property (readonly) int64_t long;
@property (readonly) Posting_apiLong * _Nullable longOrNull;
@end;
```

notice `double double`, `float float`, etc

I think this is the related element in the class

```
@Optional
val parameters: JsonElement? = null,
```

**Comment by sandwwraith** [comment] 2019-03-22 17:33
Duplicate of #306, see it for workaround. I also suppose that https://github.com/JetBrains/kotlin-native/pull/2747 have fixed this and will be available in nearest release.

**Closed by sandwwraith** 2019-03-22 17:33 UTC
