### ISSUE TITLE
Support properties naming configuration

### ISSUE THREAD

**Issue by raderio** [Kotlin/kotlinx.serialization#319] opened 2018-12-31 10:17 UTC
Is it possible to configure that in Kotlin classes have properties in camel case, but on serialization/deserialization json properties are in snake case?

To configure globally for all classes, not each property like
```
@Serializable
data class(
   @SerialName("my_string") val myString: String
)
```

This is supported in Jackson 
```
val mapper = ObjectMapper();
mapper.setPropertyNamingStrategy(PropertyNamingStrategy.CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES);
        return mapper;
```

**Comment by gildor** [comment] 2019-01-06 12:55
Duplicate of #33

**Closed** 2019-01-06 15:14 UTC
