### ISSUE TITLE
Unable to serialize Class with genetics

### ISSUE THREAD

**Issue by elkasvirElka** [Kotlin/kotlinx.serialization#1312] opened 2021-01-27 22:17 UTC
**Describe the bug**
I have a class that has 2 generics:
@Serializable
data class TestClass<ResponseType, ScoreType>(  
        var response: ResponseType? = null,
        var score: ScoreType? = null) : TestInterface

And I register it this way
val resultSerializerModule = SerializersModule {
    polymorphic(TestInterface::class) {
        subclass(TestClass.serializer(PolymorphicSerializer(String::class), PolymorphicSerializer(String::class)))
       //Also tried subclass(TestClass.serializer(String.serializer(), String.serializer()))
    }
}

Got this issue:
Class 'TestClass' is not registered for polymorphic serialization in the scope of 'TestInterface'.
    Mark the base class as 'sealed' or register the serializer explicitly.

**Environment**
 - Kotlin version: '1.4.10'
 - Library version: 1.0.1
 - Gradle version: 4.1.1
 -   classpath("org.jetbrains.kotlin:kotlin-serialization:1.4.10")

**Comment by sandwwraith** [comment] 2021-01-29 13:07
Can you also show your input json/class?

**Comment by elkasvirElka** [comment] 2021-01-29 17:21
It's a class. ArrayList<TestClass> here is what I have in the debugger before deserialization.
![example](https://user-images.githubusercontent.com/37272004/106306459-b7aedd80-6223-11eb-8b9d-b365e93d1855.jpg)
response and score could be null or string type
another item will be the same, but with these values:
response = "2"
score = "0"

**Comment by sandwwraith** [comment] 2024-12-16 18:27
Duplicate of #1252

**Closed by sandwwraith** 2024-12-16 18:27 UTC
