### ISSUE TITLE
CompilationException: Back-end (JVM) Internal error: Couldn't transform method node

### ISSUE THREAD

**Issue by Mazel-Tovr** [Kotlin/kotlinx.serialization#1684] opened 2021-09-18 10:43 UTC
**Describe the bug**
```
org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Couldn't transform method node:
<clinit> ()V:
   L0
    NEW com/epam/StoredClassData$$serializer
    DUP
    INVOKESPECIAL com/epam/StoredClassData$$serializer.<init> ()V
    PUTSTATIC com/epam/StoredClassData$$serializer.INSTANCE : Lcom/epam/StoredClassData$$serializer;
   L1
    LINENUMBER 6 L1
    NOP
    NEW kotlinx/serialization/internal/PluginGeneratedSerialDescriptor
    DUP
    LDC "com.epam.StoredClassData"
    GETSTATIC com/epam/StoredClassData$$serializer.INSTANCE : Lcom/epam/StoredClassData$$serializer;
    CHECKCAST kotlinx/serialization/internal/GeneratedSerializer
    ICONST_2
    INVOKESPECIAL kotlinx/serialization/internal/PluginGeneratedSerialDescriptor.<init> (Ljava/lang/String;Lkotlinx/serialization/internal/GeneratedSerializer;I)V
    ASTORE 0
   L2
    ALOAD 0
    LDC "version"
    NOP
    ICONST_0
    INVOKEVIRTUAL kotlinx/serialization/internal/PluginGeneratedSerialDescriptor.addElement (Ljava/lang/String;Z)V
    ALOAD 0
    NEW com/epam/Id$Impl
    DUP
    INVOKESPECIAL com/epam/Id$Impl.<init> ()V
    CHECKCAST java/lang/annotation/Annotation
    INVOKEVIRTUAL kotlinx/serialization/internal/PluginGeneratedSerialDescriptor.pushAnnotation (Ljava/lang/annotation/Annotation;)V
    ALOAD 0
    LDC "data"
    NOP
    ICONST_0
    INVOKEVIRTUAL kotlinx/serialization/internal/PluginGeneratedSerialDescriptor.addElement (Ljava/lang/String;Z)V
    ALOAD 0
    NEW com/epam/StreamSerialization$Impl
    DUP
    LDC "KRYO"
    CHECKCAST java/lang/Number
    INVOKEVIRTUAL java/lang/Number.intValue ()I
    ICONST_0
    CHECKCAST [Ljava/lang/String;
    ICONST_1
    ANEWARRAY java/lang/String
    ASTORE 1
   L3
    ALOAD 1
    ICONST_0
    LDC "com.epam.kodux.Method"
    AASTORE
    ALOAD 1
   L4
    CHECKCAST java/lang/String
    INVOKESPECIAL com/epam/StreamSerialization$Impl.<init> (I[Ljava/lang/String;Ljava/lang/String;)V
    CHECKCAST java/lang/annotation/Annotation
    INVOKEVIRTUAL kotlinx/serialization/internal/PluginGeneratedSerialDescriptor.pushAnnotation (Ljava/lang/annotation/Annotation;)V
    ALOAD 0
    CHECKCAST kotlinx/serialization/descriptors/SerialDescriptor
    PUTSTATIC com/epam/StoredClassData$$serializer.descriptor : Lkotlinx/serialization/descriptors/SerialDescriptor;
   L5
    LINENUMBER 11 L5
    NOP
    RETURN
   L6
    MAXSTACK = 8
    MAXLOCALS = 2

File is unknown
The root cause java.lang.AssertionError was thrown at: org.jetbrains.kotlin.codegen.optimization.MethodVerifier.transform(MethodVerifier.kt:28)
	at org.jetbrains.kotlin.codegen.TransformationMethodVisitor.visitEnd(TransformationMethodVisitor.kt:92)
	at org.jetbrains.org.objectweb.asm.MethodVisitor.visitEnd(MethodVisitor.java:782)
	at org.jetbrains.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:772)
	at org.jetbrains.kotlin.backend.jvm.codegen.ClassCodegen.generateMethod(ClassCodegen.kt:391)
	at org.jetbrains.kotlin.backend.jvm.codegen.ClassCodegen.generate(ClassCodegen.kt:134)
	at org.jetbrains.kotlin.backend.jvm.codegen.ClassCodegen.generate(ClassCodegen.kt:143)
	at org.jetbrains.kotlin.backend.jvm.JvmLowerKt$codegenPhase$1$1.lower(JvmLower.kt:304)
	at org.jetbrains.kotlin.backend.common.phaser.FileLoweringPhaseAdapter.invoke(PhaseBuilders.kt:120)
	at org.jetbrains.kotlin.backend.common.phaser.FileLoweringPhaseAdapter.invoke(PhaseBuilders.kt:116)
	at org.jetbrains.kotlin.backend.common.phaser.NamedCompilerPhase.invoke(CompilerPhase.kt:96)
	at org.jetbrains.kotlin.backend.common.phaser.PerformByIrFilePhase.invokeSequential(performByIrFile.kt:65)
	at org.jetbrains.kotlin.backend.common.phaser.PerformByIrFilePhase.invoke(performByIrFile.kt:55)
	at org.jetbrains.kotlin.backend.common.phaser.PerformByIrFilePhase.invoke(performByIrFile.kt:41)
	at org.jetbrains.kotlin.backend.common.phaser.NamedCompilerPhase.invoke(CompilerPhase.kt:96)
	at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:29)
	at org.jetbrains.kotlin.backend.common.phaser.NamedCompilerPhase.invoke(CompilerPhase.kt:96)
	at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:29)
	at org.jetbrains.kotlin.backend.common.phaser.NamedCompilerPhase.invoke(CompilerPhase.kt:96)
	at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.invokeToplevel(CompilerPhase.kt:43)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.doGenerateFilesInternal(JvmIrCodegenFactory.kt:191)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.generateModule(JvmIrCodegenFactory.kt:60)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:35)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.generate(KotlinToJVMBytecodeCompiler.kt:321)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:113)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:56)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:169)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:92)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:412)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:112)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:358)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally$default(IncrementalCompilerRunner.kt:300)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:160)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:81)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:607)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:96)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1658)
	at sun.reflect.GeneratedMethodAccessor107.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: AFTER mandatory stack transformations: incorrect bytecode
	at org.jetbrains.kotlin.codegen.optimization.MethodVerifier.transform(MethodVerifier.kt:28)
	at org.jetbrains.kotlin.codegen.optimization.transformer.CompositeMethodTransformer.transform(CompositeMethodTransformer.kt:25)
	at org.jetbrains.kotlin.codegen.optimization.OptimizationMethodVisitor.performTransformations(OptimizationMethodVisitor.kt:62)
	at org.jetbrains.kotlin.codegen.TransformationMethodVisitor.visitEnd(TransformationMethodVisitor.kt:70)
	... 54 more
Caused by: org.jetbrains.org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 40: Expected an object reference, but found I
	at org.jetbrains.org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:291)
	at org.jetbrains.kotlin.codegen.optimization.transformer.MethodTransformer.runAnalyzer(MethodTransformer.java:32)
	at org.jetbrains.kotlin.codegen.optimization.transformer.MethodTransformer.analyze(MethodTransformer.java:45)
	at org.jetbrains.kotlin.codegen.optimization.MethodVerifier.transform(MethodVerifier.kt:26)
	... 57 more
Caused by: org.jetbrains.org.objectweb.asm.tree.analysis.AnalyzerException: Expected an object reference, but found I
	at org.jetbrains.org.objectweb.asm.tree.analysis.BasicVerifier.unaryOperation(BasicVerifier.java:172)
	at org.jetbrains.org.objectweb.asm.tree.analysis.BasicVerifier.unaryOperation(BasicVerifier.java:43)
	at org.jetbrains.org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:591)
	at org.jetbrains.org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:187)
	... 60 more

```

**To Reproduce**
Mark some field of data class with this annotation and compile code.

```
@SerialInfo
@Target(AnnotationTarget.PROPERTY)
annotation class StreamSerialization(
    val serializationType: String,
    val compressType: Int,
    val poolRegistration: Array<String> = [],
)
```
I made a project-example which reproduces the given bug just run `CompilationExceptionTest` test 
https://github.com/Mazel-Tovr/Kotlin-serialization-bugs-sample
PS If we remove `@Target(AnnotationTarget.PROPERTY)` code will compile 

**Expected behavior**
Code compile
**Environment**
 - Kotlin version: 1.5.30
 - Library version: 1.2.2
 - Kotlin platforms: JVM
 - Gradle version: 6.5.1 or 7.1

**Comment by sandwwraith** [comment] 2021-09-27 14:24
Looks like some parameter passed to a serial info property is boxed incorrectly

**Comment by sandwwraith** [comment] 2022-08-08 09:57
Closing as obsolete, as it is reproduces only with old non-IR compiler

**Closed by sandwwraith** 2022-08-08 09:57 UTC
Labels: bug, compiler-plugin
