### ISSUE TITLE
Serialization / Deserialization failes on Kotlin Native

### ISSUE THREAD

**Issue by JulianHahn96** [Kotlin/kotlinx.serialization#2447] opened 2023-09-18 06:20 UTC
On Kotlin Native the serialization / deserialization of open inheritance does not work, while on jvm and js it works fine.

**To Reproduce**
See the attached project ([TestDeserializeNative.zip](https://github.com/Kotlin/kotlinx.serialization/files/12645078/TestDeserializeNative.zip)) and execute the SimpleTest for jvm and native.

**Expected behavior**
The Test case should work on all platforms.

**Environment**
 - Kotlin version: [e.g. 1.9.10]
 - Library version: [e.g. 1.6.0]
 - Kotlin platforms: [e.g. JVM, JS, Native]
 - Gradle version: [e.g. 8.1.1]
 - JDK: 17, Native: Windows

**Comment by pdvrieze** [comment] 2023-09-18 08:44
I've noticed one error: `TestInterface` must be marked as `Serializable` and is not. Probably once you fix that your code works.

**Comment by JulianHahn96** [comment] 2023-09-18 09:04
If i mark it as @Serializable i also need to provide a custom serializer, or make it sealed. Indeed it will work then, however in my real usecase the 2 classes come from different projects and so i can not make it sealed.

This would normally not work in jvm and js either, but therefore i made the custom SerializersModule and provide the information there.

**Comment by pdvrieze** [comment] 2023-09-18 09:36
You're right. I was not looking carefully. The interface doesn't need to be marked serializable. I've ran a few tests. What is going on is the following:
- Native does not support most of reflection, including the reflection needed to recognize the interface as such
- Explicitly specifying `PolymorphicSerializer(TestInterface::class)` works correctly
- The compiler plugin uses intrinsics for `serializer<T>()` (indirectly used in decodeFromString etc.)
- The JVM version correctly applies the intrinsic in both cases (the bytecode gets/creates the correct serializers directly and without reflection)
- The native version (probably - I haven't bothered to disassemble it) doesn't support the intrinsic and falls back to runtime reflection
- The runtime reflection fails because of limited reflection support
- Note that this mechanism isn't used for members, only for top-level polymorphics.

For you, it is probably easiest to explicitly create the correct serializer (`PolymorphicSerializer(TestInterface::class)` where you need this at toplevel.
At the same time this is clearly a bug/missing feature in the native compiler plugin.

**Comment by sandwwraith** [comment] 2023-09-20 17:06
Hi, I've take a look at your reproducer and the problem is in `json.decodeFromString<TestInterface>(testString1)`. Unfortunately, Kotlin/Native has very limited reflection capabilities and it is missing `KClass.isInterface`. Therefore, kotlinx.serialization is unable to determine that TestInterface is an interface and return correct serializer. Exception message you get even have a line about that: 

> kotlinx.serialization.SerializationException: Serializer for class 'TestInterface' is not found.
Please ensure that class is marked as `@Serializable` and that the serialization compiler plugin is applied.
To get enum serializer on Kotlin/Native, it should be annotated with `@Serializable` annotation.
**To get interface serializer on Kotlin/Native, use PolymorphicSerializer() constructor function.**

So, yes, solution is to call `json.decodeFromString(PolymorphicSerializer(TestInterface::class), testString1)`.

**Closed by sandwwraith** 2023-09-20 17:06 UTC
