### ISSUE TITLE
Serialization of a derived class throws an exception when the base is present in a different module. 

### ISSUE THREAD

**Issue by eswarmalla** [Kotlin/kotlinx.serialization#927] opened 2020-07-23 07:24 UTC
**Describe the bug**
The base class in present in kotlin mutliplatform project and I am producing an aar for consuming it. The derived class which is present external to this module is used to serialize it. 

However this always gives me an exception when doing so. Do note that the derived class when present in the same module has no problem in serializing the class. 

**To Reproduce**

For e.g 

Module 1 --> kotlin multiplatform 
open class Base {
  // some properties. 
}

I am consuming the aar in a different module and using the serializable module 

    fun getSerializableModule(): SerialModule {
       val module =  SerializersModule {
            polymorphic(Base::class) {
                Base::class with PairedDevice.serializer()
                DerivedInModule::class with DerivedInModule.serializer()
            }
        }
       val moduleDerived = SerializersModule {
            polymorphic(Base::class) {
                DerivedOutsideModule::class with DervicedOutsideModule.serializer()
            }
        }
        return module.plus(moduleDerived)
    }

This is then used to serialize the objects to json in the original module 

 val json = Json(context = serialModule)
            json.stringify(
                PolymorphicSerializer(Base::class).list,
                listOfObject 
            )

However, this throws me an exception when doing so. 

java.lang.ArrayIndexOutOfBoundsException: 0

	at 

kotlinx.serialization.internal.PluginGeneratedSerialDescriptor.getElementName(PluginGeneratedSerialDescriptor.kt:102)
	at kotlinx.serialization.json.internal.StreamingJsonOutput.encodeElement(StreamingJsonOutput.kt:123)
	at kotlinx.serialization.builtins.AbstractEncoder.encodeStringElement(AbstractEncoder.kt:68)
	at Base.write$Self(Base.kt)
	at Base.write$Self(DerivedOutsideModule.kt)
	at DerivedOutsideModule$$serializer.serialize(DerivedOutsideModule.kt)
	at DerivedOutsideModule$serializer.serialize(DerivedOutsideModule.kt:17)
	at kotlinx.serialization.json.internal.StreamingJsonOutput.encodeSerializableValue(StreamingJsonOutput.kt:237)
	at kotlinx.serialization.builtins.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:72)
	at kotlinx.serialization.internal.ListLikeSerializer.serialize(CollectionSerializers.kt:76)
	at kotlinx.serialization.json.internal.StreamingJsonOutput.encodeSerializableValue(StreamingJsonOutput.kt:227)
	at kotlinx.serialization.EncodingKt.encode(Encoding.kt:402)
	at kotlinx.serialization.json.Json.stringify(Json.kt:100)
	at Serializer.test(SerializerTest.kt:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)

**Expected behavior**
Serialization should happen properly. 

**Environment**
 - Kotlin version: 1.3.72
 - Library version: 0.20.0
 - Kotlin platforms: JVM
 - Gradle version: 6.1.1
 - IDE version (if bug is related to the IDE) Android studio 4.0 
 - Other relevant context [e.g. OS version, JRE version, ... ]

**Comment by altavir** [comment] 2020-07-23 07:47
It is a duplicate of #378. They promised to fix it in 1.4/1.0.0.

**Closed** 2020-08-04 14:04 UTC
Labels: In next release, duplicate
