### ISSUE TITLE
Ability to skip unknown enum values in a "List<Enum>, Set<Enum>" scenarios

### ISSUE THREAD

**Issue by skymansandy** [Kotlin/kotlinx.serialization#1598] opened 2021-07-12 20:27 UTC
**Problem:**
I have an API model class that has a `Set<EnumType>`. During deserialization, if there are any unknown enum values in the set, the deserialization currently fails with `NoSuchElementFoundExcpeption`. 

I found that `coerceInputValues = true` will handle some scenarios where there is a default value. But that works well with direct enum fields that have a default value. In this case it's a `List<Enum>` so there cant be one direct default value (since the element inside the list can be unknown)

**Sample Solution Preferred:**
Probably a way to NOT INCLUDE those values in the deserialized `List<>` or `Set<>` would be nice. Maybe through a config or something.  Maybe inside `ListSerializer(), SetSerializer()` impl.

So that if a Json enum list has 4 values out of which 1 is unknown. the `List<>` after deserialization can only contain 3 enums (known ones).

Please let me know if there's any more clarification needed. thanks.

**Comment by osipxd** [comment] 2021-07-31 17:15
Looks like related to #1205

**Comment by skymansandy** [comment] 2021-08-02 08:38
@osipxd yes it's the same issue. Do you know of any update on this feature request? I see there hasn't been much discussion on the other issue as well.

**Comment by osipxd** [comment] 2021-08-02 09:25
@skymansandy, unfortunately, not. Maybe @sandwwraith or @qwwdfsad can clarify the status of these issues.

**Comment by sandwwraith** [comment] 2021-08-13 11:37
I'll close this as a duplicate of #1113

But generally, #1205 also seems to be a popular feature request. I think we can try to plan it in the one of the next releases

**Closed by sandwwraith** 2021-08-13 11:37 UTC
Labels: feature, design
