### ISSUE TITLE
Incorrect Serialization when using an sealed interface

### ISSUE THREAD

**Issue by jeffdcamp** [Kotlin/kotlinx.serialization#2471] opened 2023-10-11 22:41 UTC
When a Sealed class is used in a Searializable class, the json created is incorrect.

**To Reproduce**

```
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json


fun main() {
    val mediaDto = MediaDto(
        associatedId = AudioId("123"),
        segments = listOf(
            MediaSegmentDto("p1"),
            MediaSegmentDto("p1"),
        )
    )
    val json = Json.encodeToString(MediaDto.serializer(), mediaDto)
    println(json)
}

@Serializable
data class MediaDto(
    @SerialName("id")
    val associatedId: MediaId,
    val segments: List<MediaSegmentDto> = emptyList()
)

@Serializable
data class MediaSegmentDto(val id: String?)

@Serializable
sealed interface MediaId {
    val value: String
}

@JvmInline
@Serializable
value class AudioId(override val value: String) : MediaId

@JvmInline
@Serializable
value class VideoId(override val value: String) : MediaId

```

Output (bad output... notice the "type": "kotlin.collections.Arraylist")

`{"id":"123","segments":["type":"kotlin.collections.ArrayList",{"id":"p1"},{"id":"p1"}]}`

Expected Output:

`{"id":"123","segments":[{"id":"p1"},{"id":"p1"}]}`

If I simply change MediaDto.associatedId datatype from MediaId (Sealed Class) to AudioId (Value Class).... then it works, but I then can't  use the base Sealed class (I won't be able to use VideoId or anything else that implements the Sealed class)

**Environment**
 - Kotlin version: 1.9.10
 - Library version: 1.6.0
 - Kotlin platforms: JVM
 - Gradle version: 8.3

**Comment by pdvrieze** [comment] 2023-10-12 09:44
I've not looked at the library code, but I suspect this is to do with the fact that you are combining a polymorphic type (`MediaId`) with inline instances of primitive types. To support the type discriminator I strongly suspect that a flag is set that will cause the writing of the structure to include a type discriminator. However, for a primitive type there is no place to set a discriminator, but rather than throwing an exception (or just resetting the flag) the flag is retained and observed the next time a struct (or in this case array) is written (for the list of segments is the next).

The Json generated is clearly incorrect, I would say the correct behaviour is to throw an exception. Unless you are in a mode (only in discussion/work for now) that does not write type discriminators at all (and thus will not work for deserialization).

As to the example, it is not possible to deserialize your expected output as it is not possible to know from the output whether it is an audio or a video id. If there is some way to know (maybe from the number) you can solve that by having a custom serializer rather than using the polymorphic serializer (where serialization just writes the id as string, and deserialization reads the string, determines the kind and returns the appropriate subtype).

**Comment by sandwwraith** [comment] 2023-10-12 13:22
Yes, this is a bug related to value classes. Duplicate of #2374.

Also related to #2451

**Closed by sandwwraith** 2023-10-12 13:22 UTC
