### ISSUE TITLE
Support M1

### ISSUE THREAD

**Issue by AshStefanOltmann** [Kotlin/kotlinx.serialization#1671] opened 2021-09-13 15:50 UTC
Now as Kotlin 1.5.30 is out it would be nice if you could add the targets `macosArm64` and `iosSimulatorArm64`.

**Comment by JakeWharton** [comment] 2021-09-13 15:53
Dupe of #1647

**Comment by sandwwraith** [comment] 2021-09-13 16:04
These targets are available in 1.3.0-RC

**Closed by sandwwraith** 2021-09-13 16:04 UTC
Labels: feature
