### ISSUE TITLE
Can't deserialize nested classes with inheritance

### ISSUE THREAD

**Issue by adam-arold** [Kotlin/kotlinx.serialization#145] opened 2018-06-01 14:48 UTC
I have the following nested classes in my test:

    @Serializable
    open class Nested

    @Serializable
    data class NestedOne(val one: String) : Nested()

    @Serializable
    data class NestedTwo(val two: String) : Nested()

    @Serializable
    data class Container(val value: String,
                         val nested: Nested)

When I try to serialize and deserialize them:

```
val container = Container(
        value = "value",
        nested = NestedOne("one"))


val json = JSON.stringify(container)

JSON.parse<Container>(json)
```

I get this exception:

> java.lang.ClassNotFoundException: com.example.Playground.NestedOne
> 
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:264)
> 	at kotlinx.serialization.internal.SerialCache.lookupSerializer$kotlinx_serialization_runtime(Polymorphic.kt:76)
> 	at kotlinx.serialization.internal.SerialCache.lookupSerializer$kotlinx_serialization_runtime$default(Polymorphic.kt:71)
> 	at kotlinx.serialization.ResolvingKt.serializerBySerialDescClassname(Resolving.kt:54)
> 	at kotlinx.serialization.PolymorphicSerializer.load(PolymorphicSerializer.kt:56)
> 	at kotlinx.serialization.KInput.readSerializableValue(Serialization.kt:243)
> 	at kotlinx.serialization.ElementValueInput.readSerializableElementValue(Serialization.kt:438)
> 	at com.example.Playground$Container$$serializer.load(Playground.kt)
> 	at com.example.Playground$Container$$serializer.load(Playground.kt:20)
> 	at kotlinx.serialization.KInput.read(Serialization.kt:209)
> 	at kotlinx.serialization.json.JSON.parse(JSON.kt:49)
> 	at kotlinx.serialization.json.JSON$Companion.parse(JSON.kt:59)
> 	at com.example.Playground.testLoad(Playground.kt:62)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:436)
> 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
> 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:170)
> 	at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)
> 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:166)
> 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:113)
> 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:58)
> 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:112)
> 	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
> 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
> 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
> 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:120)
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
> 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
> 	at java.util.Iterator.forEachRemaining(Iterator.java:116)
> 	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
> 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:120)
> 	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
> 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
> 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
> 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:120)
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
> 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
> 	at java.util.Iterator.forEachRemaining(Iterator.java:116)
> 	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
> 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:120)
> 	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
> 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
> 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
> 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:55)
> 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)
> 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
> 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
> 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
> 	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:65)
> 	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
> 	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
> 	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

My bet is that when deserializing this uses `Class.forName` behind the scenes but the Java syntax should be `com.example.Playground$NestedOne` instead of `com.example.Playground.NestedOne`

I think that when serializing a class `kotlinx.serialization` uses `KClass::qualifiedName` instead of `Class::name` and this causes the problem. (`Class.forName` only works with java-style names).
If you take a look at the stack trace above it uses an `URLClassLoader` which calls `Class.forName` under the hood.

If I move these classes to separate (non-nested) classes the serialization/deserialization works.

**Note that** If I don't use custom classes besides the root class the deserialization works *even if the root class is nested*:

    @Serializable
    data class SomeRootClass(val value: String)

    val someRootObj = SomeRootClass(
            value = "value")

    val json = JSON.stringify(someRootObj)

    JSON.parse<SomeRootClass>(json)

It also works if I don't use inheritance and my classes are not `open`:

    @Serializable
    data class Nested(val value: String)

    @Serializable
    data class Container(val value: String,
                         val nested: Nested)

**Comment by sandwwraith** [comment] 2018-06-01 14:54
Isn't this a duplicate of #126 ?

**Comment by adam-arold** [comment] 2018-06-01 15:03
It seems so although I didn't use `sealed` classes. I think I have the solution for it (see the bottom part of the issue above).

**Closed** 2018-06-01 15:30 UTC
