### ISSUE TITLE
NullPointerException: Parameter specified as non-null is null in abstract class

### ISSUE THREAD

**Issue by dakralex** [Kotlin/kotlinx.serialization#2537] opened 2024-01-01 11:47 UTC
I have implemented an abstract class as an abstraction for a JSON parser of very different JSON input files (they are not really related other than what data they hold, there is no common property name, but the data it holds is similar). I'm only interested in deserialization.

The abstract class looks something like this:

```kt
interface JsonEntry

abstract class JsonParser<T : JsonEntry> {
    abstract fun parseThisOrThat(entry: T): Any

    // ...

    @OptIn(ExperimentalSerializationApi::class)
    fun parseEntries(inputStream: InputStream) {
        val entries = inputStream.use { Json.decodeFromStream<List<T>>(it) }
        logger.info { "Parsed ${entries.size} entries." }

        // Do something with the data
        parseThisOrThat(entries[0])//...
    }

    fun parseEntries(files: List<File>) {
        logger.info { "Parsing ${files.size} JSON files..." }

        val inputStreams = files.map {
            when (it.extension) {
                "json" -> it.inputStream()
                "br" -> decodeBrotliFile(it)
                else -> TODO("Not implemented")
            }
        }

        inputStreams.map { parseEntries(it) }
    }
}
```

The specializations of `JsonEntry` look something like this:

```kt
@Serializable
data class FooJsonEntry(
    val id: String,
    val score: Double,
    val masterValues: List<String>,
    // ...
)

@Serializable
data class BarJsonEntry(
    val available: Boolean,
    @SerialName("basketItemID")
    val basketItemId: String? = null,
    val category: List<String>,
    // ...
)
```

And then I implement the abstract class `JsonParser` for their entry types and call them afterwards outside of the classes:

```kt
class FooJsonParser : JsonParser<FooJsonEntry>() {
    override fun parseThisOrThat(entry: FooJsonEntry): Any {
        // ...
    }
}

class BarJsonParser : JsonParser<BarJsonEntry>() {
    override fun parseThisOrThat(entry: BarJsonEntry): Any {
        // ...
    }
}

class SomewhereOutside : CliktCommand() {
    override fun run() {
        when (something) {
            Enum.FOO -> FooJsonParser().parseEntries(files)
            Enum.BAR -> BarJsonParser().parseEntries(files)
            else -> TODO("Not implemented")
        }
    }
}
```

This worked before without the abstraction, but I had a lot of duplicate code that I wanted to pull up in one class, as there will be something like 20+ different JSON input types that need to be parsed. There is no indicator inside the JSON itself what "type" of specialization that is, only the filename/my given type.

**Environment**
 - Kotlin version: 1.9.21
 - Library version: 1.6.2
 - Kotlin platforms: JVM
 - Gradle version: 8.4
 - IDE version (if bug is related to the IDE) IntelliJ IDEA 2023.3.2
 - JDK Version 17
 - OS Version Linux 6.6.8-arch1-1

**Comment by dakralex** [comment] 2024-01-01 12:18
This is the stacktrace output:

```
Exception in thread "main" java.lang.NullPointerException: Parameter specified as non-null is null: method kotlinx.serialization.SerializersKt__SerializersKt.serializer, parameter type
	at kotlinx.serialization.SerializersKt__SerializersKt.serializer(Serializers.kt)
	at kotlinx.serialization.SerializersKt.serializer(Unknown Source)
	at org.dakralex.pricevista.parser.JsonParser.parseEntries(JsonParser.kt:126)
	at org.dakralex.pricevista.parser.JsonParser.parseEntries(JsonParser.kt:105)
	at org.dakralex.pricevista.cli.UpdateCommand.run(UpdateCommand.kt:31)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:306)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:319)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:40)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:458)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:455)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:475)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:482)
	at org.dakralex.pricevista.DatagenCLIKt.main(DatagenCLI.kt:45)

FAILURE: Build failed with an exception.
```

**Comment by sandwwraith** [comment] 2024-01-02 13:43
Duplicate of #2528. In short, you can't use `decodeFromStream<List<T>>` if T is not reified, as you need to know the concrete serializer for T and, therefore, its actual type.

**Closed by sandwwraith** 2024-01-02 13:43 UTC
