### ISSUE TITLE
Polymorphic (de)serialization crashes with inline class

### ISSUE THREAD

**Issue by bubenheimer** [Kotlin/kotlinx.serialization#2049] opened 2022-10-07 02:48 UTC
**Describe the bug**

A sealed interface hierarchy containing an inline class fails on polymorphic (de)serialization. Depending on specific (de)serialization method used, different errors occur:

With decodeFromString():

kotlinx.serialization.json.internal.JsonDecodingException: Expected class kotlinx.serialization.json.JsonObject (Kotlin reflection is not available) as the serialized body of MyPoly, but had class kotlinx.serialization.json.JsonLiteral (Kotlin reflection is not available)

With encodeToJsonElement():

kotlinx.serialization.SerializationException: No tag in stack for requested element

**To Reproduce**

```
@Serializable
sealed interface MyPoly {
    @Serializable
    object Invalid : MyPoly

    @Serializable
    @JvmInline
    value class Valid(val value: String) : MyPoly
}
```

**Environment**
 - Kotlin version: 1.7.20
 - Library version: 1.4.0
 - Kotlin platforms: JVM

As for a workaround: is there anything simple besides turning the inline class into a data class?

**Comment by sandwwraith** [comment] 2022-10-07 12:37
The problem is actually on the side of initial serialization — it should be prohibited. 
We can't serialize primitives polymorphically, because there's no place to insert `"type":"MyPoly.Valid"` class discriminator. 
When we serialize a value class polymorphically, we simply get `"value"` string — and the deserializer expects an object to find a `type` key within it. 

As a workaround, you can switch to `Json { useArrayPolymorphism = true }` or replace the value class with a data class.

**Comment by bubenheimer** [comment] 2022-10-07 12:54
Is it possible to do this with a custom serializer for the value class? I had tried a simple one (with PrimitiveKind.String), but that only lead me toward `useArrayPolymorphism = true` as you mentioned. Would a different, non-PrimitiveKind custom serializer work, or is this just not an option?

**Comment by bubenheimer** [comment] 2022-10-07 14:46
To answer my own question: polymorphic serialization of value class works with non-PrimitiveKind custom serializer.

Ultimately, the best approach for my particular use case may be a custom serializer at the sealed interface level.

**Comment by sandwwraith** [comment] 2023-03-20 17:25
After giving it a second thought, I can say that problem with the *writing* of a value class is a duplicate of #1774. Once it is fixed, it would be possible to write a value class (without a discriminator, though). It is still impossible to read it back automatically, but you can fix it with a custom content-based serializer like here: https://github.com/Kotlin/kotlinx.serialization/issues/2159

**Closed by sandwwraith** 2023-03-20 17:25 UTC
Labels: bug, json, runtime
