### ISSUE TITLE
@Serializer annotation on class overrides implementation of KSerializer methods from base class

### ISSUE THREAD

**Issue by charleskorn** [Kotlin/kotlinx.serialization#918] opened 2020-07-18 23:30 UTC
**Describe the bug**
Let's say I have a class that I want to serialize, `A`. 

If I create a class `ASerializer` that implements `KSerializer<A>` directly and provides an implementation of `serialize()`, it works as expected, whether I include a `@Serializer` annotation on `ASerializer` or not.

However, if `ASerializer` inherits from another class (eg. `BaseSerializer`), and `BaseSerializer` implements `KSerializer<A>` and provides an implementation of `serialize()`, `BaseSerializer.serialize()` appears to be replaced by the default implementation if I include a `@Serializer` annotation on `ASerializer`. Removing the `@Serializer` annotation provides the desired behaviour of using the methods from the base class.

**To Reproduce**
See https://github.com/charleskorn/kotlinx-serialization-serializer-inheritance-issue/blob/master/src/main/kotlin/charleskorn/kotlinxserialization/serializerinheritance/App.kt.

For each of the cases, I've overridden `serialize()` to write the value as a string, suffixed with ` (serializer X)`.

Output is:

```
Companion object implements KSerializer directly, no @Serializer attribute
"hello (serializer 1)"

Companion object uses base class, has @Serializer attribute, base class implements custom serialize()
{"name":"hello"}

Companion object uses base class, no @Serializer attribute, base class implements custom serialize()
"hello (serializer 3)"

Companion object uses base class, has @Serializer attribute, companion implements custom serialize()
"hello (serializer 4)"
```

**Expected behaviour**

Output should be `"hello (serializer X)"` from each, as this is what is generated by the base serializer.

**Environment**
 - Kotlin version: 1.3.72
 - Library version: 0.20.0
 - Kotlin platforms: only tested on JVM
 - Gradle version: 6.5.1

**Comment by sandwwraith** [comment] 2020-07-22 17:05
It looks like a duplicate of #154 . 

But I say this maybe kinda desired behavior: documentation for `@Serializer` says that plugin will generate implementation inside this class, i.e. override members. Note that you don't have to apply `@Serializer` -- you still have to explicitly pass your custom serializer to `@Serializable(with=...)` or `@UseSerializers`, since `@Serializer` only instructs the plugin to generate implementation, not to use it.

**Closed by sandwwraith** 2020-07-22 17:05 UTC
Labels: design, duplicate

**Comment by charleskorn** [comment] 2020-07-22 22:41
I don't think this is desirable behaviour - if I have a class marked with `@Serializer` with explicit implementations for `descriptor`, `serialize()` and `deserialize()`, and then move one of them to a base class, they're suddenly not used. This doesn't align with what happens if you were to do the same thing with an ordinary Kotlin class - the base class implementation would be used.
