### ISSUE TITLE
Polymorphic/Sealed: Allow to change "type" to user-defined String

### ISSUE THREAD

**Issue by hfhbd** [Kotlin/kotlinx.serialization#910] opened 2020-07-14 20:08 UTC
**What is your use-case and why do you need this feature?**
For polymorphic and sealed class the compiler plugin generates an additional field called `type` which contains the serial name, either the class name or a custom string. Some JSON APIs do not use the "random" field name "type" to indicate the used type, but use instead the filed name "kind" or "tool" etc.

I want to customise the name of the field too.
```
"{ "kind":"Bar", "baz": 42 }" // instead of "{ "type":"Bar", "baz": 42 }"
```
**Describe the solution you'd like**
```
@Serializable(typeName = "kind") //Compiler plugin, generate SealedClassSerializer<Foo>("Foo", Foo::class, arrayOf(Foo.Bar::class), arrayOf(Foo.Bar.serializer()), "kind")
sealed class Foo {
            @Serializable
            @SerialName("Bar")
            data class Bar(val baz: Int) : Foo()
        }

```
with
```
@Target(AnnotationTarget.PROPERTY, AnnotationTarget.CLASS, AnnotationTarget.TYPE)
public annotation class Serializable(
    val with: KClass<out KSerializer<*>> = KSerializer::class, // it means -- use default serializer by default
    val typeName: String = "type"
)

@InternalSerializationApi
public class SealedClassSerializer<T : Any>(
    serialName: String,
    override val baseClass: KClass<T>,
    subclasses: Array<KClass<out T>>,
    subclassSerializers: Array<KSerializer<out T>>, typeName: String = "type"
) : AbstractPolymorphicSerializer<T>() {

    override val descriptor: SerialDescriptor = SerialDescriptor(serialName, PolymorphicKind.SEALED) {
        element(typeName, String.serializer().descriptor)
        val elementDescriptor =
            SerialDescriptor("kotlinx.serialization.Sealed<${baseClass.simpleName}>", UnionKind.CONTEXTUAL) {
                subclassSerializers.forEach {
                    val d = it.descriptor
                    element(d.serialName, d)
                }
            }
        element("value", elementDescriptor)
    }
```

alternative, using a new annotation class
```
@Serializable
@TypeName("kind")  
sealed class Foo {
            @Serializable
            @SerialName("Bar")
            data class Bar(val baz: Int) : Foo()
        }
```

**Comment by sandwwraith** [comment] 2020-08-04 16:33
Seems like a duplicate of #546 to me. Am I right that you want to use different type discriminators with different class hierarchies? Global type discriminator can be configured in json builder.

**Comment by hfhbd** [comment] 2020-08-06 06:39
Yes, you are right. I don’t want multiple class discriminators, that would be nice too, but I want to have a custom class discriminator for each polymorphic class. 
Eg:
Sealed class A uses `tool` and sealed class B uses `name`.

**Comment by qwwdfsad** [comment] 2020-08-17 10:47
>Do you have any work in process? Or which branch should be used to develop this feature maybe? dev?

We do not have any work in progress regarding this feature right now. The working branch is always `dev`, tho we are not ready to accept **any** contribution. The best way to contribute is to help us with an API design: explain your use-case in a detailed manner, tell us whether other frameworks support this feature and how and draft a desired API shape (without an implementation!) to solve this ussue


Closing as duplicate, let's discuss it in #546

**Closed by qwwdfsad** 2020-08-17 10:47 UTC
Labels: duplicate, feature
