### ISSUE TITLE
1.7.2 has problem with ktor 3.0.0-rc-1 for multiplatform, gradle sync has errors

### ISSUE THREAD

**Issue by hmy65** [Kotlin/kotlinx.serialization#2813] opened 2024-09-10 03:09 UTC
kotlinxSerialization = "1.7.2"      
ktor = "3.0.0-beta-2" 

When I sync gradle, it shows following errors: (no problem for 1.7.1)

:composeApp:commonMain: Could not resolve org.jetbrains.kotlin:kotlin-stdlib-common.
Required by:
    WorkSpaceCMP:unspecified-detachedConfiguration28:unspecified > org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.2 > org.jetbrains.kotlinx:kotlinx-serialization-json-jvm:1.7.2
    WorkSpaceCMP:unspecified-detachedConfiguration28:unspecified > io.ktor:ktor-serialization-kotlinx-json:3.0.0-beta-2 > io.ktor:ktor-serialization-kotlinx-json-jvm:3.0.0-beta-2 > io.ktor:ktor-serialization-kotlinx:3.0.0-beta-2 > io.ktor:ktor-serialization-kotlinx-jvm:3.0.0-beta-2 > org.jetbrains.kotlinx:kotlinx-serialization-core:1.7.2 > org.jetbrains.kotlinx:kotlinx-serialization-core-jvm:1.7.2

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by hmy65** [comment] 2024-09-11 01:44
> You should use Kotlin 2.0.20 for Kotlinx Serialization 1.7.2.
> 
> ktor 3.0.0-rc-1 has just been released and it is using Kotlin 2.0.20 out of the box.

Tried ktor 3.0.0-rc-1 with kotlin 2.0.20 and v1.7.2, still.

:composeApp:commonMain: Could not resolve org.jetbrains.kotlin:kotlin-stdlib-common.
Required by:
    WorkSpaceCMP:unspecified-detachedConfiguration28:unspecified > org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.2 > org.jetbrains.kotlinx:kotlinx-serialization-json-jvm:1.7.2
    WorkSpaceCMP:unspecified-detachedConfiguration28:unspecified > io.ktor:ktor-client-core:3.0.0-rc-1 > io.ktor:ktor-client-core-jvm:3.0.0-rc-1 > io.ktor:ktor-http:3.0.0-rc-1 > io.ktor:ktor-http-jvm:3.0.0-rc-1 > org.jetbrains.kotlinx:kotlinx-serialization-core:1.7.2 > org.jetbrains.kotlinx:kotlinx-serialization-core-jvm:1.7.2

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by sandwwraith** [comment] 2024-09-11 15:38
Duplicate of #2810

**Closed by sandwwraith** 2024-09-11 15:38 UTC
