### ISSUE TITLE
Json decoding using non JsonOutput

### ISSUE THREAD

**Issue by InsanusMokrassar** [Kotlin/kotlinx.serialization#615] opened 2019-11-27 07:42 UTC
For now, it is impossible to decode `JsonElement` from decoder inside of serializer if that `decoder` was not created by `Json`. Example:

```kotlin
object : KSerializer<Any> {
    override val descriptor = StringDescriptor.withName("Example")

    override fun deserialize(decoder: Decoder) {
        val json = JsonElementSerializer.deserialize(decoder)
    }

    override serialize(encoder: Encoder, obj: Any) {
        TODO()
    }
}
```

Object will throw exception in `deserialize` method each time when this serializer will not be used with Json formatter.

Is it possible to solve this problem?

**Comment by altavir** [comment] 2019-11-27 07:48
I also would like this feature implemented. Currently `Json` serialization is only possible with `JsonOutput`. It severely limits its usage for generic tree-like objects. It is obvious that serialized Json is not so beautiful without actual json to back it, but still it is possible and should be done.

**Comment by qwwdfsad** [comment] 2019-12-11 14:18
This restriction is here for a reason. 
This is a fundamental restriction of serialization design: `Decoder` is a **structured** interface. It can decode `nextInt`, `nextEnum` etc., but it cannot decode "next JSON field that can be either a number, or a string, or a nested object". And `JsonElement` is unstructured by its nature. There is just no way to implement it.

But wait, how is it implemented for `JsonOutput` if that's the case? `JsonOutput` is not an arbitrary `Decoder`, it, basically, has "give me the whole underlying string and parse it as JSON" under the hood. Moreover, calling its "give me ..." in an arbitrary place is unsafe (filed #624).

Even if we were to add some kind of `StringableDecoder`, it is still unclear how to expose this APPI to be safe and composable with other serializers

**Comment by qwwdfsad** [comment] 2019-12-11 14:21
What we can do, though, is to integrate with `kotlinx-io` and then implement this functionality in top of `Input` in a safe manner

**Comment by altavir** [comment] 2019-12-11 15:13
> This is a fundamental restriction of serialization design: `Decoder` is a **structured** interface. It can decode `nextInt`, `nextEnum` etc., but it cannot decode "next JSON field that can be either a number, or a string, or a nested object". And `JsonElement` is unstructured by its nature. There is just no way to implement it.

It is in fact quite easy to do using forward declarations. At least for binary serialization. The same way you do with polymorphic serializaer. When you serialize a field, you first write field type which is one of primitives, array or node, then the payload itself. I've got it implemented for similar format [here](https://github.com/mipt-npm/dataforge-core/blob/master/dataforge-io/src/commonMain/kotlin/hep/dataforge/io/BinaryMetaFormat.kt). I am sure it could be done for ProtoBuf as well, because it supports recurrent structures. Basically if you can do maps and polymorphic, you can do Json.

**Comment by qwwdfsad** [comment] 2019-12-11 15:57
Consider you hit a breakpoint in the following method:
```
 override fun deserialize(decoder: Decoder) {
        val json = ???
    }
```

what methods of an arbitrary decoder do you expect are called?

**Comment by altavir** [comment] 2019-12-11 16:03
```kotlin
 override fun deserialize(decoder: Decoder) {
    val type = decoder.decodeInt()
    when(type){
        0 -> decodeNull()
        1 -> decodeValue()
        2 -> decodeNode()
    }
 }
```

In fact, here is [complete implementation](https://github.com/mipt-npm/dataforge-core/blob/dev/dataforge-io/src/commonMain/kotlin/hep/dataforge/io/serialization/MetaSerializer.kt), which works both for JSON and non-json serializers. Tested for Json and Cbor.

**Comment by qwwdfsad** [comment] 2019-12-11 16:11
This implementation implies that you know something about the format of the data being deserialized (e.g. that the very first element is **always** an int). Then it is, by definition, structured and has nothing to  do with an arbitrary JSON

**Comment by altavir** [comment] 2019-12-11 16:25
@qwwdfsad It seems like we are talking about different things. My request is not that we could transform key-value pairs in any representation into JsonObject. We ask for specific class `JsonObject` to have a representation in non-Json format. Basically you should be able to change serializer any time without breaking the code (but representation will change of course). Now, if you replace Json serializer with, say, Cbor, you will get runtime exception when serializing JsonObject.

**Comment by qwwdfsad** [comment] 2019-12-11 16:34
Okay, serializing is a bit different (not much easier though).
There are no problems in serializing an arbitrary `JsonElement`. The problem is, in fact, that you cannot deserialize it back.
We generally try to avoid entities that a one-way serializable, especially when this fact is not completely clear. 
E.g. it is not a problem for hashing, because no one is expecting for hash to be reversible into an original object.
But if one serialize an arbitrary `JsonObject` with CBOR, they probably expect it to be deserializable back, because you should know exactly the type of the `JsonElement`.

> The same way you do with polymorphic serializaer.

Well, yes, if one expects `JsonObject` like "{key: value, key2, null}" to be serialized as "{key: [kotlinx.serialization.json.JsonPrimitive, value], key2: [kotlinx.serialization.json.JsonNull, Unit]}", then it is manageable :)

**Comment by altavir** [comment] 2019-12-11 16:48
We can deserialize it back as long as we expect it in this format. If you look into my implementation, you will see that it checks both serializer and deserializer. It it is JsonInput/JsonOutput, it uses beutiful json. If not, it falls back to ugly forward declaration serializer. It means that it will correctly work for Json serializer and correctly work for non-json serializer, but not in the same way.

Event if there is a case, where there are two services communicating and one of them sends all messages in Json and gets all messages in Cbor, and the other one vise versa, it will still work because serializers and deserializers are compatible within one serialization type.

**Comment by sandwwraith** [comment] 2019-12-12 09:48
So basically you want something like that:

```kotlin
override fun deserialize(decoder: Decoder): JsonElement {
    if (decoder is JsonDecoder) {
        // decodes regular JSON
        return JsonElementSerializer.deserialize(decoder)
    } else {
        // decodes polymorphic structure like
        // ["kotlinx.serialization.json.JsonObject", {key: [kotlinx.serialization.json.JsonPrimitive, value]}]
        // from any binary format
        return JsonElementPolymorphicSerializer.deserialize(decoder)
    }
}
```

Well, it is possible, but it will likely work only with data serialized with kotlinx.serialization, because it is unlikely that any other framework will produce data in such a cumbersome format.

**Comment by altavir** [comment] 2019-12-12 11:22
Indeed. It will work only for kotlin-serialization. But the primary use-case is the transport between different multiplatform targets with kotlinx-serialization. In fact, for any more or less complex serialization, we rely on code sharing. For example, polymorphic serialization won't work outside kotlinx-serialization just because nobody else knows about our types. I do not think that it will be frequent use, but the case when serialization just fails in runtime is unacceptable.

**Comment by qwwdfsad** [comment] 2019-12-12 11:33
>but the case when serialization just fails in runtime is unacceptable.

It is debatable. It's more or less expected (and stated in the documentation), that `JsonElement` entities work only with JSON format. And serializing it as a polymorphic structure in, let's say, ProtoBuf **by default** doesn't look really sane.

If you need a format-agnostic unstructured data container, it is already here and is named `Map<String, Any>`. I don't think it is a good idea to implement proposed behaviour in JsonElement, especially taking into account that its use-cases are limited, and have a solution that doesn't look like a code-smell (and serializing `JsonObject` into protobuf, indeed, looks like one)

**Comment by sandwwraith** [comment] 2019-12-12 12:22
@qwwdfsad To be fair, our current recommendation is 'prefer JsonObject to Map<String, Any>' because the former is strictly-typed and doesn't involve any polymorphism. Also, `@Polymorphic Any` results in structures like `["kotlin.String", "foo"]` (also see #40)

**Comment by altavir** [comment] 2020-03-11 18:10
I would like to revisit the issue.  We have different serialization engines that support tree-like structure: JSON, XML, YAML and possibly even CBOR and other binary formats via type-length-value notation. They all are more or less isomorphic to JSON. I have several solutions to the problem, but the simplest way is to add additional level of abstraction to serial engine - add an intermediate class like TreeLikeSerialiEngine and make it accept JsonObject even if the output is not a json.

**Comment by qwwdfsad** [comment] 2020-03-12 08:23
Well, the fact that there are multiple formats with tree-like structure doesn't fix the conceptual problem.
After implementing support of `TreeLikeSerialiEngine` (with the only implementor `JsonDecoder` in this library), the next request will be "Json decoding using non TreeLikeSerialiEngine" and here we go again

**Comment by altavir** [comment] 2020-03-12 08:38
I do not agree. It is quite obvious that different backends have different capabilities. Object serialization could request those capabilities (it even could be checked in compile-time by the plugin). In order to serialize JsonObject, you do not have to use JsonOutput, it should just be able to handle primitives, map-like structures and arrays.

I think it is important to abstract those capabilities because we can later emulate them and add to existing backents. For example map-like serializer needed for Json could be emulated in protobuf by type-value notation. For custom backends it is even more important, because it allows to disentangle them from the current serialization version.

**Comment by InsanusMokrassar** [comment] 2020-03-12 08:48
For of that, as a result in most cases we are getting objects, which are tree-like structures

**Comment by qwwdfsad** [comment] 2020-03-12 09:49
Yes, and values of these objects can still be either primitives or nested objects.
I've already described it above (https://github.com/Kotlin/kotlinx.serialization/issues/615#issuecomment-564563279) why it is impossible to do with no json-specific decoder and why it works for a json-specific ones.

It is not the matter of "we don't want to allow to deserialize JsonElement with a non-JsonInput decoder", it is just impossible for an arbitrary `JsonElement`

**Comment by qwwdfsad** [comment] 2020-08-17 10:59
Closing as won't fix

**Closed by qwwdfsad** 2020-08-17 10:59 UTC
Labels: feature, json
