### ISSUE TITLE
Provide `encodeToByteArray` function for `StringFormat`

### ISSUE THREAD

**Issue by solonovamax** [Kotlin/kotlinx.serialization#2872] opened 2024-12-04 21:00 UTC
**What is your use-case and why do you need this feature?**
There are sometimes scenarios where you need a `ByteArray` representation of a format that inherits from `StringFormat`.
In my specific usecase: sending the encoded contents of some object as a `ByteArray` using ktor.

Currently an `encodeToByteArray` is provided for the `BinaryFormat`s, however not for any `StringFormat`s.

It would be convenient to have a function that returns the equivalent of `StringFormat.encodeToString(value: T).toByteArray(Charsets.UTF_8)`/`StringFormat.encodeToString(serializer: SerializationStrategy<T>, value: T).toByteArray(Charsets.UTF_8)`, rather than having to do (for example):
```kotlin
JSON.encodeToString(myValue).toByteArray(Charsets.UTF_8)
```

**Describe the solution you'd like**
Providing a `StringFormat.encodeToByteArray(value: T): ByteArray` and a `StringFormat.encodeToByteArray(serializer: SerializationStrategy<T>, value: T): ByteArray` function which both return a byte array representing the `value` as a string encoded in UTF-8.

**Comment by pdvrieze** [comment] 2024-12-05 10:22
@solonovamax The challenge is that this would need to deal with encoding. So the implementation would still need to encode to a string and then convert it to a byte array for the specific encoding. Strings also have a `getBytes` function on the JVM (which handles charsets and does the smart thing for utf8 if the string is actually stored as that).
A more efficient approach would use (an equivalent of) `OutputStreamWriter` and an `encodeToWriter` function, which does require a cross-platform `Writer` interface (the challenge here again being to do the encoding - there is no cross-platform solution for non-utf encodings).

**Comment by sandwwraith** [comment] 2024-12-05 13:14
Duplicate of #251. We currently have no such plans, because making additional call is not that hard. Yet we may return to them in the future.

**Closed by sandwwraith** 2024-12-05 13:14 UTC
Labels: feature
