### ISSUE TITLE
typealiased @Serializable cannot be used as type hints

### ISSUE THREAD

**Issue by jooohn** [Kotlin/kotlinx.serialization#2737] opened 2024-07-03 01:27 UTC
**Describe the bug**

When `@Serializable` is annotated to std lib class using typealias, it fails to find Serializer when it's given as type hint for functions like `Json.encodeToString. It was working when I use Kotlin 1.9.24 and kotlinx-serialization-json:1.6.3.

**To Reproduce**

```kotlin
package org.example

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encodeToString
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.json.Json
import java.util.TimeZone

fun main() {
    // This works.
    val timeZone = TimeZone.getDefault()
    val wrapper = Wrapper(timeZone)
    println(Json.encodeToString(wrapper))

    // This doesn't work - 
    // Exception in thread "main" kotlinx.serialization.SerializationException: Serializer for class 'TimeZone' is not found.
    // Please ensure that class is marked as '@Serializable' and that the serialization compiler plugin is applied.
    val serializedTimeZone: SerializableTimeZone = timeZone
    val converted1 = Json.encodeToString(serializedTimeZone)
    println("Converted1: $converted1")

    // This doesn't work too.
    val converted2 = Json.encodeToString<@Serializable(with = TimeZoneSerializer::class) TimeZone>(timeZone)
    println("Converted2: $converted2")
}

typealias SerializableTimeZone =
    @Serializable(with = TimeZoneSerializer::class)
    TimeZone

object TimeZoneSerializer : KSerializer<TimeZone> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("TimeZone", PrimitiveKind.STRING)

    override fun deserialize(decoder: Decoder): TimeZone =
        TimeZone.getTimeZone(decoder.decodeString())

    override fun serialize(encoder: Encoder, value: TimeZone) {
        encoder.encodeString(value.id)
    }
}

@Serializable
data class Wrapper(val value: SerializableTimeZone)
```

**Expected behavior**

**Environment**
 - Kotlin version: 2.0.0
 - Library version: 1.7.1
 - Kotlin platforms: JVM
 - Gradle version: 8.5

**Comment by sandwwraith** [comment] 2024-07-05 12:32
Duplicate of #2731. See also https://youtrack.jetbrains.com/issue/KT-67252 and https://youtrack.jetbrains.com/issue/KT-64920 for detailed explanation

**Closed by sandwwraith** 2024-07-05 12:32 UTC
