### ISSUE TITLE
Option to include class discriminator as property in class

### ISSUE THREAD

**Issue by ankushg** [Kotlin/kotlinx.serialization#1762] opened 2021-11-16 22:19 UTC
Is it possible to include the class discriminator as a property on the class, rather than having it required in JSON but invisible from Kotlin?

something like:
```kt
@Serializable
@JsonClassDiscriminator("projectType")
sealed class Project {
    abstract val name: String

    // somehow generated: 
    val projectType: String
}

@Serializable         
@SerialName("owned")
class OwnedProject(override val name: String, val owner: String) : Project()
```

**Comment by sandwwraith** [comment] 2021-11-17 11:27
Duplicate of #1664

**Closed by sandwwraith** 2021-11-17 11:27 UTC
Labels: feature
