### ISSUE TITLE
Getting the serialName of a @Serializable data class's property by its KProperty referenve

### ISSUE THREAD

**Issue by cies** [Kotlin/kotlinx.serialization#1886] opened 2022-03-23 18:54 UTC
Say I have a data class named `MyDto` with one property `id` and I want to know the serialName of this `id` property I can use: `MyDto.serializer().descriptor.getElementName(1)`.

But I prefer to get it like this `MyDto.serializer().descriptor.getSeriaNameOf(MyDto::id)` or even  `MyDto.serializer().descriptor[MyDto::id]` or  `Json.serialNameOf(MyDto::id)` or something like `MyDto::id.serialName()`, so I wont tie my code up to the property indexes.

Is something like this even possible?

Would you accept a PR for this?
If yes, which style(s) do you prefer?

**Comment by pdvrieze** [comment] 2022-03-24 13:53
@cies Unfortunately what you ask for isn't really possible with the current version of the compiler plugin. The way that serial descriptors (and `@SerialName`) works is that this the serial name is associated with the property index. The serializer for that type will be the place that links an actual field with the index, and only in the code. The `@SerialName` annotation is not visible either.

There are some places that could go with the implementation, like a compiler (plugin) intrinsic, but that wouldn't work with a dynamic property reference.

It would probably be helpful if you could explain what the reason for the feature request is.

**Comment by cies** [comment] 2022-03-28 12:17
> explain what the reason for the feature request is.

Say I have a serialName on my DTO that results in a string in a JSON object referring to a value.

Say this JSON object is for a form submission. I have to give the name attribute to HTML input elements so it works with the DTO. If I just put the name there as string it is more brittle than referring to the serialName.

**Comment by sandwwraith** [comment] 2022-03-28 12:41
I think this is a duplicate of #1738. Unfortunately, since `KProperty` does not provide the index of property inside class, it is now not possible to provide such an API.

**Closed by sandwwraith** 2022-03-28 12:41 UTC
Labels: feature

**Comment by cies** [comment] 2022-04-11 12:44
Fair enough.
