### ISSUE TITLE
Super-Interface implementation isn't taken into account when generating serializer

### ISSUE THREAD

**Issue by molikuner** [Kotlin/kotlinx.serialization#636] opened 2019-12-23 16:49 UTC
**Describe the bug**

The `@Serializable`/`@Serializer` annotation generates a function even though a super-interface of the companion object already implemented one.

**To Reproduce**
given following code:
```Kotlin
/*  1. */ class TestSerialization {
/*  2. */     @Test
/*  3. */     fun `simple TestClass serialization test`() {
/*  4. */         val json = "\"test\""
/*  5. */         val parsed = Json.parse(TestClass.Companion, json)
/*  6. */         assertEquals(
/*  7. */             TestClass("test"),
/*  8. */             parsed
/*  9. */         )
/* 10. */     }
/* 11. */ }
/* 12. */
/* 13. */ @Serializable(with = TestClass.Companion::class)
/* 14. */ data class TestClass(val a: String) {
/* 15. */     @Serializer(forClass = TestClass::class)
/* 16. */     companion object : TestSerializer {
/* 17. */         override val descriptor: SerialDescriptor = StringDescriptor
/* 18. */
/* 19. */         // when removing this function the compiler will generate one...
/* 20. */         override fun deserialize(decoder: Decoder): TestClass {
/* 21. */             return super.deserialize(decoder)
/* 22. */         }
/* 23. */
/* 24. */         override fun serialize(encoder: Encoder, obj: TestClass) = encoder.encodeString(obj.a)
/* 25. */     }
/* 26. */ }
/* 27. */
/* 28. */ interface TestSerializer: KSerializer<TestClass> {
/* 29. */     override fun deserialize(decoder: Decoder): TestClass {
/* 30. */         return TestClass(decoder.decodeString())
/* 31. */     }
/* 32. */ }
```
When removing the function in line 20, I get the following error, which is caused by the compiler plugin falsely generating a function even though there is already one:

```log
> Task :jvmTest FAILED

Invalid JSON at 0: Expected '{, kind: CLASS'
kotlinx.serialization.json.JsonDecodingException: Invalid JSON at 0: Expected '{, kind: CLASS'
	at kotlinx.serialization.json.internal.JsonReader.fail(JsonReader.kt:293)
	at kotlinx.serialization.json.internal.StreamingJsonInput.beginStructure(StreamingJsonInput.kt:39)
	at com.molikuner.TestClass$Companion.deserialize(TestSerialization.kt)
	at com.molikuner.TestClass$Companion.deserialize(TestSerialization.kt:32)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:34)
	at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:33)
	at kotlinx.serialization.CoreKt.decode(Core.kt:80)
	at kotlinx.serialization.json.Json.parse(Json.kt:126)
	at kotlinx.serialization.json.Json$Companion.parse(Json.kt:178)
	at com.molikuner.TestSerialization.simple TestClass serialization test(TestSerialization.kt:19)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.base/java.lang.Thread.run(Thread.java:834)

com.molikuner.TestSerialization > simple TestClass serialization test FAILED
    kotlinx.serialization.json.JsonDecodingException at TestSerialization.kt:19
```

**Expected behavior**

The compiler plugin doesn't generate a function, because there is one already.

**Environment**
 - Kotlin version: `1.3.61`
 - Library version: `0.14.0`
 - Kotlin platforms: tested on `JVM`, but code is in common
 - Gradle version: `5.5.1`

**Comment by sandwwraith** [comment] 2020-01-14 13:11
Duplicate of #154 ?

**Comment by molikuner** [comment] 2020-01-16 08:38
@sandwwraith Sorry, looks like I missed the other issue. In defense, they aren't talking about interfaces. They just talk about (abstract) classes, but if you think that this issue would be fixed by fixing the other issue, feel free to close this. I'm also following the other issue now.

**Closed** 2020-07-22 17:02 UTC
