### ISSUE TITLE
0.8.2-rc13 and iOS: error: unresolved reference: serializer

### ISSUE THREAD

**Issue by yuriry** [Kotlin/kotlinx.serialization#231] opened 2018-10-06 00:35 UTC
After migrating from ```0.8.1-rc13``` to ```0.8.2-rc13``` compiling iOS project fails with the following error:
```
> Task :ios:compileDebugIos_arm64KotlinNative
common/src/main/kotlin/com/**/Foo.kt:159:76: error: unresolved reference: serializer
        fun parse(jsonText: String): Foo = JSON.nonstrict.parse(serializer(), jsonText)
                                                                           ^

> Task :ios:compileDebugIos_arm64KotlinNative FAILED
```
Common and Android sub-projects build fine.

When I remove ```serializer()``` call to make it like this
```kotlin
fun parse(jsonText: String): Foo = JSON.nonstrict.parse(jsonText)
```
the iOS project builds, but I'm getting the same error at runtime I was [getting earlier](https://github.com/Kotlin/kotlinx.serialization/issues/225#issue-364738500) when not passing serializer as the first argument.

The error above occurs when using either ```ext.kotlin_version = '1.3.0-rc-131'``` or ```ext.kotlin_version = '1.3.0-rc-146'```.  My current list of dependencies is:
```gradle
buildscript {
    ext.kotlin_version = '1.3.0-rc-146'
    ext.kotlinPluginUrl = "https://dl.bintray.com/kotlin/kotlin-eap"
    ext.kotlinPluginClassPath = "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    
    ext.kotlinNativeUrl = "https://dl.bintray.com/jetbrains/kotlin-native-dependencies"
    ext.kotlin_native_version = '1.3.0-rc-146'
    ext.kotlinNativeClassPath = "org.jetbrains.kotlin:kotlin-native-gradle-plugin:$kotlin_native_version"
    
    ext.serializationUrl = "https://kotlin.bintray.com/kotlinx"
    ext.serialization_version = '0.8.2-rc13'
    ext.serializationClasspath = "org.jetbrains.kotlin:kotlin-serialization:$kotlin_version"

    ext.android_gradle_version = '3.2.0'
    ext.androidGradleClassPath = "com.android.tools.build:gradle:$android_gradle_version"
}
```

Any help would be greatly appreciated!

**Comment by sandwwraith** [comment] 2018-10-08 10:05
It looks like the plugin hasn't been applied to the compiler. Do you use `kotlin-platform-native`? How do you connect plugin with the compiler?

**Comment by yuriry** [comment] 2018-10-10 02:00
@sandwwraith  
I do use ```'kotlin-platform-native'```

This is the top part of my **iOS sub-projecct**
```gradle
buildscript {
    repositories {
        jcenter()
        maven { url kotlinPluginUrl }
        maven { url kotlinNativeUrl }
    }
    dependencies {
        classpath kotlinPluginClassPath
        classpath kotlinNativeClassPath
        classpath serializationClasspath
    }
}

apply plugin: 'kotlin-platform-native'
apply plugin: 'kotlinx-serialization'

repositories {
    jcenter()
    maven { url kotlinPluginUrl }
    maven { url serializationUrl }
}
```

My **top-level** configuration that does not work with this **iOS sub-project** is in [my original post](https://github.com/Kotlin/kotlinx.serialization/issues/231#issue-367406589)

The **top-level** configuration that works with this **iOS sub-project** is this:
```gradle
buildscript {
    ext.kotlin_version = '1.3.0-rc-57'
    ext.kotlinPluginUrl = "https://dl.bintray.com/kotlin/kotlin-eap"
    ext.kotlinPluginClassPath = "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    
    ext.kotlinNativeUrl = "https://dl.bintray.com/jetbrains/kotlin-native-dependencies"
    ext.kotlin_native_version = '0.9.2'
    ext.kotlinNativeClassPath = "org.jetbrains.kotlin:kotlin-native-gradle-plugin:$kotlin_native_version"
    
    ext.serializationUrl = "https://kotlin.bintray.com/kotlinx"
    ext.serialization_version = '0.8.1-rc13'
    ext.serializationClasspath = "org.jetbrains.kotlin:kotlin-serialization:$kotlin_version"

    ext.android_gradle_version = '3.2.0'
    ext.androidGradleClassPath = "com.android.tools.build:gradle:$android_gradle_version"
}
```

For my working **iOS sub-project** I use ```mavenLocal()``` instead of ```maven { url serializationUrl }```, and the commit that is used to publish serialization library locally is [7a7ebe94afdc930e751af9c095edb0c5fc8338a8](https://github.com/Kotlin/kotlinx.serialization/commit/7a7ebe94afdc930e751af9c095edb0c5fc8338a8) (to workaround [the main thread related problem](https://github.com/Kotlin/kotlinx.serialization/issues/225))

As soon as I switch to ```ext.serialization_version = '0.8.2-rc13'```, I get [compiler version problem](https://github.com/Kotlin/kotlinx.serialization/issues/230) (either with ```maven { url serializationUrl }``` or with ```mavenLocal()``` in my iOS sub-project).  But when I upgrade the kotlin_version to ```1.3.0-rc-131``` or ```1.3.0-rc-146``` I get this problem.  

I'm not sure why the plugin hasn't been applied to the compiler.  The only thing I did to run into the problem is to upgrade to serialization  to ```'0.8.2-rc13'``` and to bump up kotlin_version to ```1.3.0-rc-146```.

**Comment by yuriry** [comment] 2018-10-10 23:03
@sandwwraith 
I created [a test project](https://github.com/yuriry/SerializationCompilationiOS) that reproduces the problem, could you please take a look? The line that fails to compile is [in Foo.kt](https://github.com/yuriry/SerializationCompilationiOS/blob/102ee50c9bb38d4eda8b82270a8d9a0c7d9185c6/common/src/main/kotlin/org/example/serialization/Foo.kt#L12)

If you change the version information in ```gradle.properties``` to
```
kotlin_version=1.3.0-rc-57
kotlin_native_version=0.9.2
serialization_version=0.8.1-rc13
android_gradle_version=3.2.0
``` 
the compilation succeeds.

Please let me know if you need more information.

**Comment by sandwwraith** [comment] 2018-10-12 11:34
@yuriry Yes, it reproduces the problem and I'm investigating it

**Comment by sandwwraith** [comment] 2018-10-12 11:51
It seems that the last release of Kotlin/Native gradle plugin for some reason does not add `-XPlugin` option to compiler. For a workaround, you can pass it manually, as here: https://github.com/sandwwraith/KotlinSerializationPlayground/blob/native_preview/native/build.gradle#L49

**Comment by yuriry** [comment] 2018-10-13 15:12
@sandwwraith Thank you for the workaround, it works!

**Comment by sandwwraith** [comment] 2018-10-16 09:49
Ok, so as explained in the linked issue, `kotlin-platform-native` now shades kotlin plugin inside, so all compiler plugins are also shaded and have different ids. To use the plugin with k/n 0.9.3 and library 0.8.2, use line `apply plugin: 'kotlinx-serialization-native'` in native modules. (this is applicable only to `kotlin-platform-native`, `kotlin-multiplatform` works as usual). I've updated the docs: https://github.com/Kotlin/kotlinx.serialization/commit/4ae3d34a05616d6542eca2b88afc7e30f9a0d9b6

I'm closing this now since it is a problem in K/N which has [separate ticket](https://youtrack.jetbrains.com/issue/KT-27581).

**Closed by sandwwraith** 2018-10-16 09:49 UTC
Labels: bug

**Comment by tttzof351** [comment] 2018-11-15 01:57
Same question, but my project structure without build.gradle in ios project like https://github.com/JetBrains/kotlin-examples/tree/master/tutorials/mpp-iOS-Android

So, how I can pass -XPlugin for this situation ?

**Comment by sandwwraith** [comment] 2018-11-19 08:48
For `kotlin-multiplatform` plugin you can use usual `apply plugin: 'kotlinx-serialization'` line

**Comment by sandwwraith** [comment] 2018-11-19 10:16
@tttzof351 Or maybe https://github.com/Kotlin/kotlinx.serialization/issues/264#issuecomment-439840968 would help you?
