### ISSUE TITLE
Give me a chance, get current deserialization path

### ISSUE THREAD

**Issue by iseki0** [Kotlin/kotlinx.serialization#2875] opened 2024-12-06 11:08 UTC
**What is your use-case and why do you need this feature?**
I found the official format, JSON could provide JSON Path in exception message when deserialization failed.
But current implementation don't allow customized deserializer get the message, and it also doesn't provide path message when the customized deserializer throws.

**Describe the solution you'd like**
Give me a method, or modify the thrown `SerializationException`. Provide deserialization path information(such as JSON Path) when deserialization failed.

**Comment by iseki0** [comment] 2024-12-06 17:00
Yes. In many JSON exceptions, we can get JSON path & part of the data chunk. It's useful in many cases. @pdvrieze

**Comment by sandwwraith** [comment] 2024-12-09 11:32
Correct me if I'm wrong, but this is a duplicate of #2165

**Closed by sandwwraith** 2024-12-09 11:32 UTC
Labels: feature
