### ISSUE TITLE
Support generating JSON schemas for serializable classes

### ISSUE THREAD

**Issue by natanfudge** [Kotlin/kotlinx.serialization#2432] opened 2023-09-06 06:17 UTC
This is the current process of interfacing a Kotlin server with a non-Kotlin client (or vice versa):

1. Write Kotlin models using sealed/data classes and `@Serializable` annotations. 
2. By hand, go over every model class, and rewrite it for your non-Kotlin client. (And hope you didn't miss anything or misspell something) 
3. Make changes to your Kotlin models as required.
4. On every change, reflect those changes on the non-Kotlin client. (And hope you don't forget to do this)

To improve this, I propose Kotlinx.serialization exposed a method that produces a JSON schema for serializable classes:
```kotlin
val schema = JsonSchemaGenerator.generateSchemaText(MyClass.serializer().descriptor) 
Paths.get("mySchema.json").writeText(schema)
```

And then the non-Kotlin client side may simply import this file (Typescript example)
```typescript
compileFromFile('mySchema.json')
  .then(ts => fs.writeFileSync('mySchema.d.ts', ts))
```

And now the process becomes much easier:

1. Write Kotlin models using sealed/data classes and `@Serializable` annotations. 
2. Make changes to your Kotlin models as required.

And changes are reflected automatically everywhere else. 

This feature is supported by [Jackson](https://github.com/FasterXML/jackson-module-jsonSchema) and experimentally supported here [for Protobuf](https://kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-protobuf/kotlinx.serialization.protobuf.schema/-proto-buf-schema-generator/).

**Comment by sandwwraith** [comment] 2023-09-11 12:07
Duplicate of #1115. There's even a 3rd party prototype mentioned [here](https://github.com/Kotlin/kotlinx.serialization/issues/1115#issuecomment-1279713437)

**Closed by sandwwraith** 2023-09-11 12:07 UTC
Labels: feature
