### ISSUE TITLE
Cross module serialization problems (JS)

### ISSUE THREAD

**Issue by czeidlertest** [Kotlin/kotlinx.serialization#166] opened 2018-07-05 09:12 UTC
The following setup:

1) a common module with a Data class:
`class Data(val a: Int)`
3) a libJS module that depends on the common module with a class:
`class LocalBox(val value: Data)`

When serializing LocalBox in JS it results in:
`{"value":"[object Object]"}`

This works fine in JVM and I only encountered this problem after upgrading from 0.4.2 to 0.5.1

I create a demo here:
https://gitlab.com/czeidler/boxbug
(see the test in libJS)

**Comment by sandwwraith** [comment] 2018-07-05 09:13
Isn't this a duplicate of #165 ?

**Comment by czeidler** [comment] 2018-07-05 09:15
No its a new one

**Comment by sandwwraith** [comment] 2018-07-05 09:16
Sorry, first time I pointed to a wrong issue. Now my comment edited and correct.

**Comment by czeidler** [comment] 2018-07-05 09:24
Yes it looks very similar. In #153 they use a data class and I also have seen that data classes are serialized as strings. I bet if you remove the data qualifier from the class it would result in:
`{"kdate":"[object Object]"}`
as it does in my case.

 However, I didn't encountered the problem in JVM. I could check if you think its helpful.

**Comment by sandwwraith** [comment] 2018-07-13 14:14
After short investigation, I've found that this problem was resolved alongside with #153

**Closed by sandwwraith** 2018-07-13 14:14 UTC
Labels: bug
