### ISSUE TITLE
Option to not write optional values

### ISSUE THREAD

**Issue by czeidler** [Kotlin/kotlinx.serialization#58] opened 2017-12-15 20:22 UTC
Is it possible to add an option to not write optional values?

For example, either if in nonstrict mode or add an parameter to `@Optional`. Something like:

`@Optional(dontwritewhen=2) val value: Int = 2`

or

`@Optional(writedefault=false) val value: Int = 2`

**Comment by sandwwraith** [comment] 2017-12-18 19:57
So, did I understand you correctly? Given some class

```kotlin
@Serializable
class Data(@Optional(writedefault=false) val value: Int = 2)
```

you expect `JSON.stringify(Data(3))` be `{value: 3}` and `JSON.stringify(Data(2))` be `{}`?
Basically, you try to save space in output stream by omitting values with defaults

**Comment by czeidler** [comment] 2017-12-18 20:36
Yes that is correct. Maybe a better usecase is this one:

```
@Serializable
class(val value: Int, @Optional val optionalData: OptionalData? = null)
```
If optionalData is null you don't really want to have `optionalData:null` in your JSON output. It might even causes problems for other external JSON parsing code that expect a JSON object or nothing but not a null value.

Another usecase is that you may want to read optional values but never write them (e.g. because they are deprecated)

**Comment by elizarov** [comment] 2017-12-19 07:01
I wonder if that shall be a feature of the serializable class or a feature of the format? Does it make sense to automatically support elision of default values when _both_ the class has _eligible_ defaults (I'm thinking about compile-time constants and defaults here) and the format supports it?

**Comment by czeidler** [comment] 2017-12-21 03:51
What do you mean with format? json, protobuffer, cbor? Think it depends on the use-case so IMHO it should be configurable.

**Comment by rocketraman** [comment] 2018-05-16 00:01
I am commenting here so I can easily find this issue again in the future, [since I can't do that by subscribing alone](https://github.com/isaacs/github/issues/283).

**Comment by abissell** [comment] 2018-05-25 06:44
A major use-case for this is implementing the [JSON-RPC spec](http://www.jsonrpc.org/specification). On the Request object, the spec says the `params` member "MAY be omitted." This would map most cleanly to a nullable Kotlin field, but without the ability to omit optional values it will write out `params: null`, which violates the spec.

Anyway, I know this is a feature under active development, just wanted to point out one more use case. :)

**Comment by pdvrieze** [comment] 2018-06-05 09:57
My major question is what the intended semantics of optional are. Currently it means "may be missing in the input", but will always be written. It may be possible to just have a switch that specifies the semantics (eg. omit_if_null, omit_if_default_value, never_omit, omit_if_tag). That would really benefit from default value support in annotations.

omit_if_tag would allow a tag to be set on the session (like that it is in compat mode) that can then be checked for individual fields without requiring custom serialization.

Implementation is easy if this information is available in some form to the serializer.

**Comment by coder82** [comment] 2018-06-05 15:44
I have to vote for this, saves bandwidth when we serialize!

**Comment by SapuSeven** [comment] 2018-09-20 11:34
Any news on this feature?

**Comment by sandwwraith** [comment] 2018-09-20 14:57
New framework design contains solution for this problem: https://github.com/Kotlin/KEEP/blob/serialization/proposals/extensions/serialization.md#optionality

**Comment by GoMino** [comment] 2018-10-25 12:20
@sandwwraith can you provide an exemple on how we can use the CompositeEncoder to not write optional value ? 

Can't to find any docs on this :(

**Comment by GoMino** [comment] 2018-10-25 12:38
@sandwwraith thanks, is it compatible with kotlin Native and JS ?

**Comment by sandwwraith** [comment] 2018-10-25 13:00
Yes, these are multiplatform interfaces

**Comment by InsanusMokrassar** [comment] 2018-11-13 00:33
> @GoMino for now, workaround would be to write code like this: https://github.com/Kotlin/kotlinx.serialization/blob/eap13/runtime/common/src/test/kotlin/kotlinx/serialization/CustomSerializersTest.kt#L67

Hello

What if I need to skip. for example, `null`s on serialization process in very huge count of data classes?

**Comment by pdvrieze** [comment] 2018-11-15 09:23
@InsanusMokrassar Currently you are probably best of creating a custom encoder that does this in a way configured by that encoder (using annotations, a hardcoded list, initialisation of the encoder, etc.)

**Comment by davidbrazilparker** [comment] 2018-11-27 19:15
So there's a possible fix for this that I found which is kind of hacky but will resolve this for Kotlin data classes.

Here's an example of a data class that I serialize which has an optional serializable parameter:
```
@Serializable
data class Result( @Optional @SerialName("status_id") var statusId: Int? = null)
```

Currently with how the Kotlinx serialization library is written we write to our JSON map the value of `null` as a Kotlin String `"null"`.

So for the example above the resulting JSON object would look as follows:
```
{
    "status_id":null
}
```

Cool so this will mean I'm not going to change this value when I POST this payload right? NOPE

`null` is not a valid JSON object value for the API I'm sending POST requests to. Now I'll admit I don't have much experience with API's (I'm learning 🤓). But for my use case in particular this a huge issue. Now for what I think could be the solution.

In the following file: 
https://github.com/Kotlin/kotlinx.serialization/blob/master/runtime/common/src/main/kotlin/kotlinx/serialization/json/JsonParser.kt#L23

Change this line:

`internal const val NULL = "null"`

to

`internal const val NULL = ""`

Why? JSON treats the empty string, `""`, value as a null value. What this means is that if we set a value as `""` we won't be changing that value when we POST the JSON payload.

The goal of this is so our Data Class Serialized as JSON will look like this instead:

```
{
    "status_id":""
}
```

I'm not saying this is going to cover all use cases but for my purposes and the issues I've run into, I think this is a simple solution to a problem that's been causing me plenty of headaches.

**Comment by InsanusMokrassar** [comment] 2018-11-28 04:00
@davidbrazilparker so, you offer to change output of `JSON#stringify` from

```JSON
{"output": null}
```

to

```JSON
{"output": ""}
```

Is it right? I don't think that this solve better in case of skipping some values (like null) at least for the reason that it is not obviously enough. If to talk conversation topic: it is absolutely opposite to the main idea: skip fields serialization in some cases.

**Comment by davidbrazilparker** [comment] 2018-12-03 18:41
Yeah my mistake sorry guys 😛

**Comment by raderio** [comment] 2018-12-29 09:11
In Jackson you can use
`@JsonInclude(Include.NON_NULL)`
https://www.baeldung.com/jackson-ignore-null-fields

**Comment by raderio** [comment] 2018-12-29 09:33
@InsanusMokrassar it is an example how this is done in Jackson, maybe will be good reference in implementation this here.

**Comment by InsanusMokrassar** [comment] 2018-12-29 09:35
@raderio Excuse me, I see

**Comment by sandwwraith** [comment] 2019-01-24 13:17
Starting from `0.10.0` and Kotlin `1.3.20`, both library and plugin support this feature according to design described in [KEEP](https://github.com/Kotlin/KEEP/blob/master/proposals/extensions/serialization.md#optionality). 

You can create an instance of Json class with the corresponding setting: `Json(encodeDefaults = false)` to skip default values during serialization.

**Closed by sandwwraith** 2019-01-24 13:17 UTC
Labels: feature

**Comment by Egorand** [comment] 2019-03-04 22:21
Is there a similar solution for configuring `ProtoBuf` to skip optional values?

**Comment by jpink** [comment] 2019-04-04 12:52
@sandwwraith I see this as a major **ProtoBuf** issue, because the protocol doesn't know NULL.

And you give `Json(encodeDefaults = false)` as a workaround where the issue isn't showstopper.

**Comment by sandwwraith** [comment] 2019-04-04 13:13
@jpink There's a separate issue for it: #71

**Comment by valeriyo** [comment] 2020-04-03 18:04
I'm sorry, but `Json(encodeDefaults = false)` is not sufficient. I have a bunch of hardcoded values in my request classes like this:
```
@Serializable
class DoSomethingRequest(
  @SerialName("data") val data: String?
) {
  @SerialName("source") val source = "android"
}
```
As soon as I enable `encodeDefaults = false` -- the `source` field will disappear from the input. I would like a more precise control of optionality, per field.
