### ISSUE TITLE
Serializable(with Class) should be the same class at compile time 

### ISSUE THREAD

**Issue by hfhbd** [Kotlin/kotlinx.serialization#845] opened 2020-05-27 14:46 UTC
**Describe the bug**
Currently, with the annotation @Serializable(with: KClass) there is no validation at compile matching the custom serializer to the (custom) type. Instead, the serializer throws a ClassCast exception.

**To Reproduce**
```
@Serializable
data class Foo(@Serializable(with = BazSerializer::class) val i: Bar)

class Bar
@Serializer(forClass = Bar::class)
object BarSerializer: KSerializer<Bar>

class Baz
@Serializer(forClass = Baz::class)
object BazSerializer: KSerializer<Baz>
````
**Current behavior**
A runtime error: java.lang.ClassCastException: class Baz cannot be cast to class Bar

**Expected behavior**
A compiler error: BazSerializer (for type Baz) is not subtype of Bar for member i

**Environment**
 - Kotlin version:  1.3.72
 - Library version: 0.20.0
 - Kotlin platforms: JVM
 - Gradle version: 6.4.0
 - IDE version: IntellijIDEA Community 2020.1.1
 - Other relevant context: Windows 10 1809, JDK version: OpenJDK 14.0.1

**Comment by sandwwraith** [comment] 2020-06-01 16:33
Also, #830

**Comment by sandwwraith** [comment] 2020-09-08 16:35
Actually, duplicate of #830

**Closed by sandwwraith** 2020-09-08 16:35 UTC
Labels: bug, compiler-plugin
