### ISSUE TITLE
Bring `classDiscriminator` from context to base class level to support fine-grained polymorphic serialization

### ISSUE THREAD

**Issue by pmiklos** [Kotlin/kotlinx.serialization#1002] opened 2020-08-22 19:47 UTC
**What is your use-case and why do you need this feature?**

APIs aren't always designed optimally especially when it comes to polymorphic data structures. The external API that I am trying to map with Kotlin Serialization has several different ways of representing polymorphic types:
* `["justsaying",{"subject":"exchange_rates","body":{"BTC_USD":9244.66929639}}]`
* `["request",{"command":"light/get_definition","params":"2GPBEZTAXKWEXMWCTGZALIZDNWS5B3V7"}] `
* and a couple others within request body and params types. 

Currently we can only control the built-in polymorphic serializer by configuring the context which is a generic setting, but it would be great if the representation of polymorphic discriminators could be controlled in a more fine-grained way. It would add a great flexibility and it seems to fit the current design.

**Describe the solution you'd like**

I could imagine having a class level `@Polymorphic(discriminator="command")` construct that would tell the polymorphic serializer to use `command` element of the polymorphic type to find sub-classes. 

Alternatively, it could probably also be implemented as part of the SerialModule: `polymorphic("command", Message::class) { ... }`  or similar.

**Comment by sandwwraith** [comment] 2020-08-27 15:34
Duplicate of #546  ?

**Comment by pmiklos** [comment] 2020-08-28 04:47
Indeed, that one seems to describe the exact same need.

**Closed** 2020-08-31 13:55 UTC
Labels: duplicate, feature
