### ISSUE TITLE
Keep annotations with objects

### ISSUE THREAD

**Issue by GitAntoinee** [Kotlin/kotlinx.serialization#1525] opened 2021-05-30 12:48 UTC
**Describe the bug**
At runtime, the annotations are not kept in the serializer

**To Reproduce**
```kotlin
annotation class ExampleAnnotation

@ExampleAnnotation
@Serializable
object Example

fun main() {
    // Missing annotation
    val annotation = Example.serializer().descriptor.annotations.first<ExampleAnnotation>
}
```

**Expected behavior**
The annotations should be in the descriptor

**Environment**
 - Kotlin version: 1.5.10
 - Library version: 1.2.1
 - Kotlin platforms: JVM
 - Gradle version: 7.0.2
 - IDE version (if bug is related to the IDE) [e.g. IntellijIDEA 2019.1, Android Studio 3.4]: IntelliJ IDEA
 - Other relevant context [e.g. OS version, JRE version, ... ]: Linux x64, OpenJDK 15

**Comment by sandwwraith** [comment] 2021-05-31 09:56
The annotation should be marked with `@SerialInfo` to be included in the serial descriptor. Anyway, it's a duplicate of #708

**Closed by sandwwraith** 2021-05-31 09:56 UTC
