### ISSUE TITLE
JsonArrayBuilder's unaryPlus extensions don't work for Number?

### ISSUE THREAD

**Issue by jcayzac** [Kotlin/kotlinx.serialization#418] opened 2019-03-26 09:43 UTC
Using `kotlinx-serialization-runtime:0.10.0` the following code produces an empty array:

```kt
jsonArray {
    +2
    +4
    +6
    +8
}
```

Being more verbose works as expected:

```kt
jsonArray {
    +JsonPrimitive(2)
    +JsonPrimitive(4)
    +JsonPrimitive(6)
    +JsonPrimitive(8)
}
```

It seems that https://github.com/Kotlin/kotlinx.serialization/blob/master/runtime/common/src/test/kotlin/kotlinx/serialization/json/serializers/JsonArraySerializerTest.kt lacks tests for the the `unaryPlus` overloads defined in `JsonArrayBuilder`, maybe.

**Comment by jcayzac** [comment] 2019-03-26 09:57
The overload for `String?` works, this returns an array of size `3`:

```kt
jsonArray {
    +"foo"
    +"bar"
    +"baz"
}
```

**Comment by jcayzac** [comment] 2019-03-26 10:03
I ended up using `JsonArray(listOf(2, 4, 6, 8).map(::JsonPrimitive))` for now…

**Comment by q-litzler** [comment] 2019-03-26 10:48
```kotlin
jsonArray {
  +(1 as Number)
}
```

This will work. The problem is that when you only write `+4`, you don't overload the correct `unaryPlus` operator.

**Comment by toddobryan** [comment] 2019-09-07 18:51
Can we get some movement on this. I was just bitten by it. There's a solution in dev, but it hasn't been merged back into master. In the comments on the commit, `add` is the much less verbose choice, especially when you consider that you can do `add(Number)`, `add(String)`, add(Boolean)`, and `add(null)` for all the primitives, and `add(JsonElement)` for non-primitives. It's too bad that `unaryPlus` gets confused with `Number`s, but it seems like `add` is the most concise and consistent way of doing this given that issue.

**Closed** 2020-08-17 10:10 UTC
Labels: bug, json-builder
