### ISSUE TITLE
Bad performance comparing to native JS code

### ISSUE THREAD

**Issue by blindpirate** [Kotlin/kotlinx.serialization#1258] opened 2020-12-20 14:05 UTC
**Describe the bug**

I'm writing a Game app with Kotlin JS which downloads a compressed game map JSON from backend and decompress in browser. With Kotlin serialization I wrote a (slightly complex) polymorphic deserializer, see the code below. It works well on JVM but has very bad performance issues in the browser. On the JVM, serialization/deserialization can be finished in milliseconds, but on browser - TBH - I don't know how long it takes because CPU keeps 100% for minutes and I have to kill it.

**To Reproduce**

I put a sample here: https://github.com/blindpirate/kotlin-js-bad-performance/tree/serialization-performance-issue

Note that this repo contains two performance issue reproducer, `main` branch for https://youtrack.jetbrains.com/issue/KT-42743, `serialization-performance-issue` branch for this issue I'm reporting. I highly suspect they're related.

With JS native `JSON.parse`/`stringify`:

![image](https://user-images.githubusercontent.com/12689835/102715267-33596880-430f-11eb-99a7-ebfe4fef9c9c.png)

With Kotlinx serialization:

![image](https://user-images.githubusercontent.com/12689835/102715278-466c3880-430f-11eb-9bf5-817299381f28.png)

**Expected behavior**

No performance issue.

**Environment**
 - Kotlin version: 1.4.21
 - Library version: 1.0.1
 - Kotlin platforms: JS
 - Gradle version: 6.6

**Comment by sandwwraith** [comment] 2022-09-23 12:22
Duplicate of #907

**Closed by sandwwraith** 2022-09-23 12:22 UTC
Labels: bug, js
