### ISSUE TITLE
Add JsonPath-ish like annotation to lift out nested elements

### ISSUE THREAD

**Issue by vfsfitvnm** [Kotlin/kotlinx.serialization#1896] opened 2022-04-05 22:28 UTC
**What is your use-case and why do you need this feature?**
Actually, when working with a very deep JSON object, retrieving elements is quite unpleasant. Let's say I have this object:
```json
{
  "a": {
    "b": {
      "c": {
        "d": {
          "e": {
            "f": {
              "g": {
                "h": 3
              }
            }
          }
        }
      }
    }
  }
}
```
I'd have to declare 7+1 classes in order to retrieve the information I desire. This obviously works, but when the schema gets more complex, the ongoing mental complexity is not insignificant.

Alternatively, I could use `JsonElement` and stuff to avoid the `data class` hell, then declare some helper functions e.g.
```kt
tailrec fun JsonElement.at(vararg keys: String, i: Int = 0): JsonElement {
    return when (i >= keys.lastIndex) {
        true -> jsonObject.getValue(keys.last())
        false -> jsonObject.getValue(keys[i]).iter(keys = keys, i = i + 1)
    }
}
```
This approach works too, but it makes me questioning the benefits of using `kotlinx.serialization`.

**Describe the solution you'd like**
It would be cool if there was (at least a very primitive version of) `@JsonPath` (or whatever) that could lift out nested `JsonElement`s, e.g.:
```kt
@Serializable
data class Response(
    @JsonPath("a", "b", "c", "d", "e", "f", "g")
    val h: Int
)
```
In this scenario, every key is expected to have a `JsonObject` as value.

**Comment by JakeWharton** [comment] 2022-04-06 00:38
Dupe of #648?

**Comment by vfsfitvnm** [comment] 2022-04-06 09:44
Yup, it looks like it.
However, I think a proper `JsonPath` support would be too complex; I guess there should be a meeting point between what `kotlinx.serialization` already offers and what `JsonPath` can do.

**I don't know how things are actually implemented**, but I think the solution I proposed looks very simple and straightforward to implement and, most importantly, there aren't undeterministic cases, like the following:
```
{
  "a": {
    "b": 0
  },
  "a.b": 1
}
```
This is a valid JSON, but the path `a.b` may lead to either `0` or `1` (this is just to point the solution proposed in #648 won't work).

**Closed** 2022-04-06 13:20 UTC
Labels: feature
