### ISSUE TITLE
HOCON substitutions do not work

### ISSUE THREAD

**Issue by gavvvr** [Kotlin/kotlinx.serialization#2564] opened 2024-02-07 05:01 UTC
**Describe the bug**

In HOCON config I wanted to pass a value from env var like this: `i = ${SOME_ENV_VAR}`, but it turned out that [substitutions](https://github.com/lightbend/config/blob/v1.4.3/HOCON.md#substitutions) are not supported at all.

**To Reproduce**
- Open the ["complex config" test](https://github.com/Kotlin/kotlinx.serialization/blob/1116f5f13a957feecda47d5e08b0aa335fc010fa/formats/hocon/src/test/kotlin/kotlinx/serialization/hocon/HoconObjectsTest.kt#L85-L95)
- Adjust the [test input](https://github.com/Kotlin/kotlinx.serialization/blob/1116f5f13a957feecda47d5e08b0aa335fc010fa/formats/hocon/src/test/kotlin/kotlinx/serialization/hocon/HoconObjectsTest.kt#L63) to assign value of `i` indirectly using a newly introduced variable `a` like this: 

```hocon
a = 32
i = ${a}
```

**Expected behavior**

The "complex config" test should pass

**Actual behavior**

It fails with an error:

> com.typesafe.config.ConfigException$NotResolved: need to Config#resolve(), see the API docs for Config#resolve(); substitution not resolved: ConfigReference(${a})

<details>
  <summary>Detailed stacktrace</summary>

```
com.typesafe.config.ConfigException$NotResolved: need to Config#resolve(), see the API docs for Config#resolve(); substitution not resolved: ConfigReference(${a})
	at com.typesafe.config.impl.ConfigReference.notResolved(ConfigReference.java:35)
	at com.typesafe.config.impl.ConfigReference.valueType(ConfigReference.java:42)
	at com.typesafe.config.impl.SimpleConfig.getIsNull(SimpleConfig.java:214)
	at kotlinx.serialization.hocon.Hocon$ConfigConverter$decodeTaggedNotNullMark$1.invoke(Hocon.kt:136)
	at kotlinx.serialization.hocon.Hocon$ConfigConverter$decodeTaggedNotNullMark$1.invoke(Hocon.kt:136)
	at kotlinx.serialization.hocon.Hocon$ConfigReader.getValueFromTaggedConfig(Hocon.kt:205)
	at kotlinx.serialization.hocon.Hocon$ConfigReader.getValueFromTaggedConfig(Hocon.kt:148)
	at kotlinx.serialization.hocon.Hocon$ConfigConverter.decodeTaggedNotNullMark(Hocon.kt:136)
	at kotlinx.serialization.hocon.Hocon$ConfigReader.decodeNotNullMark(Hocon.kt:170)
	at kotlinx.serialization.internal.TaggedDecoder$decodeNullableSerializableElement$1.invoke(Tagged.kt:337)
	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:294)
	at kotlinx.serialization.internal.TaggedDecoder.decodeNullableSerializableElement(Tagged.kt:286)
	at kotlinx.serialization.hocon.ConfigParserObjectsTest$ComplexConfig$$serializer.deserialize(HoconObjectsTest.kt:46)
	at kotlinx.serialization.hocon.ConfigParserObjectsTest$ComplexConfig$$serializer.deserialize(HoconObjectsTest.kt:46)
	at kotlinx.serialization.hocon.Hocon$ConfigReader.decodeSerializableValue(Hocon.kt:176)
	at kotlinx.serialization.hocon.Hocon.decodeFromConfig(Hocon.kt:63)
	at kotlinx.serialization.hocon.ConfigParserObjectsTest.complex config(HoconObjectsTest.kt:168)
```
</details>

**Comment by pdvrieze** [comment] 2024-02-07 11:48
@gavvvr As the hocon serializer doesn't do actual serialization itself (it only decodes from a Hocon Config object) the issue is that you need to call [resolve](https://lightbend.github.io/config/latest/api/com/typesafe/config/Config.html#resolve--), and use the result before using a config object (as specified in the documentation of hocon).

There is an `isResolved` function so it would be possible for the decoder to do best effort/default resolving if not explicitly resolved. already

**Comment by gavvvr** [comment] 2024-02-08 04:55
Hi @pdvrieze 

You are totally correct. I rushed to create this issue expecting too much from basic HOCON decoder. Now I see that it's my own responsibility to call `resolve()` before decoding. Thank you! Your comment has solved my problem.

**Closed** 2024-02-08 10:40 UTC
Labels: up for grabs

**Comment by pdvrieze** [comment] 2024-02-08 11:59
@sandwwraith It can be done on the serialization side as there is a way to check whether it has been done. (note that resolve doesn't mutate but returns a resolved version). If users want to do something specific they can (and this can be handled to avoid the additional resolve).

But support at kotlinx.serialization side would mainly be an ease of use feature (technically not calling resolve is an error, but it is implemented such that it doesn't matter if there are no references present in the actual file - as in the test referred to above).

**Comment by gavvvr** [comment] 2024-02-08 14:06
While deciding if any change is required on kotlinx serialization side, please note that parsing of the below HOCON also won't work without `resolve` (because `+=` is considered as a [form of substitution](https://github.com/lightbend/config/blob/v1.4.3/HOCON.md#the--field-separator) too):
```hocon
items = ["a", "b"]
items += "c"
```
