### ISSUE TITLE
Custom serializer not found when serializable class has named companion object

### ISSUE THREAD

**Issue by shwilliamson** [Kotlin/kotlinx.serialization#2046] opened 2022-09-30 16:00 UTC
Custom serializer not found when serializable class has a named companion object.  Thus test in the code snippet below will produce an error "Serializer for class 'MyClass' is not found.".  However, if you simply remove the 'MyCompanion' name from the MyClass companion, the serializer will be found, resulting in the expected NotImplemented exception in this simple example.

**To Reproduce**
```
@Serializable(with=MySerializer::class)
data class MyClass(private val abc: String = "hello") {
    companion object MyCompanion // giving this companion a name is the problem
}

object MySerializer: KSerializer<MyClass> {
    override val descriptor: SerialDescriptor
        get() = TODO("Not yet implemented")

    override fun deserialize(decoder: Decoder): MyClass {
        TODO("Not yet implemented")
    }

    override fun serialize(encoder: Encoder, value: MyClass) {
        TODO("Not yet implemented")
    }
}

inline fun <reified T> Json.toJson(obj: T): String = this.encodeToString(obj)

class MyTest {
    @Test
    fun test() {
        println(Json.toJson(MyClass()))
    }
}
```

**Expected behavior**
Simply giving a name to the companion object of the serializable class shouldn't cause custom serializers to not be found.

**Environment**
 - Kotlin version: 1.7.10
 - Library version: 1.7.10
 - Kotlin platforms: JVM
 - Gradle version: 7.5.1
 - IDE version: IntellijIDEA 2022.2.2
 - Other relevant context: Running on ARM Macbook Pro with Azul 13.0.10 JDK

**Comment by sandwwraith** [comment] 2022-10-03 13:25
Duplicate of #1726

Note that it's not possible to obtain a named companion without a dependency on a kotlin-reflect (full) library that we're trying to avoid. So it will likely stay like this until #1348 is implemented

**Closed by sandwwraith** 2022-10-03 13:25 UTC
