### ISSUE TITLE
JSON: option to serialize property names to snake_case

### ISSUE THREAD

**Issue by axelfontaine** [Kotlin/kotlinx.serialization#866] opened 2020-06-17 17:07 UTC
**What is your use-case and why do you need this feature?**

Currently properties are serialized as they appear in the source file, which is usually `camelCase` when following the Kotlin style guide.

**Describe the solution you'd like**

`snake_case` is easier on the human eye and therefore [faster to read](https://en.wikipedia.org/wiki/Camel_case#cite_note-35) when debugging. It would be great to have an option to automatically convert property names to/from `snake_case` when serializing to/from JSON.

**Comment by Dominaezzz** [comment] 2020-06-17 18:42
Duplicate of https://github.com/Kotlin/kotlinx.serialization/issues/33

**Comment by sandwwraith** [comment] 2020-06-22 14:24
There's no option to do this automatically; for now, you can use `@SerialName`.

**Closed** 2020-06-22 14:32 UTC
Labels: duplicate, feature
