### ISSUE TITLE
Unable to Specify serializer globally using typealias

### ISSUE THREAD

**Issue by SonMooSans** [Kotlin/kotlinx.serialization#2114] opened 2022-11-29 15:49 UTC
**Describe the bug**
The value is still a number even using a type alias with `@Serializable(LongAsStringSerializer::class)`
Everything is same as this [guide](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#specifying-serializer-globally-using-typealias)

**To Reproduce**
```kotlin
typealias LongAsString = @Serializable(LongAsStringSerializer::class) Long
@Serializable
data class Test(val value: LongAsString)

fun main() {
    println(Json.encodeToString(Test(100000L)))
}
```
And I got this result: `{"value":9223372036854775807}`

**Expected behavior**
prints `{"value":"9223372036854775807"}`

**Environment**
 - Kotlin version: 1.7.10
 - Library version: 1.4.21
 - Kotlin platforms: JVM
 - Gradle version: 4.10

**Comment by sandwwraith** [comment] 2022-11-29 15:52
Duplicate of #2083 — serializers for primitive types via typealias can't be set now due to a known bug. Fixed in Kotlin 1.8.20

**Closed by sandwwraith** 2022-11-29 15:52 UTC
