### ISSUE TITLE
Serializer has not been found when I switch to Kotlin 2.0

### ISSUE THREAD

**Issue by iseki0** [Kotlin/kotlinx.serialization#2692] opened 2024-05-28 03:24 UTC
**Describe the bug**
When my Kotlin 2.0.0 version project use a library that was compiled with Kotlin 1.9.0. The following code cannot compile:
```kotlin
@Serializable
data class A(
    val md5: MD5 // Serializer has not been found for type 'space.iseki.hashutil.MD5'. To use context serializer as fallback, explicitly annotate type or property with @Contextual
)
```
Are there any breaking changes? What should I do? Thank you.
**To Reproduce**

`Main.kt`: 
```kotlin
@Serializable
data class A(
    val md5: MD5
)

fun main() {
    val a = A(MD5.of("".encodeToByteArray()))
    println(Json.encodeToString(a))
}
```
`build.gradle.kts`:
```kotlin
plugins {
    kotlin("jvm") version "2.0.0"
    kotlin("plugin.serialization") version "2.0.0"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.3")
    implementation("space.iseki.hashutil:hashutil-api:0.3.0")
    testImplementation(kotlin("test"))
}
```

`MD5.java`:
```java
package space.iseki.hashutil;

import kotlinx.serialization.Serializable;

/**
 * Type for MD5
 */
@Serializable(with = MD5Serializer.class)
public final class MD5 {
    // ......
}


```

**Expected behavior**
It should be compiled.

**Environment**
 - Kotlin version: 2.0.0
 - Library version: 1.6.3
 - Kotlin platforms: JVM
 - Gradle version: 8.7
 - IDE version (if bug is related to the IDE) IntelliJ IDEA 2024.1.2
 - Other relevant context [e.g. OS version, JRE version, ... ]

**Comment by SMFDrummer** [comment] 2024-05-28 07:16
你试试把依赖从1.6.3升级到1.7.0-RC，看看还报错不

**Comment by pdvrieze** [comment] 2024-05-28 09:36
The file name for MD5 is `MD5.java`, that implies it is Java code, not Kotlin. I suspect the issue is there.

**Comment by iseki0** [comment] 2024-05-28 12:32
> 你试试把依赖从1.6.3升级到1.7.0-RC，看看还报错不

依旧报错，我也认为是 MD5<b>.java</b> 的问题

**Comment by iseki0** [comment] 2024-05-28 12:33
> The file name for MD5 is `MD5.java`, that implies it is Java code, not Kotlin. I suspect the issue is there.

Yes, that's a Java file, using `@Serializable` binds a hand-written serializer.

**Comment by sandwwraith** [comment] 2024-05-28 13:10
Was it working with 1.9.0? I'm not sure that using `@Serializable(with = MD5Serializer.class)` in Java code was ever expected to work properly, as we didn't anticipate for that

**Comment by iseki0** [comment] 2024-05-28 21:52
> Was it working with 1.9.0? I'm not sure that using `@Serializable(with = MD5Serializer.class)` in Java code was ever expected to work properly, as we didn't anticipate for that

It works on old version(1.9.x). For Java class, this is the only solution(since typealias has many other problems)

**Comment by sandwwraith** [comment] 2024-05-29 10:25
So, this is likely a difference in the K2 plugin version. I'll see if we can bring old behavior back.

**Comment by sandwwraith** [comment] 2024-06-04 16:48
I'll close this in favor of https://youtrack.jetbrains.com/issue/KT-68752/Serializable-annotation-on-Java-class-is-not-taken-into-account-in-K2-checker

**Closed by sandwwraith** 2024-06-04 16:48 UTC
Labels: bug, compiler-plugin

**Comment by vladimirfx** [comment] 2024-08-07 10:00
I just rechecked with 2.0.20-RC and the problem was reproduced.

**Comment by sandwwraith** [comment] 2024-08-07 11:54
@vladimirfx Are you sure it is the same problem? For me, `@Serializable(with = MD5Serializer.class) public final class MD5` in Java works fine on 2.0.20-RC

**Comment by vladimirfx** [comment] 2024-08-07 12:32
> @vladimirfx Are you sure it is the same problem? For me, `@Serializable(with = MD5Serializer.class) public final class MD5` in Java works fine on 2.0.20-RC

Sorry, I mean https://github.com/Kotlin/kotlinx.serialization/issues/2704 is reproducible on 2.0.20-RC

**Comment by copyandexecute** [comment] 2024-08-21 11:00
BUMP

**Comment by copyandexecute** [comment] 2024-08-21 11:01
![grafik](https://github.com/user-attachments/assets/a82b0526-31bf-466d-84be-da96790f7495)
![grafik](https://github.com/user-attachments/assets/162d77c6-bee4-465f-a6d2-c5c206aca872)

It worked perfectly fine on 
"1.9.23", how to fix?

**Comment by sandwwraith** [comment] 2024-08-21 12:39
@copyandexecute See https://github.com/Kotlin/kotlinx.serialization/issues/2731#issuecomment-2195217655
